// Catálogo de los Misterios — estudios publicados de Jashmal.
// Cada misterio es una landing en /misterio/{slug}. Para añadir uno nuevo,
// agrega una entrada aquí y crea su página.

export interface Misterio {
  slug: string;          // ruta: /misterio/{slug} y atajo /{slug}
  numero?: string;       // número/gematría destacado (ej. "358")
  he: string;            // término hebreo central
  titulo: string;        // título en español (canónico)
  tituloFa: string;
  tituloEn?: string;     // inglés — lo llena el Sofer por fases ([[i18n-audit]])
  gancho: string;        // una línea de gancho (español)
  ganchoFa: string;
  ganchoEn?: string;     // inglés — lo llena el Sofer por fases
  serie?: string;        // nombre de la serie (para agrupar)
  color: string;
  orden: number;         // orden de aparición (menor = primero)
}

export const MISTERIOS: Misterio[] = [
  {
    slug: "358",
    numero: "358",
    he: "מָשִׁיחַ = נָחָשׁ",
    titulo: "El Mesías y la Serpiente",
    tituloFa: "ماشیح و مار",
    tituloEn: "The Messiah and the Serpent",
    gancho: "El redentor y la serpiente del Edén comparten el mismo número. La Cabalá lo sabía hace 800 años.",
    ganchoFa: "رهاننده و مارِ عدن یک عدد دارند. کابالا ۸۰۰ سال است این را می‌داند.",
    ganchoEn: "The redeemer and the serpent of Eden share the same number. Kabbalah has known it for 800 years.",
    serie: "dos-filos",
    color: "#c9a43e",
    orden: 1,
  },
  {
    slug: "26",
    numero: "26",
    he: "אֶחָד · אַהֲבָה",
    titulo: "Unidad y Amor",
    tituloFa: "یگانگی و عشق",
    tituloEn: "Oneness and Love",
    gancho: "Ejad (Uno) y Ahavá (Amor) suman lo mismo: 26 — el Nombre de Dios. La unidad y el amor son Su Nombre.",
    ganchoFa: "اِچاد (یک) و اَهاوا (عشق) برابرند: ۲۶ — نامِ خدا.",
    ganchoEn: "Echad (One) and Ahavah (Love) add up to the same: 26 — the Name of God. Oneness and love are His Name.",
    serie: "dos-filos",
    color: "#f0d060",
    orden: 2,
  },
  {
    slug: "tamar",
    he: "תָּמָר",
    titulo: "El velo que escondía al Mesías",
    tituloFa: "تامار — حجابی که ماشیح را پنهان می‌کرد",
    tituloEn: "The Veil That Hid the Messiah",
    gancho: "El mayor escándalo de la Torá esconde el nacimiento de la línea del Mashíaj. Mientras los hombres veían vergüenza, el Cielo encendía la luz del Redentor.",
    ganchoFa: "بزرگ‌ترین رسواییِ تورات، تولدِ تبارِ ماشیح را پنهان می‌کند. آنچه جهان می‌پوشاند، خدا تاج می‌بخشد.",
    ganchoEn: "The greatest scandal in the Torah conceals the birth of the line of Mashiach. While men saw shame, Heaven was kindling the light of the Redeemer.",
    serie: "dos-filos",
    color: "#c9a43e",
    orden: 3,
  },
  {
    slug: "betsabe",
    he: "בַּת־שֶׁבַע",
    titulo: "Betsabé — El viajero que se quedó a vivir",
    tituloFa: "بَت‌شِبَع — مسافری که ماند تا بماند",
    tituloEn: "Bathsheba — The Traveler Who Came to Stay",
    gancho: "¿Quién se acostó con Betsabé: el rey David… o un viajero extraño? El Talmud lee la caída más famosa de la Biblia con una sola imagen —el huésped que se vuelve amo— y, en su raíz, esconde la luz del Mashíaj.",
    ganchoFa: "چه کسی با بَت‌شِبَع خوابید: داوودِ پادشاه… یا مسافری بیگانه؟ تلمود مشهورترین سقوطِ کتاب مقدس را با یک تصویر می‌خواند —مهمانی که ارباب می‌شود— و در ریشه‌اش، نورِ ماشیح را پنهان می‌کند.",
    ganchoEn: "Who lay with Bathsheba: King David… or a strange traveler? The Talmud reads the most famous fall in the Bible through a single image —the guest who becomes the master— and, at its root, it hides the light of Mashiach.",
    serie: "dos-filos",
    color: "#cf8c52",
    orden: 3.5,
  },
  {
    slug: "lot",
    he: "לוֹט",
    titulo: "Lot — Las dos hijas sin nombre",
    tituloFa: "لوط — دو دخترِ بی‌نام",
    tituloEn: "Lot — The Two Nameless Daughters",
    gancho: "Las dos mujeres de las que nace el linaje del Rey David no tienen nombre… y lo que hicieron rompió todo tabú. Del barro más bajo —una cueva, tras el fin de un mundo— el Cielo sacó la corona del Mashíaj.",
    ganchoFa: "دو زنی که تبارِ داوودِ پادشاه از آنان زاده می‌شود، نامی ندارند… و آنچه کردند هر تابویی را شکست. از پست‌ترین گِل، خدا تاجِ ماشیح را برآورد.",
    ganchoEn: "The two women from whom the lineage of King David is born have no name… and what they did broke every taboo. From the lowest clay —a cave, after the end of a world— Heaven drew out the crown of Mashiach.",
    serie: "dos-filos",
    color: "#d8a24a",
    orden: 3.7,
  },
  {
    slug: "yehuda",
    he: "צָדְקָה מִמֶּנִּי",
    titulo: "Yehudá — El rey que se declaró culpable",
    tituloFa: "یهودا — پادشاهی که خود را گناهکار خواند",
    tituloEn: "Yehudah — The King Who Pleaded Guilty",
    gancho: "Pudo callar y dejarla arder. En cambio dijo dos palabras —«ella es más justa que yo»— y se hundió en público para salvarla. Esa confesión le ganó el cetro eterno, el Nombre de Dios dentro de su nombre, y la línea directa del Mashíaj ben David.",
    ganchoFa: "می‌توانست خاموش بماند و بگذارد بسوزد. اما دو واژه گفت —«او از من پارساتر است»— و در برابر همگان خود را فروشکست تا او را برهاند. آن اعتراف، عصای جاودان، نامِ خدا را در نامش، و تبارِ مستقیمِ ماشیح بن داوود را به او بخشید.",
    ganchoEn: "He could have kept silent and let her burn. Instead he spoke two words —“she is more righteous than I”— and lowered himself in public to save her. That confession won him the eternal scepter, the Name of God within his name, and the direct line of Mashiach ben David.",
    serie: "dos-filos",
    color: "#caa23f",
    orden: 3.8,
  },
  {
    slug: "ropas-de-luz",
    he: "כָּתְנוֹת עוֹר · אוֹר",
    titulo: "De Ropas de Luz a Piel de Serpiente",
    tituloFa: "از جامه‌های نور تا پوست مار",
    tituloEn: "From Garments of Light to Serpent's Skin",
    gancho: "Una sola letra separa la «ropa de luz» (אוֹר) de la «ropa de piel» (עוֹר). Hubo una falta real en el Edén — pero esa caída tenía un lugar en el plan: vestir la luz de piel para que el hombre la rescate desde abajo. La caída necesaria para el Tikún.",
    ganchoFa: "تنها یک حرف، «جامهٔ نور» (אוֹר) را از «جامهٔ پوست» (עוֹר) جدا می‌کند. در عدن لغزشی واقعی رخ داد — اما آن سقوط جایی در نقشه داشت: سقوطِ لازم برای تیکون.",
    ganchoEn: "A single letter separates the “garment of light” (אוֹר) from the “garment of skin” (עוֹר). There was a real fault in Eden — but that fall had a place in the plan: to clothe the light in skin so that man could rescue it from below. The fall the Tikkun required.",
    serie: "dos-filos",
    color: "#cf8c52",
    orden: 3.9,
  },
  {
    slug: "chispas-en-las-naciones",
    numero: "288",
    he: "רפ״ח נִיצוֹצוֹת",
    titulo: "Las chispas del Mashíaj en las naciones",
    tituloFa: "جرقه‌های ماشیح در میان ملت‌ها",
    tituloEn: "The Sparks of Mashiach Among the Nations",
    gancho: "El linaje del Mashíaj no es «puro»: Rut la moabita, Rajav la cananea, Naamá la amonita, Yitró el midianita. Las chispas más altas cayeron más lejos —entre las naciones— y la redención es recogerlas. El converso es una chispa que vuelve a casa.",
    ganchoFa: "تبارِ ماشیح «پاک» نیست: روتِ موآبی، راحاوِ کنعانی، نَعَمای عَمّونی، یترُوی مدیانی. برترین جرقه‌ها دورتر افتادند — میان ملت‌ها — و رستگاری یعنی گردآوریِ آن‌ها. گِر (نوكیش) جرقه‌ای است که به خانه بازمی‌گردد.",
    ganchoEn: "The lineage of Mashiach is not “pure”: Ruth the Moabite, Rahab the Canaanite, Naamah the Ammonite, Yitro the Midianite. The highest sparks fell farthest —among the nations— and redemption means gathering them back. The convert is a spark coming home.",
    serie: "dos-filos",
    color: "#dcae46",
    orden: 4.5,
  },
  {
    slug: "linaje",
    he: "עֲבֵרָה לִשְׁמָהּ",
    titulo: "El linaje prohibido del Mashíaj",
    tituloFa: "تبارِ ممنوعِ ماشیح",
    tituloEn: "The Forbidden Lineage of Mashiach",
    gancho: "El Mashíaj desciende por los lugares más caídos: incesto, prostitución, adulterio. La sombra, dada vuelta, es la luz.",
    ganchoFa: "ماشیح از فروافتاده‌ترین جاها فرود می‌آید. سایه، وارونه، نور است.",
    ganchoEn: "Mashiach descends through the most fallen places: incest, prostitution, adultery. The shadow, turned over, is the light.",
    serie: "dos-filos",
    color: "#e0a850",
    orden: 4,
  },
  {
    slug: "habakuk",
    numero: "216",
    he: "חֲבַקּוּק",
    titulo: "Habakuk y el doble abrazo",
    tituloFa: "حَبَقّوق و دو آغوش",
    tituloEn: "Habakkuk and the Double Embrace",
    gancho: "Shigyonot: ¿errores o instrumentos? Habakuk: ¿un abrazo o dos? Una palabra con dos filos, y una gematría que abraza la partición del mar.",
    ganchoFa: "شیگیونوت: خطاها یا سازها؟ حَبَقّوق: یک آغوش یا دو؟ یک واژه با دو لبه.",
    ganchoEn: "Shigyonot: errors or instruments? Habakkuk: one embrace or two? A word with two edges, and a gematria that embraces the splitting of the sea.",
    serie: "dos-filos",
    color: "#b89a4e",
    orden: 5,
  },
  {
    slug: "pinjas",
    he: "פִּינְחָס",
    titulo: "El Misterio del Fuego",
    tituloFa: "رازِ آتش",
    tituloEn: "The Mystery of Fire",
    gancho: "La lanza de Pinjás fue una oración. El tikún de la serpiente del Edén, las almas de Nadav y Avihu, y el brit shalom — todo convergió en un momento.",
    ganchoFa: "نیزهٔ پینحاس یک دعا بود. تیکونِ مارِ عدن، جان‌های نَداو و اَویهو، و بریت‌شالوم — همه در یک لحظه تقاطع کردند.",
    ganchoEn: "Pinchas's spear was a prayer. The tikun of the Eden serpent, the souls of Nadav and Avihu, and the brit shalom — all converged in one moment.",
    serie: "dos-filos",
    color: "#c94a2e",
    orden: 6.5,
  },
  {
    slug: "bilaam",
    he: "בִּלְעָם",
    titulo: "Bilaam — la boca de la serpiente",
    tituloFa: "بیلعام — دهانِ مار",
    tituloEn: "Balaam — The Mouth of the Serpent",
    gancho: "El hechicero con el espíritu de Samael vino a maldecir a Israel — y de su boca salió la profecía mesiánica más profunda de la Biblia. Del lugar más oscuro, la luz más brillante.",
    ganchoFa: "جادوگری با روحِ سَمائل آمد تا نفرین کند — و از دهانش ژرف‌ترین پیشگوییِ مسیحایی برآمد.",
    ganchoEn: "The sorcerer with the spirit of Samael came to curse Israel — and from his mouth came the deepest messianic prophecy in the Bible. From the darkest place, the brightest light.",
    serie: "dos-filos",
    color: "#9a6a8e",
    orden: 6,
  },
  {
    slug: "137",
    numero: "137",
    he: "קַבָּלָה",
    titulo: "137 — El acertijo de la creación",
    tituloFa: "۱۳۷ — معمای آفرینش",
    tituloEn: "137 — The Riddle of Creation",
    gancho: "Kabalah = 137. Y la constante de estructura fina α ≈ 1/137 que gobierna la luz. El número que une la Cabalá con la física (Rav Ginsburgh).",
    ganchoFa: "قبالا = ۱۳۷. و ثابتِ ساختارِ ریز α ≈ ۱/۱۳۷ که نور را حکم می‌راند. عددی که کابالا را با فیزیک می‌پیوندد.",
    ganchoEn: "Kabbalah = 137. And the fine-structure constant α ≈ 1/137 that governs light. The number that joins Kabbalah with physics (Rav Ginsburgh).",
    serie: "gematria",
    color: "#9a6a8e",
    orden: 7,
  },
  {
    slug: "entrelazamiento",
    numero: "137",
    he: "אַהֲבָה ⊗ יִרְאָה",
    titulo: "El entrelazamiento de las almas",
    tituloFa: "درهم‌تنیدگیِ جان‌ها",
    tituloEn: "The Entanglement of Souls",
    gancho: "Amor (42 veces) + Temor (95 veces) = 137. En la atadura de Isaac, el amor y el temor quedan entrelazados — como dos partículas que actúan como una. Y la Cabalá (=137) es la constante que acopla el alma con Dios.",
    ganchoFa: "عشق (۴۲ بار) + ترس (۹۵ بار) = ۱۳۷. در بستنِ اسحاق، عشق و ترس درهم‌تنیده می‌شوند — چون دو ذرّه که چون یکی رفتار می‌کنند. و کابالا (=۱۳۷) ثابتی است که جان را به خدا می‌پیوندد.",
    ganchoEn: "Love (42 times) + Fear (95 times) = 137. In the binding of Isaac, love and fear become entangled — like two particles acting as one. And Kabbalah (=137) is the constant that couples the soul to God.",
    serie: "gematria",
    color: "#b5557a",
    orden: 8,
  },
  {
    slug: "chashmal-vav",
    numero: "378",
    he: "חַשְׁמַל · וָאו",
    titulo: "El Chashmal — el silencio que habla",
    tituloFa: "چَشمَل — سکوتی که سخن می‌گوید",
    tituloEn: "The Chashmal — The Silence That Speaks",
    gancho: "La palabra más misteriosa de la Biblia lleva dentro su propio secreto: חש (silencio, 308) + מל (habla, 70) = 378 = חשמל. Y la vav, el «y» más simple del hebreo, se expande hasta revelar exactamente 137 — la constante de la luz.",
    ganchoFa: "رازآمیزترین واژهٔ کتاب مقدس، رازِ خود را در درون دارد: חש (سکوت، ۳۰۸) + מל (سخن، ۷۰) = ۳۷۸ = חשמל. و واو، سادهٔ‌ترین «و» در عبری، گسترش می‌یابد تا دقیقاً ۱۳۷ را آشکار کند.",
    ganchoEn: "The most mysterious word in the Bible carries its own secret within: חש (silence, 308) + מל (speech, 70) = 378 = חשמל. And the vav, the simplest “and” in Hebrew, expands to reveal exactly 137 — the constant of light.",
    serie: "gematria",
    color: "#7855bb",
    orden: 8.3,
  },
  {
    slug: "machlokot-koraj",
    numero: "578",
    he: "מַחֲלֹקֶת",
    titulo: "Koraj — cuando la verdad se vuelve un arma",
    tituloFa: "قورَح — وقتی حقیقت به سلاح بدل می‌شود",
    tituloEn: "Korach — When Truth Becomes a Weapon",
    gancho: "Koraj tenía razón: «todos somos santos» es verdad. Pero la usó como arma. Machlóket (disputa) = 578 = Shalom (paz, 376) + Rav (grandeza, 202). La paz más el ego produce la guerra.",
    ganchoFa: "قورَح حق داشت: «همه مقدسیم» راست است. اما آن را چون سلاح به کار برد. مَحلوقت (نزاع) = ۵۷۸ = شالوم (صلح، ۳۷۶) + رَو (بزرگی، ۲۰۲). صلح به‌علاوهٔ خودبزرگی، جنگ می‌زاید.",
    ganchoEn: "Korach was right: “we are all holy” is true. But he used it as a weapon. Machloket (dispute) = 578 = Shalom (peace, 376) + Rav (greatness, 202). Peace plus ego breeds war.",
    serie: "gematria",
    color: "#b0413e",
    orden: 8.7,
  },
  {
    slug: "arca-no-ocupa-lugar",
    numero: "216",
    he: "מְקוֹם אָרוֹן",
    titulo: "El Arca que no ocupaba lugar",
    tituloFa: "تابوتِ عهد که مکان نمی‌گرفت",
    tituloEn: "The Ark That Took Up No Space",
    gancho: "10 + 2,5 + 10 = 22,5 codos… en un cuarto de 20. El Talmud lo dice sin rodeos: el Arca estaba presente por completo y no ocupaba lugar. דְּבִיר = גְּבוּרָה = 216: el lugar de máxima contracción es donde la Luz infinita mora sin medida.",
    ganchoFa: "۱۰ + ۲٫۵ + ۱۰ = ۲۲٫۵ ذراع… در اتاقی بیست‌ذراعی. تلمود بی‌پرده می‌گوید: تابوت به‌تمامی حاضر بود و مکان اشغال نمی‌کرد. דְּבִיר = גְּבוּרָה = ۲۱۶: جای بیشترین تنگنا همان‌جاست که نورِ بی‌کران بی‌اندازه ساکن می‌شود.",
    ganchoEn: "10 + 2.5 + 10 = 22.5 cubits… in a 20-cubit room. The Talmud says it plainly: the Ark was fully present yet took up no space. דְּבִיר = גְּבוּרָה = 216: the place of deepest contraction is where the infinite Light dwells without measure.",
    serie: "gematria",
    color: "#c9a43e",
    orden: 8.9,
  },
  {
    slug: "enoch",
    numero: "84",
    he: "חֲנוֹךְ",
    titulo: "Janóoj — la gracia que asciende",
    tituloFa: "حَنوخ — فیضی که بالا می‌رود",
    tituloEn: "Chanoch — The Grace That Ascends",
    gancho: "Janóoj «caminó con Dios y desapareció, porque Dios lo tomó». El iniciado que asciende y se vuelve Metatrón, el canal universal (=314). Su nombre (חֲנוֹךְ) y «educación» (חִינּוּךְ) comparten una raíz: el camino que vuelve al hombre vehículo de luz.",
    ganchoFa: "خنوخ «با خدا راه رفت و ناپدید شد، زیرا خدا او را برگرفت». مبتدی‌ای که بالا می‌رود و مِطَطرون می‌شود، کانالِ جهانی (=۳۱۴). نامِ او (חֲנוֹךְ) و «تربیت» (חִינּוּךְ) یک ریشه دارند: راهی که انسان را مرکبِ نور می‌کند.",
    ganchoEn: "Chanoch “walked with God and was no more, for God took him.” The initiate who ascends and becomes Metatron, the universal channel (=314). His name (חֲנוֹךְ) and “education” (חִינּוּךְ) share one root: the path that turns man into a vehicle of light.",
    serie: "gematria",
    color: "#6cd4e0",
    orden: 8.5,
  },
  {
    slug: "sanador",
    he: "יְהוָה רֹפְאֶךָ",
    titulo: "Yo soy Hashem tu sanador",
    tituloFa: "من خداوند، شفادهندهٔ تو",
    tituloEn: "I Am Hashem Your Healer",
    gancho: "«Yo soy Hashem tu sanador» (Éxodo 15:26). La sanidad no es algo que Dios envía — es uno de Sus Nombres. Y la primera cura es el perdón (Salmos 103:3).",
    ganchoFa: "«من خداوند، شفادهندهٔ توام» (خروج ۱۵:۲۶). شفا چیزی نیست که خدا بفرستد — یکی از نام‌های اوست. و نخستین شفا، آمرزش است (مزامیر ۱۰۳:۳).",
    ganchoEn: "“I am Hashem your healer” (Exodus 15:26). Healing is not something God sends — it is one of His Names. And the first cure is forgiveness (Psalms 103:3).",
    serie: "sanidad",
    color: "#3fa68a",
    orden: 9,
  },
  {
    slug: "refael",
    numero: "311",
    he: "רְפָאֵל",
    titulo: "Refael — «Dios sana»",
    tituloFa: "رفائل — «خدا شفا می‌دهد»",
    tituloEn: "Refael — “God Heals”",
    gancho: "Refael (=311) es el ángel cuyo nombre dice «Dios sana». Curó a Abraham tras la circuncisión — y el mismo ángel que sana es el que rescata. רפא (281) + אל (31) = 312 = 311+1, el sello del kolel.",
    ganchoFa: "رفائل (=۳۱۱) فرشته‌ای است که نامش می‌گوید «خدا شفا می‌دهد». ابراهام را پس از ختنه شفا داد — و همان فرشته که شفا می‌دهد، همان است که می‌رهاند.",
    ganchoEn: "Refael (=311) is the angel whose name says “God heals.” He healed Abraham after the circumcision — and the same angel who heals is the one who rescues. רפא (281) + אל (31) = 312 = 311+1, the seal of the kolel.",
    serie: "sanidad",
    color: "#5b8fd6",
    orden: 10,
  },
  {
    slug: "serpiente-de-cobre",
    numero: "358",
    he: "נְחַשׁ הַנְּחֹשֶׁת",
    titulo: "La serpiente de cobre",
    tituloFa: "مارِ مفرغین",
    tituloEn: "The Copper Serpent",
    gancho: "La medicina tenía la forma exacta de la enfermedad. Nájash (serpiente) = Mashíaj = 358: la fuerza que envenena, elevada hacia lo Alto, se vuelve la cura.",
    ganchoFa: "درمان درست به شکلِ بیماری بود. مار (نَحَش) = ماشیح = ۳۵۸: نیرویی که زهر می‌ریزد، برافراشته به سویِ بالا، شفا می‌شود.",
    ganchoEn: "The medicine had the exact shape of the disease. Nachash (serpent) = Mashiach = 358: the force that poisons, raised toward Heaven, becomes the cure.",
    serie: "sanidad",
    color: "#b06a3c",
    orden: 11,
  },
  {
    slug: "refua",
    he: "רְפוּאַת הַנֶּפֶשׁ וּרְפוּאַת הַגּוּף",
    titulo: "Sanación del alma y del cuerpo",
    tituloFa: "شفایِ جان و شفایِ تن",
    tituloEn: "Healing of the Soul and the Body",
    gancho: "El alma va primero, y el cuerpo después. No prometemos que el cuerpo siempre sane — pero el alma siempre puede volver a casa.",
    ganchoFa: "نخست جان، آنگاه تن. وعده نمی‌دهیم که تن همیشه شفا یابد — اما جان همیشه می‌تواند به خانه برگردد.",
    ganchoEn: "The soul goes first, and the body after. We do not promise the body will always heal — but the soul can always come home.",
    serie: "sanidad",
    color: "#7d9b8a",
    orden: 12,
  },
  {
    slug: "21-pactos",
    numero: "21",
    he: "אֶהְיֶה",
    titulo: "El Nombre que vale 21",
    tituloFa: "نامی که ۲۱ است",
    tituloEn: "The Name That Equals 21",
    gancho: "Ehyé (אהיה), «Yo Seré» (Éx 3:14), suma 21 — y la Torá guarda 21 pactos que sostienen toda la realidad. En clave de sod, esos 21 son Ehyé hecho estructura: Biná, la octava sefirá.",
    ganchoFa: "اَهیه (אהיה)، «خواهم بود» (خروج ۳:۱۴)، برابر ۲۱ است — و تورات ۲۱ پیمان را نگاه می‌دارد که تمامِ هستی را برپا می‌دارند. در کلیدِ سود، این ۲۱ همان اَهیه است که ساختار شده: بینا.",
    ganchoEn: "Ehyeh (אהיה), “I Shall Be” (Ex 3:14), equals 21 — and the Torah holds 21 covenants that sustain all of reality. In the key of sod, those 21 are Ehyeh made structure: Binah, the eighth sefirah.",
    serie: "gematria",
    color: "#1fd8e0",
    orden: 13,
  },

  // ── SERIE "MASHÍAJ" — Del Enigma del Mashíaj al Ajarít HaYamim ──────────────
  // 13 estudios: Estudio 0 (la Puerta, publicado) + 12 módulos (placeholders
  // "próximamente" hasta que el Sofer los escriba). Slugs según 00-MAPA-SERIE.md.
  {
    slug: "enigma-mashiaj",
    he: "חִידַת הַמָּשִׁיחַ",
    titulo: "El Enigma del Mashíaj — La Tesis",
    tituloFa: "معمای ماشیح — نهاد",
    tituloEn: "The Enigma of Mashiach — The Thesis",
    gancho: "¿Persona, conciencia colectiva o estado de conciencia? El Mashíaj es las tres — y casi nadie lo sabe. Capítulo 1, la Tesis: el despertar desde abajo, la redención que subimos con nuestras obras. La puerta de la serie sobre el fin de los días.",
    ganchoFa: "شخص، آگاهیِ جمعی یا حالتِ آگاهی؟ ماشیح هر سه است — و کمتر کسی این را می‌داند. فصلِ ۱، نهاد: بیداری از پایین، رستگاری‌ای که با کارهای خود بالا می‌بریم. دروازهٔ سری دربارهٔ آخریتِ روزها.",
    ganchoEn: "A person, a collective consciousness, or a state of consciousness? Mashiach is all three — and almost no one knows it. Chapter 1, the Thesis: the awakening from below, the redemption we raise with our deeds. The gate of the series on the end of days.",
    serie: "mashiaj",
    color: "#c9a43e",
    orden: 0,
  },
  {
    slug: "despertar-de-lo-alto",
    he: "אִתְעֲרוּתָא דִּלְעֵילָא",
    titulo: "El Despertar desde Arriba — La Antítesis",
    tituloFa: "بیداری از بالا — پادنهاد",
    tituloEn: "The Awakening from Above — The Antithesis",
    gancho: "Creías que la redención la subimos nosotros. La otra mitad del enigma gira el espejo: el Mashíaj es, antes que nada, descenso — Dios baja primero, y la luz más alta no se gana: se recibe. Capítulo 2, la Antítesis.",
    ganchoFa: "می‌پنداشتی رستگاری را ما بالا می‌بریم. نیمهٔ دیگرِ معما آینه را می‌چرخاند: ماشیح پیش از هر چیز فرود است — خدا نخست پایین می‌آید، و برترین نور به دست نمی‌آید: دریافت می‌شود. فصلِ ۲، پادنهاد.",
    ganchoEn: "You thought redemption was something we raise ourselves. The other half of the enigma turns the mirror around: Mashiach is, before all else, descent — God comes down first, and the highest light is not earned: it is received. Chapter 2, the Antithesis.",
    serie: "mashiaj",
    color: "#caa23f",
    orden: 0.02,
  },
  {
    slug: "tercer-templo",
    he: "בֵּית הַמִּקְדָּשׁ הַשְּׁלִישִׁי",
    titulo: "El Tercer Templo — La Síntesis",
    tituloFa: "معبدِ سوم — هم‌نهاد",
    tituloEn: "The Third Temple — The Synthesis",
    gancho: "Una redención sube, la otra baja. ¿Cuál es la verdadera? Las dos a la vez — y la prueba se puede tocar: el Tercer Templo. El hombre levanta los muros; Dios trae el fuego desde lo Alto. Capítulo 3, la Síntesis que sella la Puerta.",
    ganchoFa: "یک رستگاری بالا می‌رود، دیگری پایین می‌آید. کدام راستین است؟ هر دو با هم — و گواهش لمس‌شدنی است: معبدِ سوم. انسان دیوارها را برمی‌افرازد؛ خدا آتش را از بالا می‌آورد. فصلِ ۳، هم‌نهادی که دروازه را مُهر می‌کند.",
    ganchoEn: "One redemption ascends, the other descends. Which is the true one? Both at once — and the proof can be touched: the Third Temple. Man raises the walls; God brings the fire from Above. Chapter 3, the Synthesis that seals the Gate.",
    serie: "mashiaj",
    color: "#cf8c52",
    orden: 0.04,
  },
  {
    // Puerta de las luces dentro de la serie del Mashíaj. Verificado por el
    // Sofer (scratchpad/estudio-cinco-luces.md). Los campos Fa replican el
    // español a propósito hasta que llegue la traducción verificada.
    slug: "cinco-luces-mashiaj",
    numero: "207",
    he: "אוֹר",
    titulo: "Las Cinco Luces y su revelación en el Mashíaj",
    tituloFa: "Las Cinco Luces y su revelación en el Mashíaj",
    tituloEn: "The Five Lights and Their Revelation in Mashiach",
    gancho:
      "La luz del primer día no es la del sol — el sol recién aparece en el cuarto día. La palabra «luz» suena cinco veces en ese día, y la tradición la nombra de cinco maneras: directa, retornante, interior, circundante, guardada. Un midrash dice para quién quedó guardada. Or = Raz = Ein Sof = 207.",
    ganchoFa:
      "La luz del primer día no es la del sol — el sol recién aparece en el cuarto día. La palabra «luz» suena cinco veces en ese día, y la tradición la nombra de cinco maneras: directa, retornante, interior, circundante, guardada. Un midrash dice para quién quedó guardada. Or = Raz = Ein Sof = 207.",
    ganchoEn:
      "The light of the first day is not the sun's — the sun only appears on day four. The word “light” sounds five times on that day, and tradition names it in five ways: direct, returning, inner, surrounding, hidden. One midrash says for whom it was stored away. Or = Raz = Ein Sof = 207.",
    serie: "mashiaj",
    color: "#e8c96a",
    orden: 0.045,
  },
  {
    slug: "simiente-mesianica",
    he: "הַזֶּרַע הַמְּשִׁיחִי",
    titulo: "La Simiente Mesiánica",
    tituloFa: "بذرِ ماشیحی",
    tituloEn: "The Messianic Seed",
    gancho: "Una simiente —una zéra— atraviesa toda la historia como si tuviera voluntad propia: un hilo fino de descendencia que sobrevive a cada intento de cortarlo y avanza por los caminos más improbables hasta el rey que repara la fractura del Edén. El Midrash la llama «la simiente que viene de otro lugar».",
    ganchoFa: "بذری —یک زِرَع— گویی با ارادهٔ خود از سراسرِ تاریخ می‌گذرد: رشته‌ای باریک از نسل که از هر کوششی برای بریدنش جان به‌در می‌برد و از ناممکن‌ترین راه‌ها تا پادشاهی که شکافِ عدن را ترمیم می‌کند پیش می‌رود. میدراش آن را «بذری که از جای دیگر می‌آید» می‌نامد.",
    ganchoEn: "One seed —one zera— crosses all of history as if it had a will of its own: a thin thread of descent that survives every attempt to cut it and advances along the most improbable paths to the king who repairs the fracture of Eden. The Midrash calls it “the seed that comes from another place.”",
    serie: "mashiaj",
    color: "#d8a24a",
    orden: 0.05,
  },
  {
    slug: "ajarit-hayamim",
    he: "אַחֲרִית הַיָּמִים",
    titulo: "¿Qué es Ajarít HaYamim?",
    tituloFa: "آخریتِ روزها چیست؟",
    tituloEn: "What Is Acharit HaYamim?",
    gancho: "«Ajarít hayamim» no significa el final del mundo. Significa el mundo llegando a ser lo que siempre debió ser. Cuatro términos que el público confunde —Gueulá, Yemot HaMashíaj, Tejiyat HaMetim, Olam HaBa— son grados de un solo ascenso.",
    ganchoFa: "«آخریتِ روزها» پایانِ جهان نیست. یعنی جهانی که سرانجام همان می‌شود که همیشه باید می‌بود — کمالِ زمان، نه پایانِ آن.",
    ganchoEn: "“Acharit hayamim” does not mean the end of the world. It means the world becoming what it was always meant to be. Four terms the public confuses —Geulah, Yemot HaMashiach, Techiyat HaMetim, Olam HaBa— are degrees of a single ascent.",
    serie: "mashiaj",
    color: "#caa23f",
    orden: 0.1,
  },
  {
    slug: "finalidad-creacion",
    numero: "45",
    he: "תַּכְלִית הַבְּרִיאָה",
    titulo: "La Finalidad de la Creación",
    tituloFa: "غایتِ آفرینش",
    tituloEn: "The Purpose of Creation",
    gancho: "Dios no creó el mundo y luego decidió redimirlo. Lo creó porque quería una casa aquí abajo. La redención es la mudanza. Gueulá = Adam = 45.",
    ganchoFa: "خدا جهان را نیافرید و سپس به رستگاری‌اش بیندیشد. آفرید چون خانه‌ای در پایین می‌خواست. رستگاری همان اسباب‌کشی است. گئولا = آدام = ۴۵.",
    ganchoEn: "God did not create the world and then decide to redeem it. He created it because He wanted a home down here. Redemption is the moving-in. Geulah = Adam = 45.",
    serie: "mashiaj",
    color: "#cf8c52",
    orden: 0.2,
  },
  {
    slug: "exilio-redencion",
    numero: "44→45",
    he: "גָּלוּת וּגְאוּלָּה",
    titulo: "Exilio y Redención en los Profetas",
    tituloFa: "تبعید و رستگاری در پیامبران",
    tituloEn: "Exile and Redemption in the Prophets",
    gancho: "Golá (exilio) = 44; Gueulá (redención) = 45. Entre el exilio y la redención hay una sola letra: la א, el Alef — Dios mismo entrando en la palabra. La redención empieza en el corazón, no en la política.",
    ganchoFa: "گولا (تبعید) = ۴۴؛ گئولا (رستگاری) = ۴۵. میانِ تبعید و رستگاری تنها یک حرف است: الف — خودِ خدا. رستگاری از دل آغاز می‌شود، نه از سیاست.",
    ganchoEn: "Golah (exile) = 44; Geulah (redemption) = 45. Between exile and redemption there is a single letter: the א, the Alef — God Himself entering the word. Redemption begins in the heart, not in politics.",
    serie: "mashiaj",
    color: "#d8a24a",
    orden: 0.3,
  },
  {
    slug: "mashiaj-jazal",
    numero: "138",
    he: "הַמָּשִׁיחַ בְּדִבְרֵי חֲזַ״ל",
    titulo: "El Mashíaj en la Literatura Rabínica",
    tituloFa: "ماشیح در ادبیاتِ ربانی",
    tituloEn: "Mashiach in Rabbinic Literature",
    gancho: "El Talmud no se pone de acuerdo en el nombre del Mashíaj: ¿Shiló? ¿Yinón? ¿Janiná? ¿Menajem? Y tiene razón en todos. Menajem (el Consolador) = Tzémaj (el Retoño) = 138: consolar es hacer retoñar.",
    ganchoFa: "تلمود بر نامِ ماشیح اتفاق ندارد: شیلو؟ یینون؟ حنینا؟ مناحم؟ و در همه حق دارد. مناحم (تسلی‌دهنده) = تسماخ (جوانه) = ۱۳۸: تسلی‌دادن یعنی جوانه‌زدن.",
    ganchoEn: "The Talmud cannot agree on the name of Mashiach: Shiloh? Yinnon? Chaninah? Menachem? And it is right about all of them. Menachem (the Comforter) = Tzemach (the Sprout) = 138: to comfort is to make sprout.",
    serie: "mashiaj",
    color: "#dcae46",
    orden: 0.4,
  },
  {
    slug: "daniel-apocaliptica",
    he: "דָּנִיֵּאל וְהַחֲזוֹן",
    titulo: "Daniel y la Apocalíptica",
    tituloFa: "دانیال و مکاشفه",
    tituloEn: "Daniel and Apocalyptic Literature",
    gancho: "La primera vez que la Biblia promete que los muertos despertarán está escondida en un libro «sellado hasta el fin». Las cuatro bestias, el fin de los imperios y la resurrección, en clave.",
    ganchoFa: "نخستین باری که کتاب مقدس وعده می‌دهد مردگان بیدار خواهند شد، در کتابی «مُهرشده تا پایان» پنهان است. چهار جانور، پایانِ امپراتوری‌ها و رستاخیز، در رمز.",
    ganchoEn: "The first time the Bible promises that the dead will awaken is hidden in a book “sealed until the end.” The four beasts, the end of the empires and the resurrection, in code.",
    serie: "mashiaj",
    color: "#b89a4e",
    orden: 0.5,
  },
  {
    slug: "gog-umagog",
    numero: "26",
    he: "גּוֹג וּמָגוֹג",
    titulo: "Gog uMagog",
    tituloFa: "جوج و ماجوج",
    tituloEn: "Gog and Magog",
    gancho: "Toda la profecía de la guerra final desemboca en cinco palabras: «YHVH será Uno y Su Nombre Uno» (Zejaryá 14:9). Los dos «Uno» suman 13+13 = 26 = YHVH. La guerra es el parto de la Unidad.",
    ganchoFa: "تمامِ نبوتِ جنگِ پایانی به پنج واژه می‌رسد: «خداوند یکی است و نامش یکی» (زخریا ۱۴:۹). دو «یک» جمعاً ۱۳+۱۳ = ۲۶ = یهوه. جنگ، زایمانِ یگانگی است.",
    ganchoEn: "The whole prophecy of the final war flows into five words: “YHVH will be One and His Name One” (Zechariah 14:9). The two “One”s add up to 13+13 = 26 = YHVH. The war is the birth-pangs of Oneness.",
    serie: "mashiaj",
    color: "#9a6a8e",
    orden: 0.6,
  },
  {
    slug: "zohar-redencion",
    he: "הַזֹּהַר וְהַגְּאוּלָּה",
    titulo: "El Zóhar y la Redención",
    tituloFa: "زوهر و رستگاری",
    tituloEn: "The Zohar and Redemption",
    gancho: "El Zóhar dice algo escandaloso: cuando Israel está en el exilio, Dios también lo está. La Shejiná baja con el pueblo, y la redención se teje a dos voces — el despertar de abajo y el de arriba.",
    ganchoFa: "زوهر چیزی شگفت می‌گوید: وقتی اسرائیل در تبعید است، خدا نیز هست. شخینا با قوم فرود می‌آید، و رستگاری به دو صدا بافته می‌شود — بیداری از پایین و از بالا.",
    ganchoEn: "The Zohar says something scandalous: when Israel is in exile, God is too. The Shechinah descends with the people, and redemption is woven in two voices — the awakening from below and the one from above.",
    serie: "mashiaj",
    color: "#7855bb",
    orden: 0.7,
  },
  {
    slug: "tikunei-zohar",
    numero: "913",
    he: "תִּקּוּנֵי הַזֹּהַר",
    titulo: "Tikunei HaZóhar y los Procesos Finales",
    tituloFa: "تیکونِی زوهر و فرایندهای پایانی",
    tituloEn: "Tikkunei HaZohar and the Final Processes",
    gancho: "Bereshit = 913. De esa sola palabra el Tikunei HaZóhar saca 70 explicaciones. El comienzo del mundo contenía, plegado, todo su final — y el mundo está hecho de letras divinas que el tikún reordena.",
    ganchoFa: "برئشیت = ۹۱۳. تیکونِی زوهر از همین یک واژه ۷۰ توضیح برمی‌آورد. آغازِ جهان، پایانِ آن را در خود تا کرده بود — و جهان از حروفِ الهی ساخته شده که تیکون آن‌ها را بازمی‌چیند.",
    ganchoEn: "Bereshit = 913. From that single word the Tikkunei HaZohar draws seventy explanations. The beginning of the world contained, folded within it, its entire end — and the world is made of divine letters that the tikkun rearranges.",
    serie: "mashiaj",
    color: "#b5557a",
    orden: 0.8,
  },
  {
    slug: "el-ari",
    numero: "45",
    he: "הָאֲרִ״י וּמִבְנֵה הַבְּרִיאָה",
    titulo: "El Arí y la Estructura Cósmica",
    tituloFa: "آری و ساختارِ آفرینش",
    tituloEn: "The Ari and the Cosmic Structure",
    gancho: "El sistema luriano completo —Tzimtzum, Shevirat HaKelim, Birur y Tikún—: la «física» de toda la serie. El mundo nació roto a propósito. Adam = Gueulá = Mah = 45: somos el instrumento del tikún.",
    ganchoFa: "نظامِ کاملِ لوریانی —تسیمتسوم، شکستِ ظرف‌ها، بیرور و تیکون—: «فیزیکِ» تمامِ سری. جهان عمداً شکسته زاده شد. آدام = گئولا = مَه = ۴۵: ما ابزارِ تیکونیم.",
    ganchoEn: "The complete Lurianic system —Tzimtzum, Shevirat HaKelim, Birur and Tikkun—: the “physics” of the whole series. The world was born broken on purpose. Adam = Geulah = Mah = 45: we are the instrument of the tikkun.",
    serie: "mashiaj",
    color: "#6cd4e0",
    orden: 0.9,
  },
  {
    slug: "shaar-hagilgulim",
    numero: "37",
    he: "שַׁעַר הַגִּלְגּוּלִים",
    titulo: "Shaar HaGilgulim y la Rectificación de las Almas",
    tituloFa: "شَعَر هَگیلگولیم و اصلاحِ جان‌ها",
    tituloEn: "Sha'ar HaGilgulim and the Rectification of Souls",
    gancho: "Yejidá = Hével = 37. El punto más alto de tu alma carga la memoria del primer hijo que murió. La reencarnación es el mecanismo del tikún personal: cada vez que te corriges, reparas algo del Edén.",
    ganchoFa: "یِحیدا = هِوِل = ۳۷. بلندترین نقطهٔ جانِ تو، یادِ نخستین فرزندی را که مُرد در خود دارد. تناسخ سازوکارِ تیکونِ شخصی است: هر بار که خود را اصلاح می‌کنی، چیزی از عدن را ترمیم می‌کنی.",
    ganchoEn: "Yechidah = Hevel = 37. The highest point of your soul carries the memory of the first son who died. Reincarnation is the mechanism of personal tikkun: every time you correct yourself, you repair something of Eden.",
    serie: "mashiaj",
    color: "#3fa68a",
    orden: 0.95,
  },
  {
    slug: "jasidut-redencion",
    numero: "26",
    he: "חֲסִידוּת וְהַגְּאוּלָּה הַפְּנִימִית",
    titulo: "Jasidut y la Redención Interior",
    tituloFa: "حَسیدوت و رستگاریِ درونی",
    tituloEn: "Chasidut and the Inner Redemption",
    gancho: "Ahavá (amor) = 13 y Ejad (uno) = 13. Súmalos: 26 = YHVH. Cuando dos amores se vuelven uno, aparece el Nombre. La Gueulá empieza dentro: la redención del mundo empieza en cómo amas hoy.",
    ganchoFa: "اَهاوا (عشق) = ۱۳ و اِچاد (یک) = ۱۳. جمع‌شان: ۲۶ = یهوه. وقتی دو عشق یکی می‌شوند، نام پدیدار می‌گردد. رستگاری از درون آغاز می‌شود: از این‌که امروز چگونه عشق می‌ورزی.",
    ganchoEn: "Ahavah (love) = 13 and Echad (one) = 13. Add them: 26 = YHVH. When two loves become one, the Name appears. Geulah begins within: the redemption of the world begins in how you love today.",
    serie: "mashiaj",
    color: "#5b8fd6",
    orden: 0.97,
  },
  {
    slug: "olam-haba",
    numero: "358",
    he: "עוֹלָם הַבָּא וְהַתַּכְלִית",
    titulo: "Olam HaBa y la Consumación Final",
    tituloFa: "عولام هَبا و غایتِ نهایی",
    tituloEn: "Olam HaBa and the Final Consummation",
    gancho: "El cierre del arco: la serie empezó con un enigma —«¿qué es el Mashíaj?»— y termina con cinco palabras: «YHVH Uno, Su Nombre Uno». Mashíaj = Najash = 358: el Mashíaj nunca fue una persona que llega; es el mundo volviéndose Uno.",
    ganchoFa: "بستنِ کمان: سری با معمایی آغاز شد —«ماشیح چیست؟»— و با پنج واژه پایان می‌یابد: «خداوند یکی، نامش یکی». ماشیح = ناحاش = ۳۵۸: ماشیح هرگز شخصی نبود که می‌آید؛ جهان است که یکی می‌شود.",
    ganchoEn: "The closing of the arc: the series began with an enigma —“what is Mashiach?”— and ends with five words: “YHVH One, His Name One.” Mashiach = Nachash = 358: Mashiach was never a person who arrives; it is the world becoming One.",
    serie: "mashiaj",
    color: "#b06a3c",
    orden: 0.99,
  },

  // ── SERIE "CIENCIA" — Cabalá y física (libro «137: The Riddle of Creation») ──
  {
    slug: "cuatro-fuerzas",
    numero: "4→1",
    he: "יהוה · ד׳ כֹּחוֹת",
    titulo: "Las cuatro fuerzas y el Nombre de Dios",
    tituloFa: "چهار نیرو و نامِ خدا",
    tituloEn: "The Four Forces and the Name of God",
    gancho:
      "La física tardó un siglo en hallar que solo cuatro fuerzas gobiernan todo el universo: gravedad, electromagnetismo y las fuerzas nucleares fuerte y débil. La Cabalá ya lo decía: son las cuatro letras del Nombre יהוה y los cuatro Mundos. Y antes del Big Bang, las cuatro eran Una.",
    ganchoFa:
      "فیزیک یک قرن زمان برد تا دریابد تنها چهار نیرو بر تمامِ جهان حکم می‌رانند: گرانش، الکترومغناطیس و دو نیرویِ هسته‌ایِ قوی و ضعیف. کابالا از پیش گفته بود: این‌ها چهار حرفِ نامِ یهوه و چهار جهان‌اند. و پیش از مِهبانگ، هر چهار یکی بودند.",
    ganchoEn:
      "It took physics a century to find that just four forces govern the whole universe: gravity, electromagnetism, and the strong and weak nuclear forces. Kabbalah had already said it: they are the four letters of the Name יהוה and the four Worlds. And before the Big Bang, all four were One.",
    serie: "ciencia",
    color: "#48b8f0",
    orden: 14,
  },
  {
    slug: "abrazo-cosmico",
    numero: "496",
    he: "מַלְכוּת",
    titulo: "El abrazo cósmico",
    tituloFa: "آغوشِ کیهانی",
    tituloEn: "The Cosmic Embrace",
    gancho:
      "El universo entero se separa: cada galaxia huye de las demás, y cada vez más rápido. Y sin embargo no se deshace. Una fuerza invisible —que la ciencia aún no logra explicar, el 95 % oscuro del cosmos— lo abraza desde afuera. La Cabalá la llamó Maljut. Su número, 496, es exactamente la dimensión que la teoría de cuerdas necesita para que el universo sea posible.",
    ganchoFa:
      "تمامِ جهان از هم می‌گسلد: هر کهکشان از دیگران می‌گریزد، و هر دم تندتر. و با این همه از هم نمی‌پاشد. نیرویی نادیدنی —که علم هنوز نمی‌تواند توضیحش دهد، ۹۵٪ تاریکِ کیهان— آن را از بیرون در آغوش می‌گیرد. کابالا آن را مَلخوت نامید. عددش، ۴۹۶، دقیقاً همان بُعدی است که نظریهٔ ریسمان برای ممکن‌شدنِ جهان نیاز دارد.",
    ganchoEn:
      "The whole universe is flying apart: every galaxy fleeing the others, faster and faster. And yet it does not come undone. An invisible force —which science still cannot explain, the dark 95 % of the cosmos— embraces it from the outside. Kabbalah called it Malchut. Its number, 496, is exactly the dimension string theory needs for a universe to be possible.",
    serie: "ciencia",
    color: "#6d7bf0",
    orden: 15,
  },
  {
    slug: "137-y-la-edad",
    numero: "137",
    he: "מַה־טּוֹב לָאָדָם",
    titulo: "137 — el número entre la vida y la muerte",
    tituloFa: "۱۳۷ — عددِ میانِ زندگی و مرگ",
    tituloEn: "137 — The Number Between Life and Death",
    gancho:
      "El mismo 137 que gobierna la luz mide la vida humana: Ismael, Leví y Amram vivieron exactamente 137 años, y Abraham tenía 137 cuando murió Sará. Y en física, 137 decide cuánto vive una partícula —y si el gato de Schrödinger está vivo o muerto. El número del umbral entre el ser y el no-ser.",
    ganchoFa:
      "همان ۱۳۷ که بر نور حکم می‌راند، زندگیِ انسان را اندازه می‌گیرد: اسماعیل، لاوی و عَمرام دقیقاً ۱۳۷ سال زیستند، و ابراهیم هنگامِ مرگِ سارا ۱۳۷ ساله بود. و در فیزیک، ۱۳۷ تعیین می‌کند یک ذرّه چقدر زنده می‌مانَد — و آیا گربهٔ شرودینگر زنده است یا مرده. عددِ آستانهٔ میانِ بودن و نبودن.",
    ganchoEn:
      "The same 137 that governs light measures human life: Ishmael, Levi and Amram each lived exactly 137 years, and Abraham was 137 when Sarah died. And in physics, 137 decides how long a particle lives —and whether Schrödinger's cat is alive or dead. The number of the threshold between being and non-being.",
    serie: "ciencia",
    color: "#34c5d6",
    orden: 15.5,
  },
  {
    slug: "casamentero",
    numero: "137",
    he: "מוֹצֵא אִשָּׁה",
    titulo: "137 — El Casamentero Divino",
    tituloFa: "۱۳۷ — واسطهٔ آسمانی",
    tituloEn: "137 — The Divine Matchmaker",
    gancho:
      "En física, 137 es la constante que acopla la luz con la materia: enlaza el fotón sin masa con el electrón, la energía con la sustancia. En hebreo, «el que halla» (מוֹצֵא) esposa vale 137 —igual que «Cabalá»— y los sabios enseñan que cada pareja se decide en el Cielo. El número del matrimonio cósmico: donde la energía se vuelve materia y dos almas se reencuentran.",
    ganchoFa:
      "در فیزیک، ۱۳۷ ثابتی است که نور را به ماده می‌پیوندد: فوتونِ بی‌جرم را به الکترون جفت می‌کند، انرژی را به مادّه. در عبری، «آن‌که می‌یابد» (מוֹצֵא) همسری برابرِ ۱۳۷ است — درست مانندِ «کابالا» — و حکیمان می‌آموزند که هر جفت در آسمان تعیین می‌شود. عددِ ازدواجِ کیهانی: جایی که انرژی مادّه می‌شود و دو جان بازیکدیگر را می‌یابند.",
    ganchoEn:
      "In physics, 137 is the constant that couples light to matter: it binds the massless photon to the electron, energy to substance. In Hebrew, “the one who finds” (מוֹצֵא) a wife equals 137 — just like “Kabbalah” — and the sages teach that every match is made in Heaven. The number of the cosmic marriage: where energy becomes matter and two souls find each other again.",
    serie: "ciencia",
    color: "#c77dd0",
    orden: 15.7,
  },
  {
    slug: "complementariedad",
    numero: "2",
    he: "בֵּית",
    titulo: "Complementariedad — la luz que no se deja ver entera",
    tituloFa: "مکملیت — نوری که یکجا دیده نمی‌شود",
    tituloEn: "Complementarity — The Light You Cannot See Whole",
    gancho:
      "La física descubrió que la luz es onda y partícula a la vez, pero jamás en la misma mirada; y que es imposible conocerlo todo de una sola vez (Heisenberg). La Cabalá lo dijo antes: la Torá no empieza en el Uno (א = 1) sino en el Dos (ב = 2), y su primera letra está sellada por tres lados. El principio de incertidumbre, escrito en la primera letra de la creación.",
    ganchoFa:
      "فیزیک دریافت که نور هم موج است و هم ذرّه، اما هرگز در یک نگاه؛ و ناممکن است همه‌چیز را یکجا دانست (هایزنبرگ). کابالا پیش‌تر گفته بود: تورات نه از یک (א = ۱) بلکه از دو (ב = ۲) آغاز می‌شود، و نخستین حرفش از سه سو بسته است. اصلِ عدمِ قطعیت، نوشته بر نخستین حرفِ آفرینش.",
    ganchoEn:
      "Physics discovered that light is both wave and particle, yet never in the same glance; and that it is impossible to know everything at once (Heisenberg). Kabbalah said it first: the Torah does not begin with the One (א = 1) but with the Two (ב = 2), and its first letter is sealed on three sides. The uncertainty principle, written into the first letter of creation.",
    serie: "ciencia",
    color: "#4fb0c6",
    orden: 15.8,
  },
  {
    slug: "simetria-cpt",
    numero: "137",
    he: "עוֹלָם · שָׁנָה · נֶפֶשׁ",
    titulo: "Simetría CPT — cuando el tiempo corre hacia atrás",
    tituloFa: "تقارنِ CPT — آنگاه که زمان به عقب می‌رود",
    tituloEn: "CPT Symmetry — When Time Runs Backwards",
    gancho:
      "La física halló una ley que el universo jamás rompe: invierte a la vez la carga, el espacio y el tiempo (CPT) y todo queda idéntico. La Cabalá ya lo había escrito —mundo, año y alma son las tres dimensiones de la creación (Séfer Yetzirá)— y en las letras de sus tres meses esconde el número 137. Y la teshuvá resulta ser la simetría del tiempo: volver atrás y reescribir el pasado.",
    ganchoFa:
      "فیزیک قانونی یافت که جهان هرگز آن را نمی‌شکند: بار، فضا و زمان را همزمان وارونه کن (CPT) و همه‌چیز یکسان می‌مانَد. کابالا از پیش نوشته بود —جهان، سال و جان سه بُعدِ آفرینش‌اند (سِفِر یِتسیرا)— و در حروفِ سه ماهِ خود عددِ ۱۳۷ را پنهان کرده است. و تشووا همان تقارنِ زمان است: بازگشت به گذشته و بازنویسیِ آن.",
    ganchoEn:
      "Physics found a law the universe never breaks: reverse charge, space and time all at once (CPT) and everything stays identical. Kabbalah had already written it —world, year and soul are the three dimensions of creation (Sefer Yetzirah)— and in the letters of its three months it hides the number 137. And teshuvah turns out to be the symmetry of time: going back to rewrite the past.",
    serie: "ciencia",
    color: "#5ad1a0",
    orden: 15.9,
  },
  {
    slug: "musica-de-la-creacion",
    numero: "137/60",
    he: "שִׁיר חָדָשׁ",
    titulo: "La música de la creación",
    tituloFa: "موسیقیِ آفرینش",
    tituloEn: "The Music of Creation",
    gancho:
      "Pulsa una sola cuerda y no suena un tono, sino muchos a la vez: mitades, tercios, cuartos, quintos —una escalera oculta de armónicos. Suma los cinco primeros y da exactamente 137/60: Cabalá (137) sobre halajá (60). Y la física lo reencontró: en la teoría de cuerdas, todo el universo está hecho de cuerdas que vibran. El cosmos es música.",
    ganchoFa:
      "یک تار را بنواز و یک نوا نمی‌شنوی، بلکه بسیاری با هم: نیم‌ها، ثلث‌ها، ربع‌ها، خمس‌ها — نردبانی پنهان از هماهنگ‌ها. پنج تای نخست را جمع کن، دقیقاً ۱۳۷/۶۰ می‌شود: کابالا (۱۳۷) بر هلاخا (۶۰). و فیزیک همان را بازیافت: در نظریهٔ ریسمان، تمامِ جهان از ریسمان‌هایی ساخته شده که می‌لرزند. کیهان، موسیقی است.",
    ganchoEn:
      "Pluck a single string and you don't hear one tone but many at once: halves, thirds, quarters, fifths —a hidden ladder of overtones. Add the first five and you get exactly 137/60: Kabbalah (137) over halachah (60). And physics rediscovered it: in string theory, the whole universe is made of vibrating strings. The cosmos is music.",
    serie: "ciencia",
    color: "#e8b84a",
    orden: 15.95,
  },
  {
    slug: "observador",
    numero: "48+89",
    he: "מֹחַ · גּוּף",
    titulo: "El observador — la conciencia que enciende la realidad",
    tituloFa: "ناظر — آگاهی‌ای که واقعیت را روشن می‌کند",
    tituloEn: "The Observer — The Consciousness That Lights Up Reality",
    gancho:
      "La física cuántica descubrió algo perturbador: una partícula existe en todos sus estados a la vez —hasta que alguien la observa. El observador consciente fija la realidad. La Cabalá lo dijo antes: nada existe sin conciencia. Y en hebreo, mente (מֹחַ, 48) + cuerpo (גּוּף, 89) = 137 = Cabalá: el mismo número que gobierna la luz une la mente con la materia.",
    ganchoFa:
      "فیزیکِ کوانتومی چیزی نگران‌کننده یافت: یک ذرّه هم‌زمان در همهٔ حالاتش هست — تا آنکه کسی آن را ببیند. ناظرِ آگاه واقعیت را قطعی می‌کند. کابالا پیش‌تر گفته بود: هیچ‌چیز بی‌آگاهی وجود ندارد. و در عبری، ذهن (מֹחַ، ۴۸) + تن (גּוּף، ۸۹) = ۱۳۷ = کابالا: همان عددی که بر نور حکم می‌راند، ذهن را به مادّه می‌پیوندد.",
    ganchoEn:
      "Quantum physics found something unsettling: a particle exists in all its states at once —until someone observes it. The conscious observer fixes reality. Kabbalah said it first: nothing exists without consciousness. And in Hebrew, mind (מֹחַ, 48) + body (גּוּף, 89) = 137 = Kabbalah: the same number that governs light unites mind with matter.",
    serie: "ciencia",
    color: "#8a7bf0",
    orden: 15.85,
  },
  {
    slug: "411",
    numero: "411",
    he: "תֹהוּ = יֵשׁ מֵאַיִן",
    titulo: "411 — El cero y el uno de la creación",
    tituloFa: "۴۱۱ — صفر و یکِ آفرینش",
    tituloEn: "411 — The Zero and the One of Creation",
    gancho:
      "Toda la realidad se reduce a dos estados: 0 y 1, apagado y encendido, la nada y el ser. Cuando Leibniz inventó el sistema binario lo llamó «imagen de la creación»: el 1 es el ser, el 0 es la nada. La Cabalá lo dijo antes: crear es yesh me'ayin —sacar algo (1) de la nada (0)—. Y el vacío primordial de la Torá, tohu (Génesis 1:2), vale 411 = 3 × 137: el número de la luz, tres veces, escrito en el cero y el uno de la creación.",
    ganchoFa:
      "تمامِ واقعیت به دو حالت فرومی‌کاهد: ۰ و ۱، خاموش و روشن، نیستی و هستی. لایبنیتس چون نظامِ دوتایی را ابداع کرد، آن را «تصویرِ آفرینش» نامید: ۱ هستی است، ۰ نیستی. کابالا پیش‌تر گفته بود: آفریدن یعنی یِش مِآیین — برآوردنِ چیزی (۱) از هیچ (۰). و تُهوی نخستین، تهیِ آغازینِ تورات (پیدایش ۱:۲)، برابرِ ۴۱۱ = ۳ × ۱۳۷ است: عددِ نور، سه بار، نوشته در صفر و یکِ آفرینش.",
    ganchoEn:
      "All of reality reduces to two states: 0 and 1, off and on, nothing and being. When Leibniz invented the binary system he called it an “image of creation”: 1 is being, 0 is nothing. Kabbalah said it first: to create is yesh me'ayin —drawing something (1) out of nothing (0). And the primordial void of the Torah, tohu (Genesis 1:2), equals 411 = 3 × 137: the number of light, three times, written into the zero and the one of creation.",
    serie: "ciencia",
    color: "#3fd0b0",
    orden: 15.97,
  },
  {
    slug: "salmo-15",
    numero: "11",
    he: "מִי יָגוּר בְּאָהֳלֶךָ",
    titulo: "Las once puertas del Salmo 15",
    tituloFa: "یازده دروازهٔ مزمور ۱۵",
    tituloEn: "The Eleven Gates of Psalm 15",
    gancho:
      "El rey David preguntó: «¿Quién podrá habitar en Tu tienda?» y respondió con once condiciones. Ahora cuenta las letras: la pregunta tiene 37, las once condiciones exactamente 137 —el número de la Cabalá y de la luz— y el sello final 17. Y esos tres números son las edades de Abraham, Itzjak y Yaakov en sus pruebas más duras. Un salmo que se mide letra por letra.",
    ganchoFa:
      "داوودِ پادشاه پرسید: «چه کسی می‌تواند در خیمهٔ تو ساکن شود؟» و با یازده شرط پاسخ داد. حال حروف را بشمار: پرسش ۳۷ حرف دارد، یازده شرط دقیقاً ۱۳۷ — عددِ کابالا و عددِ نور — و مُهرِ پایانی ۱۷. و این سه عدد، سنِ ابراهیم، اسحاق و یعقوب در سخت‌ترین آزمون‌هایشان است. مزموری که حرف‌به‌حرف اندازه‌گیری می‌شود.",
    ganchoEn:
      "King David asked: “Who may dwell in Your tent?” and answered with eleven conditions. Now count the letters: the question has 37, the eleven conditions exactly 137 —the number of Kabbalah and of light— and the closing seal 17. And those three numbers are the ages of Abraham, Isaac and Jacob at their hardest trials. A psalm measured letter by letter.",
    serie: "ciencia",
    color: "#d96f8f",
    orden: 15.98,
  },
  {
    slug: "numero-femenino",
    numero: "137",
    he: "אַיֵּה · הִיא",
    titulo: "137 — el número femenino",
    tituloFa: "۱۳۷ — عددِ مؤنث",
    tituloEn: "137 — The Feminine Number",
    gancho:
      "La primera frase de la Torá esconde una pregunta. Las letras א, ה e י aparecen allí por primera vez en el orden א-י-ה: «¿dónde?». Y esas mismas tres letras, escritas con su nombre completo, suman 137. Cuando Dios crea la luz vuelven a aparecer juntas —al revés— y se leen הִיא: «Ella». En física, 137 es la constante que acopla la luz con la materia: lo que da y lo que recibe. Y recibir, en hebreo, se llama Cabalá.",
    ganchoFa:
      "نخستین جملهٔ تورات پرسشی را پنهان کرده است. حروفِ א، ה و י نخستین بار در آنجا به ترتیبِ א-י-ה پدیدار می‌شوند: «کجا؟». و همین سه حرف، چون با نامِ کاملشان نوشته شوند، ۱۳۷ می‌شوند. آنگاه که خدا نور را می‌آفریند، باز کنارِ هم می‌آیند — وارونه — و הִיא خوانده می‌شوند: «او (زن)». در فیزیک، ۱۳۷ همان ثابتی است که نور را به مادّه می‌پیوندد: آنچه می‌بخشد و آنچه می‌پذیرد. و پذیرفتن، در عبری، کابالا نام دارد.",
    ganchoEn:
      "The Torah's first sentence hides a question. The letters א, ה and י first appear there in the order א-י-ה: “where?” And those same three letters, written out by their full names, add up to 137. When God creates light they appear together again —reversed— and read הִיא: “She.” In physics, 137 is the constant that couples light to matter: the giver and the receiver. And to receive, in Hebrew, is called Kabbalah.",
    serie: "ciencia",
    color: "#cf6fa8",
    orden: 15.99,
  },
  {
    slug: "numero-pi",
    numero: "π",
    he: "יוֹם · שָׁנָה",
    titulo: "π — el número escondido entre el día y el año",
    tituloFa: "π — عددی پنهان میانِ روز و سال",
    tituloEn: "π — The Number Hidden Between the Day and the Year",
    gancho:
      "«Año» (שָׁנָה) vale 355. «Un día» escrito en su plenitud vale 113. Divide uno entre el otro: 355/113 = 3,141592… — el número π, exacto hasta el sexto decimal. Es la mejor fracción de π con números menores que mil, y a Occidente le tomó hasta el siglo XVI encontrarla. En la Torá, el año es el círculo que gira y el día es la línea que no cambia. π es la razón entre los dos: entre el tiempo que pasa y el tiempo que permanece.",
    ganchoFa:
      "«سال» (שָׁנָה) برابرِ ۳۵۵ است. «یک روز»، چون در پُری‌اش نوشته شود، برابرِ ۱۱۳. یکی را بر دیگری تقسیم کن: ۳۵۵/۱۱۳ = ۳٫۱۴۱۵۹۲… — همان عددِ π، درست تا ششمین رقمِ اعشار. این بهترین کسرِ π با عددهای کمتر از هزار است، و غرب تا سدهٔ شانزدهم آن را نیافت. در تورات، سال دایره‌ای است که می‌گردد و روز خطی که دگرگون نمی‌شود. π نسبتِ میانِ این دو است: میانِ زمانی که می‌گذرد و زمانی که می‌مانَد.",
    ganchoEn:
      "“Year” (שָׁנָה) equals 355. “One day,” written out in full, equals 113. Divide one by the other: 355/113 = 3.141592… — the number π, exact to six decimal places. It is the best fraction for π using numbers under a thousand, and the West did not find it until the 16th century. In the Torah the year is the circle that turns and the day is the line that does not change. π is the ratio between the two: between the time that passes and the time that remains.",
    serie: "ciencia",
    color: "#f0913f",
    orden: 16,
  },

  // ── SERIE "PARASHA" — Estudios completos de parashá con PaRDeS ───────────────
  // Cada entrada de parashá es el ÍNDICE de enseñanzas en /misterio/{slug}.
  // Las sub-enseñanzas viven en /misterio/{slug}/{enseñanza}/page.tsx.
  {
    slug: "parashat-korach",
    numero: "308",
    he: "פָּרָשַׁת קֹרַח",
    titulo: "Parashat Korach",
    tituloFa: "پاراشات قورَح",
    tituloEn: "Parashat Korach",
    gancho: "Korach tenía razón en el diagnóstico. Se equivocó en la prescripción.",
    ganchoFa: "قورَح در تشخیص درست بود. در نسخه اشتباه کرد.",
    ganchoEn: "Korach was right about the diagnosis. He was wrong about the prescription.",
    serie: "parasha",
    color: "#8b3a3a",
    orden: 16,
  },
  {
    slug: "vaiejal-moshe",
    he: "וַיְחַל מֹשֶׁה",
    titulo: "El juramento que Dios necesitaba que alguien anulara",
    tituloFa: "سوگندی که خدا نیاز داشت کسی باطلش کند",
    tituloEn: "The Oath God Needed Someone to Annul",
    gancho: "Dios jura destruir a Israel. Una palabra rara en el texto —vaiéjal— dice que Moisés hizo algo mucho más audaz que rogar: anuló el juramento de Dios. Y el Talmud dice que Dios se lo permitió a propósito.",
    ganchoFa: "خدا سوگند می‌خورد اسرائیل را نابود کند. واژه‌ای کمیاب در متن — وَیِّخَل — می‌گوید موسی کاری بسی جسورانه‌تر از التماس کرد: سوگندِ خدا را باطل کرد. و تلمود می‌گوید خدا عمداً چنین اجازه‌ای به او داد.",
    ganchoEn: "God swears to destroy Israel. A rare word in the text —vayechal— says Moses did something far bolder than pleading: he annulled God's oath. And the Talmud says God allowed it on purpose.",
    serie: "parasha",
    color: "#8b6a3a",
    orden: 16.5,
  },
  {
    slug: "likutei-moharan-i-1",
    he: "אַשְׁרֵי תְמִימֵי דָרֶךְ",
    titulo: "El jen que hace que tu oración sea escuchada",
    tituloFa: "حنی که دعایت را می‌شنواند",
    tituloEn: "The Grace That Makes Your Prayer Heard",
    gancho: "La luna no tiene luz propia. Tú tampoco — todavía. Rebbe Najman revela el secreto del jen.",
    ganchoFa: "ماه نور ذاتی ندارد. تو هم — هنوز. ربه نجمن راز חֵן را آشکار می‌کند.",
    ganchoEn: "The moon has no light of its own. Neither do you — yet. Rebbe Nachman reveals the secret of chen.",
    serie: "shabat",
    color: "#e8945a",
    orden: 17,
  },
  {
    slug: "likutei-moharan-i-2",
    he: "וּתְהִלָּתִי אֶחֱטָם לָךְ",
    titulo: "El arma secreta del Mashíaj",
    tituloFa: "سلاحِ پنهانِ ماشیَح",
    tituloEn: "The Secret Weapon of Mashiach",
    gancho: "No es la espada, es el aliento: por qué la oración es el arma más poderosa que existe.",
    ganchoFa: "نه شمشیر، بلکه نَفَس — چرا دعا قدرتمندترین سلاحی است که وجود دارد.",
    ganchoEn: "Not the sword, but the breath — why prayer is the most powerful weapon there is.",
    serie: "shabat",
    color: "#e8945a",
    orden: 17.5,
  },
  {
    slug: "likutei-moharan-i-3",
    he: "קוֹל הַנְּגִינָה",
    titulo: "La voz del canto: por qué una melodía te salva o te enreda",
    tituloFa: "آوازِ نغمه: چرا یک ملودی نجاتت می‌دهد یا به دام می‌اندازد",
    tituloEn: "The Voice of Song: Why a Melody Can Save You or Ensnare You",
    gancho: "No hay música inocente: cada melodía que oyes mama de una fuente — y te ata a ella.",
    ganchoFa: "هیچ موسیقیِ بی‌گناهی نیست: هر نغمه‌ای که می‌شنوی از سرچشمه‌ای شیر می‌خورد — و تو را به آن می‌بندد.",
    ganchoEn: "No song is innocent: every melody you hear nurses from a source — and binds you to it.",
    serie: "shabat",
    color: "#e8945a",
    orden: 18,
  },
  {
    slug: "likutei-moharan-i-4",
    he: "אָנֹכִי ה' אֱלֹהֶיךָ",
    titulo: "Todo lo que te sucede es para tu bien",
    tituloFa: "هر آنچه بر تو می‌گذرد، به سودِ توست",
    tituloEn: "Everything That Happens to You Is for Your Good",
    gancho: "Saber que todo lo que te pasa es para tu bien: un anticipo del Paraíso.",
    ganchoFa: "بدانی هر چه پیش می‌آید به سودِ توست — چشیدنِ طعمِ عالَمِ آینده.",
    ganchoEn: "To know that all that befalls you is for your good — a foretaste of the World to Come.",
    serie: "shabat",
    color: "#e8945a",
    orden: 18.5,
  },
  {
    slug: "likutei-moharan-i-5",
    he: "בַּחֲצֹצְרוֹת וְקוֹל שׁוֹפָר",
    titulo: "La voz que se vuelve trueno y quiebra el decreto",
    tituloFa: "صدایی که رعد می‌شود و حکم را درهم می‌شکند",
    tituloEn: "The Voice That Becomes Thunder and Breaks the Decree",
    gancho: "Tu plegaria, dicha con fuerza pura, se vuelve trueno que endereza el corazón.",
    ganchoFa: "دعایی که با نیرویی پاک گفته شود، رعدی می‌شود که قلب را راست می‌کند.",
    ganchoEn: "Prayer spoken with pure force becomes thunder that straightens the heart.",
    serie: "shabat",
    color: "#e8945a",
    orden: 19,
  },
  {
    slug: "likutei-moharan-i-6",
    he: "דּוֹם לַה׳",
    titulo: "La corona del que calla",
    tituloFa: "تاجِ آن‌که خاموش می‌مانَد",
    tituloEn: "The Crown of the One Who Keeps Silent",
    gancho: "Te insultan. No respondes. En ese silencio nace una letra que te corona.",
    ganchoFa: "به تو توهین می‌کنند و پاسخ نمی‌دهی؛ در آن سکوت حرفی زاده می‌شود که تاجِ توست.",
    ganchoEn: "They insult you. You don't answer. In that silence a letter is born that crowns you.",
    serie: "shabat",
    color: "#e8945a",
    orden: 19.5,
  },
  {
    slug: "eikev-talon",
    he: "עֵקֶב",
    titulo: "El talón: lo que pisamos sin mirar",
    tituloFa: "پاشنه: آنچه بی‌آنکه بنگریم لگد می‌کنیم",
    tituloEn: "The Heel: What We Trample Without Looking",
    gancho: "El Ramban: la cabeza es el comienzo, el talón es el final. Rashi: las mitzvot livianas son las que pisamos con el talón. Justo donde muerde la serpiente.",
    ganchoFa: "رامبان: سر آغاز است و پاشنه پایان. راشی: میتزوت‌های سبک همان‌هایند که با پاشنه لگد می‌کنیم. دقیقاً همان‌جا که مار می‌گزد.",
    ganchoEn: "Ramban: the head is the beginning, the heel is the end. Rashi: the light mitzvot are the ones we trample with our heels. Exactly where the serpent bites.",
    serie: "parasha",
    color: "#8b6a3a",
    orden: 16.7,
  },
  {
    // Re'eh sigue a Eikev en el orden de lectura de Devarim.
    // tituloFa/ganchoFa replican el español a propósito: el estudio está solo
    // en español y el Sofer aún no lo tradujo. NO se generó farsi automático.
    slug: "reeh-ojo-doble",
    he: "רְאֵה",
    titulo: "El ojo que ve doble",
    tituloFa: "El ojo que ve doble",
    tituloEn: "The Eye That Sees Double",
    gancho: "La parashá se llama «Mira». Prohíbe una manera de ver —«cada uno lo recto a sus propios ojos»— y la reemplaza por otra: «lo recto a los ojos de HaShem». Misma palabra; lo único que cambia es de quién son los ojos.",
    ganchoFa: "La parashá se llama «Mira». Prohíbe una manera de ver —«cada uno lo recto a sus propios ojos»— y la reemplaza por otra: «lo recto a los ojos de HaShem». Misma palabra; lo único que cambia es de quién son los ojos.",
    ganchoEn: "The parashah is called “Look.” It forbids one way of seeing —“each man what is right in his own eyes”— and replaces it with another: “what is right in the eyes of HaShem.” Same word; all that changes is whose eyes they are.",
    serie: "parasha",
    color: "#8b6a3a",
    orden: 16.8,
  },
  {
    // Ki Tetzé sigue a Re'eh y Shoftim en el orden de lectura de Devarim.
    // tituloFa/ganchoFa replican el español a propósito: el estudio está solo
    // en español y el Sofer aún no lo tradujo. NO se generó farsi automático.
    slug: "buey-y-burro",
    he: "נָחָשׁ",
    titulo: "El buey y el burro dentro de la serpiente",
    tituloFa: "El buey y el burro dentro de la serpiente",
    tituloEn: "The Ox and the Donkey Inside the Serpent",
    gancho:
      "Dentro de la palabra hebrea para serpiente hay dos animales escondidos — y la Torá manda que nunca se junten: «no ararás con buey y burro juntos». El Megalé Amukot (al Vaetjanán, Ofán 71) revela dónde viven: clavados en las letras mismas de נחש.",
    ganchoFa:
      "Dentro de la palabra hebrea para serpiente hay dos animales escondidos — y la Torá manda que nunca se junten: «no ararás con buey y burro juntos». El Megalé Amukot (al Vaetjanán, Ofán 71) revela dónde viven: clavados en las letras mismas de נחש.",
    ganchoEn:
      "Inside the Hebrew word for serpent two animals are hidden — and the Torah commands that they never be joined: “you shall not plow with an ox and a donkey together.” The Megaleh Amukot (on Va'etchanan, Ofan 71) reveals where they live: fixed in the very letters of נחש.",
    serie: "parasha",
    color: "#8b6a3a",
    orden: 16.9,
  },
  {
    // Ki Tavó sigue a Ki Tetzé en el orden de lectura de Devarim.
    // tituloFa/ganchoFa replican el español a propósito: el estudio está solo
    // en español y el Sofer aún no lo tradujo. NO se generó farsi automático.
    slug: "bendicion-invertida",
    he: "שִׂמְחָה",
    titulo: "La bendición que se invierte",
    tituloFa: "La bendición que se invierte",
    tituloEn: "The Blessing That Inverts",
    gancho:
      "Las 98 maldiciones de la Tojajá no caen sobre quien dejó de servir: caen sobre quien siguió sirviendo — sin alegría. Y el versículo dice dónde nacen: «por la abundancia de todo» (Devarim 28:47). La misma abundancia, invertida por la vasija que la recibe.",
    ganchoFa:
      "Las 98 maldiciones de la Tojajá no caen sobre quien dejó de servir: caen sobre quien siguió sirviendo — sin alegría. Y el versículo dice dónde nacen: «por la abundancia de todo» (Devarim 28:47). La misma abundancia, invertida por la vasija que la recibe.",
    ganchoEn:
      "The 98 curses of the Tochachah do not fall on the one who stopped serving: they fall on the one who kept serving — without joy. And the verse says where they are born: “out of the abundance of everything” (Devarim 28:47). The same abundance, inverted by the vessel that receives it.",
    serie: "parasha",
    color: "#8b6a3a",
    orden: 16.95,
  },
  // ── HUB de la serie "SHABAT" — índice de enseñanzas de Likutei Moharan ───────
  // La página /misterio/shabat es el índice; las enseñanzas viven en
  // /misterio/{slug} (p. ej. likutei-moharan-i-1) con serie "shabat".
  {
    slug: "shabat",
    he: "שַׁבָּת",
    titulo: "Shabbat — Enseñanzas de Likutei Moharan",
    tituloFa: "شبات — آموزش‌های لیکوتی موهاران",
    tituloEn: "Shabbat — Teachings of Likutei Moharan",
    gancho: "Cada viernes, una enseñanza del Rebbe Najman destilada para la entrada del Shabbat.",
    ganchoFa: "هر جمعه، یکی از آموزش‌های ربه نجمن برای ورودِ شبات.",
    ganchoEn: "Every Friday, one teaching of Rebbe Nachman distilled for the entrance of Shabbat.",
    serie: "shabat",
    color: "#e8945a",
    orden: 18,
  },
];

export function getMisterio(slug: string): Misterio | undefined {
  return MISTERIOS.find((m) => m.slug === slug);
}

export const MISTERIOS_ORDENADOS = [...MISTERIOS].sort((a, b) => a.orden - b.orden);
