// Catálogo de los Misterios — estudios publicados de Jashmal.
// Cada misterio es una landing en /misterio/{slug}. Para añadir uno nuevo,
// agrega una entrada aquí y crea su página.

export interface Misterio {
  slug: string;          // ruta: /misterio/{slug} y atajo /{slug}
  numero?: string;       // número/gematría destacado (ej. "358")
  he: string;            // término hebreo central
  titulo: string;        // título en español (canónico)
  tituloFa: string;
  tituloEn?: string;     // inglés — lo llena el Sofer por fases ([[i18n-audit]])
  gancho: string;        // una línea de gancho (español)
  ganchoFa: string;
  ganchoEn?: string;     // inglés — lo llena el Sofer por fases
  serie?: string;        // nombre de la serie (para agrupar)
  color: string;
  orden: number;         // orden de aparición (menor = primero)
}

export const MISTERIOS: Misterio[] = [
  {
    slug: "nudo-de-la-fe",
    numero: "91",
    he: "קִשְׁרָא דִּמְהֵימְנוּתָא",
    titulo: "El Nudo de la Fe",
    tituloFa: "گِرِهِ ایمان",
    gancho: "Dios no le mostró a Moshé su rostro — le mostró un nudo. El «nudo de la fe» del Zohar ata lo que no se ve con lo que sí: y cada mañana, al anudarte los tefilín, lo vuelves a atar.",
    ganchoFa: "خدا چهره‌اش را به موسی نشان نداد — یک گره نشانش داد. «گِرِهِ ایمان» در زوهر، ناپیدا را به پیدا می‌بندد؛ و هر بامداد که تِفیلین می‌بندی، آن را از نو گره می‌زنی.",
    serie: "fe",
    color: "#6f8fe8",
    orden: 0.5,
  },
  {
    slug: "emunah",
    numero: "102",
    he: "אֱמוּנָה",
    titulo: "La Fe — el fundamento de todo",
    tituloFa: "ایمان — ستونی که همه‌چیز بر آن ایستاده است",
    gancho: "613 mandamientos, y Habakuk los redujo todos a uno: «el justo por su fe vivirá». Pero la fe no es una corazonada — es firmeza, la piedra de abajo sobre la que todo se sostiene.",
    ganchoFa: "ششصد و سیزده فرمان، و حَبَقوق همه را بر یک پایه نهاد: «عادل به ایمانش زنده است». اما ایمان گمان نیست — استواری است، آن سنگِ زیرین که همه‌چیز بر آن می‌ایستد.",
    serie: "fe",
    color: "#6f8fe8",
    orden: 0.6,
  },
  {
    slug: "en-que-consiste",
    he: "אֱמוּנָה וּבִטָּחוֹן",
    titulo: "En qué consiste la fe — de la creencia a la confianza",
    tituloFa: "ایمان از چه ساخته شده؟ — از باور تا توکّل",
    gancho: "Creer es saber que Dios es firme; confiar es dejarse caer en esa firmeza. La fe consiste en tres columnas: el bitajón, la providencia en cada hoja y la fuerza de sostener cuando el Rostro se oculta.",
    ganchoFa: "باور می‌گوید «او پابرجاست»؛ توکّل می‌افزاید «پس بر او می‌افتم». ایمان از سه ستون ساخته شده: توکّل، مشیّتِ جزئی، و ایستادن آنجا که چهره پنهان است.",
    serie: "fe",
    color: "#6f8fe8",
    orden: 0.7,
  },
  {
    slug: "358",
    numero: "358",
    he: "מָשִׁיחַ = נָחָשׁ",
    titulo: "El Mesías y la Serpiente",
    tituloFa: "ماشیح و مار",
    gancho: "El redentor y la serpiente del Edén comparten el mismo número. La Cabalá lo sabía hace 800 años.",
    ganchoFa: "رهاننده و مارِ عدن یک عدد دارند. کابالا ۸۰۰ سال است این را می‌داند.",
    serie: "dos-filos",
    color: "#c9a43e",
    orden: 1,
  },
  {
    slug: "26",
    numero: "26",
    he: "אֶחָד · אַהֲבָה",
    titulo: "Unidad y Amor",
    tituloFa: "یگانگی و عشق",
    gancho: "Ejad (Uno) y Ahavá (Amor) suman lo mismo: 26 — el Nombre de Dios. La unidad y el amor son Su Nombre.",
    ganchoFa: "اِچاد (یک) و اَهاوا (عشق) برابرند: ۲۶ — نامِ خدا.",
    serie: "dos-filos",
    color: "#f0d060",
    orden: 2,
  },
  {
    slug: "tamar",
    he: "תָּמָר",
    titulo: "El velo que escondía al Mesías",
    tituloFa: "تامار — حجابی که ماشیح را پنهان می‌کرد",
    gancho: "El mayor escándalo de la Torá esconde el nacimiento de la línea del Mashíaj. Mientras los hombres veían vergüenza, el Cielo encendía la luz del Redentor.",
    ganchoFa: "بزرگ‌ترین رسواییِ تورات، تولدِ تبارِ ماشیح را پنهان می‌کند. آنچه جهان می‌پوشاند، خدا تاج می‌بخشد.",
    serie: "dos-filos",
    color: "#c9a43e",
    orden: 3,
  },
  {
    slug: "betsabe",
    he: "בַּת־שֶׁבַע",
    titulo: "Betsabé — El viajero que se quedó a vivir",
    tituloFa: "بَت‌شِبَع — مسافری که ماند تا بماند",
    gancho: "¿Quién se acostó con Betsabé: el rey David… o un viajero extraño? El Talmud lee la caída más famosa de la Biblia con una sola imagen —el huésped que se vuelve amo— y, en su raíz, esconde la luz del Mashíaj.",
    ganchoFa: "چه کسی با بَت‌شِبَع خوابید: داوودِ پادشاه… یا مسافری بیگانه؟ تلمود مشهورترین سقوطِ کتاب مقدس را با یک تصویر می‌خواند —مهمانی که ارباب می‌شود— و در ریشه‌اش، نورِ ماشیح را پنهان می‌کند.",
    serie: "dos-filos",
    color: "#cf8c52",
    orden: 3.5,
  },
  {
    slug: "lot",
    he: "לוֹט",
    titulo: "Lot — Las dos hijas sin nombre",
    tituloFa: "لوط — دو دخترِ بی‌نام",
    gancho: "Las dos mujeres de las que nace el linaje del Rey David no tienen nombre… y lo que hicieron rompió todo tabú. Del barro más bajo —una cueva, tras el fin de un mundo— el Cielo sacó la corona del Mashíaj.",
    ganchoFa: "دو زنی که تبارِ داوودِ پادشاه از آنان زاده می‌شود، نامی ندارند… و آنچه کردند هر تابویی را شکست. از پست‌ترین گِل، خدا تاجِ ماشیح را برآورد.",
    serie: "dos-filos",
    color: "#d8a24a",
    orden: 3.7,
  },
  {
    slug: "yehuda",
    he: "צָדְקָה מִמֶּנִּי",
    titulo: "Yehudá — El rey que se declaró culpable",
    tituloFa: "یهودا — پادشاهی که خود را گناهکار خواند",
    gancho: "Pudo callar y dejarla arder. En cambio dijo dos palabras —«ella es más justa que yo»— y se hundió en público para salvarla. Esa confesión le ganó el cetro eterno, el Nombre de Dios dentro de su nombre, y la línea directa del Mashíaj ben David.",
    ganchoFa: "می‌توانست خاموش بماند و بگذارد بسوزد. اما دو واژه گفت —«او از من پارساتر است»— و در برابر همگان خود را فروشکست تا او را برهاند. آن اعتراف، عصای جاودان، نامِ خدا را در نامش، و تبارِ مستقیمِ ماشیح بن داوود را به او بخشید.",
    serie: "dos-filos",
    color: "#caa23f",
    orden: 3.8,
  },
  {
    slug: "ropas-de-luz",
    he: "כָּתְנוֹת עוֹר · אוֹר",
    titulo: "De Ropas de Luz a Piel de Serpiente",
    tituloFa: "از جامه‌های نور تا پوست مار",
    gancho: "Una sola letra separa la «ropa de luz» (אוֹר) de la «ropa de piel» (עוֹר). Hubo una falta real en el Edén — pero esa caída tenía un lugar en el plan: vestir la luz de piel para que el hombre la rescate desde abajo. La caída necesaria para el Tikún.",
    ganchoFa: "تنها یک حرف، «جامهٔ نور» (אוֹר) را از «جامهٔ پوست» (עוֹר) جدا می‌کند. در عدن لغزشی واقعی رخ داد — اما آن سقوط جایی در نقشه داشت: سقوطِ لازم برای تیکون.",
    serie: "dos-filos",
    color: "#cf8c52",
    orden: 3.9,
  },
  {
    slug: "chispas-en-las-naciones",
    numero: "288",
    he: "רפ״ח נִיצוֹצוֹת",
    titulo: "Las chispas del Mashíaj en las naciones",
    tituloFa: "جرقه‌های ماشیح در میان ملت‌ها",
    gancho: "El linaje del Mashíaj no es «puro»: Rut la moabita, Rajav la cananea, Naamá la amonita, Yitró el midianita. Las chispas más altas cayeron más lejos —entre las naciones— y la redención es recogerlas. El converso es una chispa que vuelve a casa.",
    ganchoFa: "تبارِ ماشیح «پاک» نیست: روتِ موآبی، راحاوِ کنعانی، نَعَمای عَمّونی، یترُوی مدیانی. برترین جرقه‌ها دورتر افتادند — میان ملت‌ها — و رستگاری یعنی گردآوریِ آن‌ها. گِر (نوكیش) جرقه‌ای است که به خانه بازمی‌گردد.",
    serie: "dos-filos",
    color: "#dcae46",
    orden: 4.5,
  },
  {
    slug: "linaje",
    he: "עֲבֵרָה לִשְׁמָהּ",
    titulo: "El linaje prohibido del Mashíaj",
    tituloFa: "تبارِ ممنوعِ ماشیح",
    gancho: "El Mashíaj desciende por los lugares más caídos: incesto, prostitución, adulterio. La sombra, dada vuelta, es la luz.",
    ganchoFa: "ماشیح از فروافتاده‌ترین جاها فرود می‌آید. سایه، وارونه، نور است.",
    serie: "dos-filos",
    color: "#e0a850",
    orden: 4,
  },
  {
    slug: "habakuk",
    numero: "216",
    he: "חֲבַקּוּק",
    titulo: "Habakuk y el doble abrazo",
    tituloFa: "حَبَقّوق و دو آغوش",
    gancho: "Shigyonot: ¿errores o instrumentos? Habakuk: ¿un abrazo o dos? Una palabra con dos filos, y una gematría que abraza la partición del mar.",
    ganchoFa: "شیگیونوت: خطاها یا سازها؟ حَبَقّوق: یک آغوش یا دو؟ یک واژه با دو لبه.",
    serie: "dos-filos",
    color: "#b89a4e",
    orden: 5,
  },
  {
    slug: "bilaam",
    he: "בִּלְעָם",
    titulo: "Bilaam — la boca de la serpiente",
    tituloFa: "بیلعام — دهانِ مار",
    gancho: "El hechicero con el espíritu de Samael vino a maldecir a Israel — y de su boca salió la profecía mesiánica más profunda de la Biblia. Del lugar más oscuro, la luz más brillante.",
    ganchoFa: "جادوگری با روحِ سَمائل آمد تا نفرین کند — و از دهانش ژرف‌ترین پیشگوییِ مسیحایی برآمد.",
    serie: "dos-filos",
    color: "#9a6a8e",
    orden: 6,
  },
  {
    slug: "137",
    numero: "137",
    he: "קַבָּלָה",
    titulo: "137 — El acertijo de la creación",
    tituloFa: "۱۳۷ — معمای آفرینش",
    gancho: "Kabalah = 137. Y la constante de estructura fina α ≈ 1/137 que gobierna la luz. El número que une la Cabalá con la física (Rav Ginsburgh).",
    ganchoFa: "قبالا = ۱۳۷. و ثابتِ ساختارِ ریز α ≈ ۱/۱۳۷ که نور را حکم می‌راند. عددی که کابالا را با فیزیک می‌پیوندد.",
    serie: "gematria",
    color: "#9a6a8e",
    orden: 7,
  },
  {
    slug: "entrelazamiento",
    numero: "137",
    he: "אַהֲבָה ⊗ יִרְאָה",
    titulo: "El entrelazamiento de las almas",
    tituloFa: "درهم‌تنیدگیِ جان‌ها",
    gancho: "Amor (42 veces) + Temor (95 veces) = 137. En la atadura de Isaac, el amor y el temor quedan entrelazados — como dos partículas que actúan como una. Y la Cabalá (=137) es la constante que acopla el alma con Dios.",
    ganchoFa: "عشق (۴۲ بار) + ترس (۹۵ بار) = ۱۳۷. در بستنِ اسحاق، عشق و ترس درهم‌تنیده می‌شوند — چون دو ذرّه که چون یکی رفتار می‌کنند. و کابالا (=۱۳۷) ثابتی است که جان را به خدا می‌پیوندد.",
    serie: "gematria",
    color: "#b5557a",
    orden: 8,
  },
  {
    slug: "enoch",
    numero: "84",
    he: "חֲנוֹךְ",
    titulo: "Janóoj — la gracia que asciende",
    tituloFa: "حَنوخ — فیضی که بالا می‌رود",
    gancho: "Janóoj «caminó con Dios y desapareció, porque Dios lo tomó». El iniciado que asciende y se vuelve Metatrón, el canal universal (=314). Su nombre (חֲנוֹךְ) y «educación» (חִינּוּךְ) comparten una raíz: el camino que vuelve al hombre vehículo de luz.",
    ganchoFa: "خنوخ «با خدا راه رفت و ناپدید شد، زیرا خدا او را برگرفت». مبتدی‌ای که بالا می‌رود و مِطَطرون می‌شود، کانالِ جهانی (=۳۱۴). نامِ او (חֲנוֹךְ) و «تربیت» (חִינּוּךְ) یک ریشه دارند: راهی که انسان را مرکبِ نور می‌کند.",
    serie: "gematria",
    color: "#6cd4e0",
    orden: 8.5,
  },
  {
    slug: "sanador",
    he: "יְהוָה רֹפְאֶךָ",
    titulo: "Yo soy Hashem tu sanador",
    tituloFa: "من خداوند، شفادهندهٔ تو",
    gancho: "«Yo soy Hashem tu sanador» (Éxodo 15:26). La sanidad no es algo que Dios envía — es uno de Sus Nombres. Y la primera cura es el perdón (Salmos 103:3).",
    ganchoFa: "«من خداوند، شفادهندهٔ توام» (خروج ۱۵:۲۶). شفا چیزی نیست که خدا بفرستد — یکی از نام‌های اوست. و نخستین شفا، آمرزش است (مزامیر ۱۰۳:۳).",
    serie: "sanidad",
    color: "#3fa68a",
    orden: 9,
  },
  {
    slug: "refael",
    numero: "311",
    he: "רְפָאֵל",
    titulo: "Refael — «Dios sana»",
    tituloFa: "رفائل — «خدا شفا می‌دهد»",
    gancho: "Refael (=311) es el ángel cuyo nombre dice «Dios sana». Curó a Abraham tras la circuncisión — y el mismo ángel que sana es el que rescata. רפא (281) + אל (31) = 312 = 311+1, el sello del kolel.",
    ganchoFa: "رفائل (=۳۱۱) فرشته‌ای است که نامش می‌گوید «خدا شفا می‌دهد». ابراهام را پس از ختنه شفا داد — و همان فرشته که شفا می‌دهد، همان است که می‌رهاند.",
    serie: "sanidad",
    color: "#5b8fd6",
    orden: 10,
  },
  {
    slug: "serpiente-de-cobre",
    numero: "358",
    he: "נְחַשׁ הַנְּחֹשֶׁת",
    titulo: "La serpiente de cobre",
    tituloFa: "مارِ مفرغین",
    gancho: "La medicina tenía la forma exacta de la enfermedad. Nájash (serpiente) = Mashíaj = 358: la fuerza que envenena, elevada hacia lo Alto, se vuelve la cura.",
    ganchoFa: "درمان درست به شکلِ بیماری بود. مار (نَحَش) = ماشیح = ۳۵۸: نیرویی که زهر می‌ریزد، برافراشته به سویِ بالا، شفا می‌شود.",
    serie: "sanidad",
    color: "#b06a3c",
    orden: 11,
  },
  {
    slug: "refua",
    he: "רְפוּאַת הַנֶּפֶשׁ וּרְפוּאַת הַגּוּף",
    titulo: "Sanación del alma y del cuerpo",
    tituloFa: "شفایِ جان و شفایِ تن",
    gancho: "El alma va primero, y el cuerpo después. No prometemos que el cuerpo siempre sane — pero el alma siempre puede volver a casa.",
    ganchoFa: "نخست جان، آنگاه تن. وعده نمی‌دهیم که تن همیشه شفا یابد — اما جان همیشه می‌تواند به خانه برگردد.",
    serie: "sanidad",
    color: "#7d9b8a",
    orden: 12,
  },
  {
    slug: "21-pactos",
    numero: "21",
    he: "אֶהְיֶה",
    titulo: "El Nombre que vale 21",
    tituloFa: "نامی که ۲۱ است",
    gancho: "Ehyé (אהיה), «Yo Seré» (Éx 3:14), suma 21 — y la Torá guarda 21 pactos que sostienen toda la realidad. En clave de sod, esos 21 son Ehyé hecho estructura: Biná, la octava sefirá.",
    ganchoFa: "اَهیه (אהיה)، «خواهم بود» (خروج ۳:۱۴)، برابر ۲۱ است — و تورات ۲۱ پیمان را نگاه می‌دارد که تمامِ هستی را برپا می‌دارند. در کلیدِ سود، این ۲۱ همان اَهیه است که ساختار شده: بینا.",
    serie: "gematria",
    color: "#1fd8e0",
    orden: 13,
  },
];

export function getMisterio(slug: string): Misterio | undefined {
  return MISTERIOS.find((m) => m.slug === slug);
}

export const MISTERIOS_ORDENADOS = [...MISTERIOS].sort((a, b) => a.orden - b.orden);
