// Catálogo de los Misterios — estudios publicados de Jashmal.
// Cada misterio es una landing en /misterio/{slug}. Para añadir uno nuevo,
// agrega una entrada aquí y crea su página.

export interface Misterio {
  slug: string;          // ruta: /misterio/{slug} y atajo /{slug}
  numero?: string;       // número/gematría destacado (ej. "358")
  he: string;            // término hebreo central
  titulo: string;        // título en español (canónico)
  tituloFa: string;
  tituloEn?: string;     // inglés — lo llena el Sofer por fases ([[i18n-audit]])
  gancho: string;        // una línea de gancho (español)
  ganchoFa: string;
  ganchoEn?: string;     // inglés — lo llena el Sofer por fases
  serie?: string;        // nombre de la serie (para agrupar)
  color: string;
  orden: number;         // orden de aparición (menor = primero)
}

export const MISTERIOS: Misterio[] = [
  {
    slug: "358",
    numero: "358",
    he: "מָשִׁיחַ = נָחָשׁ",
    titulo: "El Mesías y la Serpiente",
    tituloFa: "ماشیح و مار",
    gancho: "El redentor y la serpiente del Edén comparten el mismo número. La Cabalá lo sabía hace 800 años.",
    ganchoFa: "رهاننده و مارِ عدن یک عدد دارند. کابالا ۸۰۰ سال است این را می‌داند.",
    serie: "dos-filos",
    color: "#c9a43e",
    orden: 1,
  },
  {
    slug: "26",
    numero: "26",
    he: "אֶחָד · אַהֲבָה",
    titulo: "Unidad y Amor",
    tituloFa: "یگانگی و عشق",
    gancho: "Ejad (Uno) y Ahavá (Amor) suman lo mismo: 26 — el Nombre de Dios. La unidad y el amor son Su Nombre.",
    ganchoFa: "اِچاد (یک) و اَهاوا (عشق) برابرند: ۲۶ — نامِ خدا.",
    serie: "dos-filos",
    color: "#f0d060",
    orden: 2,
  },
  {
    slug: "tamar",
    he: "תָּמָר",
    titulo: "El velo que escondía al Mesías",
    tituloFa: "تامار — حجابی که ماشیح را پنهان می‌کرد",
    gancho: "El mayor escándalo de la Torá esconde el nacimiento de la línea del Mashíaj. Mientras los hombres veían vergüenza, el Cielo encendía la luz del Redentor.",
    ganchoFa: "بزرگ‌ترین رسواییِ تورات، تولدِ تبارِ ماشیح را پنهان می‌کند. آنچه جهان می‌پوشاند، خدا تاج می‌بخشد.",
    serie: "dos-filos",
    color: "#c9a43e",
    orden: 3,
  },
  {
    slug: "betsabe",
    he: "בַּת־שֶׁבַע",
    titulo: "Betsabé — El viajero que se quedó a vivir",
    tituloFa: "بَت‌شِبَع — مسافری که ماند تا بماند",
    gancho: "¿Quién se acostó con Betsabé: el rey David… o un viajero extraño? El Talmud lee la caída más famosa de la Biblia con una sola imagen —el huésped que se vuelve amo— y, en su raíz, esconde la luz del Mashíaj.",
    ganchoFa: "چه کسی با بَت‌شِبَع خوابید: داوودِ پادشاه… یا مسافری بیگانه؟ تلمود مشهورترین سقوطِ کتاب مقدس را با یک تصویر می‌خواند —مهمانی که ارباب می‌شود— و در ریشه‌اش، نورِ ماشیح را پنهان می‌کند.",
    serie: "dos-filos",
    color: "#cf8c52",
    orden: 3.5,
  },
  {
    slug: "lot",
    he: "לוֹט",
    titulo: "Lot — Las dos hijas sin nombre",
    tituloFa: "لوط — دو دخترِ بی‌نام",
    gancho: "Las dos mujeres de las que nace el linaje del Rey David no tienen nombre… y lo que hicieron rompió todo tabú. Del barro más bajo —una cueva, tras el fin de un mundo— el Cielo sacó la corona del Mashíaj.",
    ganchoFa: "دو زنی که تبارِ داوودِ پادشاه از آنان زاده می‌شود، نامی ندارند… و آنچه کردند هر تابویی را شکست. از پست‌ترین گِل، خدا تاجِ ماشیح را برآورد.",
    serie: "dos-filos",
    color: "#d8a24a",
    orden: 3.7,
  },
  {
    slug: "yehuda",
    he: "צָדְקָה מִמֶּנִּי",
    titulo: "Yehudá — El rey que se declaró culpable",
    tituloFa: "یهودا — پادشاهی که خود را گناهکار خواند",
    gancho: "Pudo callar y dejarla arder. En cambio dijo dos palabras —«ella es más justa que yo»— y se hundió en público para salvarla. Esa confesión le ganó el cetro eterno, el Nombre de Dios dentro de su nombre, y la línea directa del Mashíaj ben David.",
    ganchoFa: "می‌توانست خاموش بماند و بگذارد بسوزد. اما دو واژه گفت —«او از من پارساتر است»— و در برابر همگان خود را فروشکست تا او را برهاند. آن اعتراف، عصای جاودان، نامِ خدا را در نامش، و تبارِ مستقیمِ ماشیح بن داوود را به او بخشید.",
    serie: "dos-filos",
    color: "#caa23f",
    orden: 3.8,
  },
  {
    slug: "ropas-de-luz",
    he: "כָּתְנוֹת עוֹר · אוֹר",
    titulo: "De Ropas de Luz a Piel de Serpiente",
    tituloFa: "از جامه‌های نور تا پوست مار",
    gancho: "Una sola letra separa la «ropa de luz» (אוֹר) de la «ropa de piel» (עוֹר). Hubo una falta real en el Edén — pero esa caída tenía un lugar en el plan: vestir la luz de piel para que el hombre la rescate desde abajo. La caída necesaria para el Tikún.",
    ganchoFa: "تنها یک حرف، «جامهٔ نور» (אוֹר) را از «جامهٔ پوست» (עוֹר) جدا می‌کند. در عدن لغزشی واقعی رخ داد — اما آن سقوط جایی در نقشه داشت: سقوطِ لازم برای تیکون.",
    serie: "dos-filos",
    color: "#cf8c52",
    orden: 3.9,
  },
  {
    slug: "chispas-en-las-naciones",
    numero: "288",
    he: "רפ״ח נִיצוֹצוֹת",
    titulo: "Las chispas del Mashíaj en las naciones",
    tituloFa: "جرقه‌های ماشیح در میان ملت‌ها",
    gancho: "El linaje del Mashíaj no es «puro»: Rut la moabita, Rajav la cananea, Naamá la amonita, Yitró el midianita. Las chispas más altas cayeron más lejos —entre las naciones— y la redención es recogerlas. El converso es una chispa que vuelve a casa.",
    ganchoFa: "تبارِ ماشیح «پاک» نیست: روتِ موآبی، راحاوِ کنعانی، نَعَمای عَمّونی، یترُوی مدیانی. برترین جرقه‌ها دورتر افتادند — میان ملت‌ها — و رستگاری یعنی گردآوریِ آن‌ها. گِر (نوكیش) جرقه‌ای است که به خانه بازمی‌گردد.",
    serie: "dos-filos",
    color: "#dcae46",
    orden: 4.5,
  },
  {
    slug: "linaje",
    he: "עֲבֵרָה לִשְׁמָהּ",
    titulo: "El linaje prohibido del Mashíaj",
    tituloFa: "تبارِ ممنوعِ ماشیح",
    gancho: "El Mashíaj desciende por los lugares más caídos: incesto, prostitución, adulterio. La sombra, dada vuelta, es la luz.",
    ganchoFa: "ماشیح از فروافتاده‌ترین جاها فرود می‌آید. سایه، وارونه، نور است.",
    serie: "dos-filos",
    color: "#e0a850",
    orden: 4,
  },
  {
    slug: "habakuk",
    numero: "216",
    he: "חֲבַקּוּק",
    titulo: "Habakuk y el doble abrazo",
    tituloFa: "حَبَقّوق و دو آغوش",
    gancho: "Shigyonot: ¿errores o instrumentos? Habakuk: ¿un abrazo o dos? Una palabra con dos filos, y una gematría que abraza la partición del mar.",
    ganchoFa: "شیگیونوت: خطاها یا سازها؟ حَبَقّوق: یک آغوش یا دو؟ یک واژه با دو لبه.",
    serie: "dos-filos",
    color: "#b89a4e",
    orden: 5,
  },
  {
    slug: "bilaam",
    he: "בִּלְעָם",
    titulo: "Bilaam — la boca de la serpiente",
    tituloFa: "بیلعام — دهانِ مار",
    gancho: "El hechicero con el espíritu de Samael vino a maldecir a Israel — y de su boca salió la profecía mesiánica más profunda de la Biblia. Del lugar más oscuro, la luz más brillante.",
    ganchoFa: "جادوگری با روحِ سَمائل آمد تا نفرین کند — و از دهانش ژرف‌ترین پیشگوییِ مسیحایی برآمد.",
    serie: "dos-filos",
    color: "#9a6a8e",
    orden: 6,
  },
  {
    slug: "137",
    numero: "137",
    he: "קַבָּלָה",
    titulo: "137 — El acertijo de la creación",
    tituloFa: "۱۳۷ — معمای آفرینش",
    gancho: "Kabalah = 137. Y la constante de estructura fina α ≈ 1/137 que gobierna la luz. El número que une la Cabalá con la física (Rav Ginsburgh).",
    ganchoFa: "قبالا = ۱۳۷. و ثابتِ ساختارِ ریز α ≈ ۱/۱۳۷ که نور را حکم می‌راند. عددی که کابالا را با فیزیک می‌پیوندد.",
    serie: "gematria",
    color: "#9a6a8e",
    orden: 7,
  },
  {
    slug: "entrelazamiento",
    numero: "137",
    he: "אַהֲבָה ⊗ יִרְאָה",
    titulo: "El entrelazamiento de las almas",
    tituloFa: "درهم‌تنیدگیِ جان‌ها",
    gancho: "Amor (42 veces) + Temor (95 veces) = 137. En la atadura de Isaac, el amor y el temor quedan entrelazados — como dos partículas que actúan como una. Y la Cabalá (=137) es la constante que acopla el alma con Dios.",
    ganchoFa: "عشق (۴۲ بار) + ترس (۹۵ بار) = ۱۳۷. در بستنِ اسحاق، عشق و ترس درهم‌تنیده می‌شوند — چون دو ذرّه که چون یکی رفتار می‌کنند. و کابالا (=۱۳۷) ثابتی است که جان را به خدا می‌پیوندد.",
    serie: "gematria",
    color: "#b5557a",
    orden: 8,
  },
  {
    slug: "chashmal-vav",
    numero: "378",
    he: "חַשְׁמַל · וָאו",
    titulo: "El Chashmal — el silencio que habla",
    tituloFa: "چَشمَل — سکوتی که سخن می‌گوید",
    gancho: "La palabra más misteriosa de la Biblia lleva dentro su propio secreto: חש (silencio, 308) + מל (habla, 70) = 378 = חשמל. Y la vav, el «y» más simple del hebreo, se expande hasta revelar exactamente 137 — la constante de la luz.",
    ganchoFa: "رازآمیزترین واژهٔ کتاب مقدس، رازِ خود را در درون دارد: חש (سکوت، ۳۰۸) + מל (سخن، ۷۰) = ۳۷۸ = חשמל. و واو، سادهٔ‌ترین «و» در عبری، گسترش می‌یابد تا دقیقاً ۱۳۷ را آشکار کند.",
    serie: "gematria",
    color: "#7855bb",
    orden: 8.3,
  },
  {
    slug: "machlokot-koraj",
    numero: "578",
    he: "מַחֲלֹקֶת",
    titulo: "Koraj — cuando la verdad se vuelve un arma",
    tituloFa: "قورَح — وقتی حقیقت به سلاح بدل می‌شود",
    gancho: "Koraj tenía razón: «todos somos santos» es verdad. Pero la usó como arma. Machlóket (disputa) = 578 = Shalom (paz, 376) + Rav (grandeza, 202). La paz más el ego produce la guerra.",
    ganchoFa: "قورَح حق داشت: «همه مقدسیم» راست است. اما آن را چون سلاح به کار برد. مَحلوقت (نزاع) = ۵۷۸ = شالوم (صلح، ۳۷۶) + رَو (بزرگی، ۲۰۲). صلح به‌علاوهٔ خودبزرگی، جنگ می‌زاید.",
    serie: "gematria",
    color: "#b0413e",
    orden: 8.7,
  },
  {
    slug: "enoch",
    numero: "84",
    he: "חֲנוֹךְ",
    titulo: "Janóoj — la gracia que asciende",
    tituloFa: "حَنوخ — فیضی که بالا می‌رود",
    gancho: "Janóoj «caminó con Dios y desapareció, porque Dios lo tomó». El iniciado que asciende y se vuelve Metatrón, el canal universal (=314). Su nombre (חֲנוֹךְ) y «educación» (חִינּוּךְ) comparten una raíz: el camino que vuelve al hombre vehículo de luz.",
    ganchoFa: "خنوخ «با خدا راه رفت و ناپدید شد، زیرا خدا او را برگرفت». مبتدی‌ای که بالا می‌رود و مِطَطرون می‌شود، کانالِ جهانی (=۳۱۴). نامِ او (חֲנוֹךְ) و «تربیت» (חִינּוּךְ) یک ریشه دارند: راهی که انسان را مرکبِ نور می‌کند.",
    serie: "gematria",
    color: "#6cd4e0",
    orden: 8.5,
  },
  {
    slug: "sanador",
    he: "יְהוָה רֹפְאֶךָ",
    titulo: "Yo soy Hashem tu sanador",
    tituloFa: "من خداوند، شفادهندهٔ تو",
    gancho: "«Yo soy Hashem tu sanador» (Éxodo 15:26). La sanidad no es algo que Dios envía — es uno de Sus Nombres. Y la primera cura es el perdón (Salmos 103:3).",
    ganchoFa: "«من خداوند، شفادهندهٔ توام» (خروج ۱۵:۲۶). شفا چیزی نیست که خدا بفرستد — یکی از نام‌های اوست. و نخستین شفا، آمرزش است (مزامیر ۱۰۳:۳).",
    serie: "sanidad",
    color: "#3fa68a",
    orden: 9,
  },
  {
    slug: "refael",
    numero: "311",
    he: "רְפָאֵל",
    titulo: "Refael — «Dios sana»",
    tituloFa: "رفائل — «خدا شفا می‌دهد»",
    gancho: "Refael (=311) es el ángel cuyo nombre dice «Dios sana». Curó a Abraham tras la circuncisión — y el mismo ángel que sana es el que rescata. רפא (281) + אל (31) = 312 = 311+1, el sello del kolel.",
    ganchoFa: "رفائل (=۳۱۱) فرشته‌ای است که نامش می‌گوید «خدا شفا می‌دهد». ابراهام را پس از ختنه شفا داد — و همان فرشته که شفا می‌دهد، همان است که می‌رهاند.",
    serie: "sanidad",
    color: "#5b8fd6",
    orden: 10,
  },
  {
    slug: "serpiente-de-cobre",
    numero: "358",
    he: "נְחַשׁ הַנְּחֹשֶׁת",
    titulo: "La serpiente de cobre",
    tituloFa: "مارِ مفرغین",
    gancho: "La medicina tenía la forma exacta de la enfermedad. Nájash (serpiente) = Mashíaj = 358: la fuerza que envenena, elevada hacia lo Alto, se vuelve la cura.",
    ganchoFa: "درمان درست به شکلِ بیماری بود. مار (نَحَش) = ماشیح = ۳۵۸: نیرویی که زهر می‌ریزد، برافراشته به سویِ بالا، شفا می‌شود.",
    serie: "sanidad",
    color: "#b06a3c",
    orden: 11,
  },
  {
    slug: "refua",
    he: "רְפוּאַת הַנֶּפֶשׁ וּרְפוּאַת הַגּוּף",
    titulo: "Sanación del alma y del cuerpo",
    tituloFa: "شفایِ جان و شفایِ تن",
    gancho: "El alma va primero, y el cuerpo después. No prometemos que el cuerpo siempre sane — pero el alma siempre puede volver a casa.",
    ganchoFa: "نخست جان، آنگاه تن. وعده نمی‌دهیم که تن همیشه شفا یابد — اما جان همیشه می‌تواند به خانه برگردد.",
    serie: "sanidad",
    color: "#7d9b8a",
    orden: 12,
  },
  {
    slug: "21-pactos",
    numero: "21",
    he: "אֶהְיֶה",
    titulo: "El Nombre que vale 21",
    tituloFa: "نامی که ۲۱ است",
    gancho: "Ehyé (אהיה), «Yo Seré» (Éx 3:14), suma 21 — y la Torá guarda 21 pactos que sostienen toda la realidad. En clave de sod, esos 21 son Ehyé hecho estructura: Biná, la octava sefirá.",
    ganchoFa: "اَهیه (אהיה)، «خواهم بود» (خروج ۳:۱۴)، برابر ۲۱ است — و تورات ۲۱ پیمان را نگاه می‌دارد که تمامِ هستی را برپا می‌دارند. در کلیدِ سود، این ۲۱ همان اَهیه است که ساختار شده: بینا.",
    serie: "gematria",
    color: "#1fd8e0",
    orden: 13,
  },

  // ── SERIE "MASHÍAJ" — Del Enigma del Mashíaj al Ajarít HaYamim ──────────────
  // 13 estudios: Estudio 0 (la Puerta, publicado) + 12 módulos (placeholders
  // "próximamente" hasta que el Sofer los escriba). Slugs según 00-MAPA-SERIE.md.
  {
    slug: "enigma-mashiaj",
    he: "חִידַת הַמָּשִׁיחַ",
    titulo: "El Enigma del Mashíaj — La Tesis",
    tituloFa: "معمای ماشیح — نهاد",
    gancho: "¿Persona, conciencia colectiva o estado de conciencia? El Mashíaj es las tres — y casi nadie lo sabe. Capítulo 1, la Tesis: el despertar desde abajo, la redención que subimos con nuestras obras. La puerta de la serie sobre el fin de los días.",
    ganchoFa: "شخص، آگاهیِ جمعی یا حالتِ آگاهی؟ ماشیح هر سه است — و کمتر کسی این را می‌داند. فصلِ ۱، نهاد: بیداری از پایین، رستگاری‌ای که با کارهای خود بالا می‌بریم. دروازهٔ سری دربارهٔ آخریتِ روزها.",
    serie: "mashiaj",
    color: "#c9a43e",
    orden: 0,
  },
  {
    slug: "despertar-de-lo-alto",
    he: "אִתְעֲרוּתָא דִּלְעֵילָא",
    titulo: "El Despertar desde Arriba — La Antítesis",
    tituloFa: "بیداری از بالا — پادنهاد",
    gancho: "Creías que la redención la subimos nosotros. La otra mitad del enigma gira el espejo: el Mashíaj es, antes que nada, descenso — Dios baja primero, y la luz más alta no se gana: se recibe. Capítulo 2, la Antítesis.",
    ganchoFa: "می‌پنداشتی رستگاری را ما بالا می‌بریم. نیمهٔ دیگرِ معما آینه را می‌چرخاند: ماشیح پیش از هر چیز فرود است — خدا نخست پایین می‌آید، و برترین نور به دست نمی‌آید: دریافت می‌شود. فصلِ ۲، پادنهاد.",
    serie: "mashiaj",
    color: "#caa23f",
    orden: 0.02,
  },
  {
    slug: "tercer-templo",
    he: "בֵּית הַמִּקְדָּשׁ הַשְּׁלִישִׁי",
    titulo: "El Tercer Templo — La Síntesis",
    tituloFa: "معبدِ سوم — هم‌نهاد",
    gancho: "Una redención sube, la otra baja. ¿Cuál es la verdadera? Las dos a la vez — y la prueba se puede tocar: el Tercer Templo. El hombre levanta los muros; Dios trae el fuego desde lo Alto. Capítulo 3, la Síntesis que sella la Puerta.",
    ganchoFa: "یک رستگاری بالا می‌رود، دیگری پایین می‌آید. کدام راستین است؟ هر دو با هم — و گواهش لمس‌شدنی است: معبدِ سوم. انسان دیوارها را برمی‌افرازد؛ خدا آتش را از بالا می‌آورد. فصلِ ۳، هم‌نهادی که دروازه را مُهر می‌کند.",
    serie: "mashiaj",
    color: "#cf8c52",
    orden: 0.04,
  },
  {
    slug: "simiente-mesianica",
    he: "הַזֶּרַע הַמְּשִׁיחִי",
    titulo: "La Simiente Mesiánica",
    tituloFa: "بذرِ ماشیحی",
    gancho: "Una simiente —una zéra— atraviesa toda la historia como si tuviera voluntad propia: un hilo fino de descendencia que sobrevive a cada intento de cortarlo y avanza por los caminos más improbables hasta el rey que repara la fractura del Edén. El Midrash la llama «la simiente que viene de otro lugar».",
    ganchoFa: "بذری —یک زِرَع— گویی با ارادهٔ خود از سراسرِ تاریخ می‌گذرد: رشته‌ای باریک از نسل که از هر کوششی برای بریدنش جان به‌در می‌برد و از ناممکن‌ترین راه‌ها تا پادشاهی که شکافِ عدن را ترمیم می‌کند پیش می‌رود. میدراش آن را «بذری که از جای دیگر می‌آید» می‌نامد.",
    serie: "mashiaj",
    color: "#d8a24a",
    orden: 0.05,
  },
  {
    slug: "ajarit-hayamim",
    he: "אַחֲרִית הַיָּמִים",
    titulo: "¿Qué es Ajarít HaYamim?",
    tituloFa: "آخریتِ روزها چیست؟",
    gancho: "«Ajarít hayamim» no significa el final del mundo. Significa el mundo llegando a ser lo que siempre debió ser. Cuatro términos que el público confunde —Gueulá, Yemot HaMashíaj, Tejiyat HaMetim, Olam HaBa— son grados de un solo ascenso.",
    ganchoFa: "«آخریتِ روزها» پایانِ جهان نیست. یعنی جهانی که سرانجام همان می‌شود که همیشه باید می‌بود — کمالِ زمان، نه پایانِ آن.",
    serie: "mashiaj",
    color: "#caa23f",
    orden: 0.1,
  },
  {
    slug: "finalidad-creacion",
    numero: "45",
    he: "תַּכְלִית הַבְּרִיאָה",
    titulo: "La Finalidad de la Creación",
    tituloFa: "غایتِ آفرینش",
    gancho: "Dios no creó el mundo y luego decidió redimirlo. Lo creó porque quería una casa aquí abajo. La redención es la mudanza. Gueulá = Adam = 45.",
    ganchoFa: "خدا جهان را نیافرید و سپس به رستگاری‌اش بیندیشد. آفرید چون خانه‌ای در پایین می‌خواست. رستگاری همان اسباب‌کشی است. گئولا = آدام = ۴۵.",
    serie: "mashiaj",
    color: "#cf8c52",
    orden: 0.2,
  },
  {
    slug: "exilio-redencion",
    numero: "44→45",
    he: "גָּלוּת וּגְאוּלָּה",
    titulo: "Exilio y Redención en los Profetas",
    tituloFa: "تبعید و رستگاری در پیامبران",
    gancho: "Golá (exilio) = 44; Gueulá (redención) = 45. Entre el exilio y la redención hay una sola letra: la א, el Alef — Dios mismo entrando en la palabra. La redención empieza en el corazón, no en la política.",
    ganchoFa: "گولا (تبعید) = ۴۴؛ گئولا (رستگاری) = ۴۵. میانِ تبعید و رستگاری تنها یک حرف است: الف — خودِ خدا. رستگاری از دل آغاز می‌شود، نه از سیاست.",
    serie: "mashiaj",
    color: "#d8a24a",
    orden: 0.3,
  },
  {
    slug: "mashiaj-jazal",
    numero: "138",
    he: "הַמָּשִׁיחַ בְּדִבְרֵי חֲזַ״ל",
    titulo: "El Mashíaj en la Literatura Rabínica",
    tituloFa: "ماشیح در ادبیاتِ ربانی",
    gancho: "El Talmud no se pone de acuerdo en el nombre del Mashíaj: ¿Shiló? ¿Yinón? ¿Janiná? ¿Menajem? Y tiene razón en todos. Menajem (el Consolador) = Tzémaj (el Retoño) = 138: consolar es hacer retoñar.",
    ganchoFa: "تلمود بر نامِ ماشیح اتفاق ندارد: شیلو؟ یینون؟ حنینا؟ مناحم؟ و در همه حق دارد. مناحم (تسلی‌دهنده) = تسماخ (جوانه) = ۱۳۸: تسلی‌دادن یعنی جوانه‌زدن.",
    serie: "mashiaj",
    color: "#dcae46",
    orden: 0.4,
  },
  {
    slug: "daniel-apocaliptica",
    he: "דָּנִיֵּאל וְהַחֲזוֹן",
    titulo: "Daniel y la Apocalíptica",
    tituloFa: "دانیال و مکاشفه",
    gancho: "La primera vez que la Biblia promete que los muertos despertarán está escondida en un libro «sellado hasta el fin». Las cuatro bestias, el fin de los imperios y la resurrección, en clave.",
    ganchoFa: "نخستین باری که کتاب مقدس وعده می‌دهد مردگان بیدار خواهند شد، در کتابی «مُهرشده تا پایان» پنهان است. چهار جانور، پایانِ امپراتوری‌ها و رستاخیز، در رمز.",
    serie: "mashiaj",
    color: "#b89a4e",
    orden: 0.5,
  },
  {
    slug: "gog-umagog",
    numero: "26",
    he: "גּוֹג וּמָגוֹג",
    titulo: "Gog uMagog",
    tituloFa: "جوج و ماجوج",
    gancho: "Toda la profecía de la guerra final desemboca en cinco palabras: «YHVH será Uno y Su Nombre Uno» (Zejaryá 14:9). Los dos «Uno» suman 13+13 = 26 = YHVH. La guerra es el parto de la Unidad.",
    ganchoFa: "تمامِ نبوتِ جنگِ پایانی به پنج واژه می‌رسد: «خداوند یکی است و نامش یکی» (زخریا ۱۴:۹). دو «یک» جمعاً ۱۳+۱۳ = ۲۶ = یهوه. جنگ، زایمانِ یگانگی است.",
    serie: "mashiaj",
    color: "#9a6a8e",
    orden: 0.6,
  },
  {
    slug: "zohar-redencion",
    he: "הַזֹּהַר וְהַגְּאוּלָּה",
    titulo: "El Zóhar y la Redención",
    tituloFa: "زوهر و رستگاری",
    gancho: "El Zóhar dice algo escandaloso: cuando Israel está en el exilio, Dios también lo está. La Shejiná baja con el pueblo, y la redención se teje a dos voces — el despertar de abajo y el de arriba.",
    ganchoFa: "زوهر چیزی شگفت می‌گوید: وقتی اسرائیل در تبعید است، خدا نیز هست. شخینا با قوم فرود می‌آید، و رستگاری به دو صدا بافته می‌شود — بیداری از پایین و از بالا.",
    serie: "mashiaj",
    color: "#7855bb",
    orden: 0.7,
  },
  {
    slug: "tikunei-zohar",
    numero: "913",
    he: "תִּקּוּנֵי הַזֹּהַר",
    titulo: "Tikunei HaZóhar y los Procesos Finales",
    tituloFa: "تیکونِی زوهر و فرایندهای پایانی",
    gancho: "Bereshit = 913. De esa sola palabra el Tikunei HaZóhar saca 70 explicaciones. El comienzo del mundo contenía, plegado, todo su final — y el mundo está hecho de letras divinas que el tikún reordena.",
    ganchoFa: "برئشیت = ۹۱۳. تیکونِی زوهر از همین یک واژه ۷۰ توضیح برمی‌آورد. آغازِ جهان، پایانِ آن را در خود تا کرده بود — و جهان از حروفِ الهی ساخته شده که تیکون آن‌ها را بازمی‌چیند.",
    serie: "mashiaj",
    color: "#b5557a",
    orden: 0.8,
  },
  {
    slug: "el-ari",
    numero: "45",
    he: "הָאֲרִ״י וּמִבְנֵה הַבְּרִיאָה",
    titulo: "El Arí y la Estructura Cósmica",
    tituloFa: "آری و ساختارِ آفرینش",
    gancho: "El sistema luriano completo —Tzimtzum, Shevirat HaKelim, Birur y Tikún—: la «física» de toda la serie. El mundo nació roto a propósito. Adam = Gueulá = Mah = 45: somos el instrumento del tikún.",
    ganchoFa: "نظامِ کاملِ لوریانی —تسیمتسوم، شکستِ ظرف‌ها، بیرور و تیکون—: «فیزیکِ» تمامِ سری. جهان عمداً شکسته زاده شد. آدام = گئولا = مَه = ۴۵: ما ابزارِ تیکونیم.",
    serie: "mashiaj",
    color: "#6cd4e0",
    orden: 0.9,
  },
  {
    slug: "shaar-hagilgulim",
    numero: "37",
    he: "שַׁעַר הַגִּלְגּוּלִים",
    titulo: "Shaar HaGilgulim y la Rectificación de las Almas",
    tituloFa: "شَعَر هَگیلگولیم و اصلاحِ جان‌ها",
    gancho: "Yejidá = Hével = 37. El punto más alto de tu alma carga la memoria del primer hijo que murió. La reencarnación es el mecanismo del tikún personal: cada vez que te corriges, reparas algo del Edén.",
    ganchoFa: "یِحیدا = هِوِل = ۳۷. بلندترین نقطهٔ جانِ تو، یادِ نخستین فرزندی را که مُرد در خود دارد. تناسخ سازوکارِ تیکونِ شخصی است: هر بار که خود را اصلاح می‌کنی، چیزی از عدن را ترمیم می‌کنی.",
    serie: "mashiaj",
    color: "#3fa68a",
    orden: 0.95,
  },
  {
    slug: "jasidut-redencion",
    numero: "26",
    he: "חֲסִידוּת וְהַגְּאוּלָּה הַפְּנִימִית",
    titulo: "Jasidut y la Redención Interior",
    tituloFa: "حَسیدوت و رستگاریِ درونی",
    gancho: "Ahavá (amor) = 13 y Ejad (uno) = 13. Súmalos: 26 = YHVH. Cuando dos amores se vuelven uno, aparece el Nombre. La Gueulá empieza dentro: la redención del mundo empieza en cómo amas hoy.",
    ganchoFa: "اَهاوا (عشق) = ۱۳ و اِچاد (یک) = ۱۳. جمع‌شان: ۲۶ = یهوه. وقتی دو عشق یکی می‌شوند، نام پدیدار می‌گردد. رستگاری از درون آغاز می‌شود: از این‌که امروز چگونه عشق می‌ورزی.",
    serie: "mashiaj",
    color: "#5b8fd6",
    orden: 0.97,
  },
  {
    slug: "olam-haba",
    numero: "358",
    he: "עוֹלָם הַבָּא וְהַתַּכְלִית",
    titulo: "Olam HaBa y la Consumación Final",
    tituloFa: "عولام هَبا و غایتِ نهایی",
    gancho: "El cierre del arco: la serie empezó con un enigma —«¿qué es el Mashíaj?»— y termina con cinco palabras: «YHVH Uno, Su Nombre Uno». Mashíaj = Najash = 358: el Mashíaj nunca fue una persona que llega; es el mundo volviéndose Uno.",
    ganchoFa: "بستنِ کمان: سری با معمایی آغاز شد —«ماشیح چیست؟»— و با پنج واژه پایان می‌یابد: «خداوند یکی، نامش یکی». ماشیح = ناحاش = ۳۵۸: ماشیح هرگز شخصی نبود که می‌آید؛ جهان است که یکی می‌شود.",
    serie: "mashiaj",
    color: "#b06a3c",
    orden: 0.99,
  },

  // ── SERIE "CIENCIA" — Cabalá y física (libro «137: The Riddle of Creation») ──
  {
    slug: "cuatro-fuerzas",
    numero: "4→1",
    he: "יהוה · ד׳ כֹּחוֹת",
    titulo: "Las cuatro fuerzas y el Nombre de Dios",
    tituloFa: "چهار نیرو و نامِ خدا",
    tituloEn: "The Four Forces and the Name of God",
    gancho:
      "La física tardó un siglo en hallar que solo cuatro fuerzas gobiernan todo el universo: gravedad, electromagnetismo y las fuerzas nucleares fuerte y débil. La Cabalá ya lo decía: son las cuatro letras del Nombre יהוה y los cuatro Mundos. Y antes del Big Bang, las cuatro eran Una.",
    ganchoFa:
      "فیزیک یک قرن زمان برد تا دریابد تنها چهار نیرو بر تمامِ جهان حکم می‌رانند: گرانش، الکترومغناطیس و دو نیرویِ هسته‌ایِ قوی و ضعیف. کابالا از پیش گفته بود: این‌ها چهار حرفِ نامِ یهوه و چهار جهان‌اند. و پیش از مِهبانگ، هر چهار یکی بودند.",
    ganchoEn:
      "It took physics a century to find that just four forces govern the whole universe: gravity, electromagnetism, and the strong and weak nuclear forces. Kabbalah had already said it: they are the four letters of the Name יהוה and the four Worlds. And before the Big Bang, all four were One.",
    serie: "ciencia",
    color: "#48b8f0",
    orden: 14,
  },
  {
    slug: "abrazo-cosmico",
    numero: "496",
    he: "מַלְכוּת",
    titulo: "El abrazo cósmico",
    tituloFa: "آغوشِ کیهانی",
    tituloEn: "The Cosmic Embrace",
    gancho:
      "El universo entero se separa: cada galaxia huye de las demás, y cada vez más rápido. Y sin embargo no se deshace. Una fuerza invisible —que la ciencia aún no logra explicar, el 95 % oscuro del cosmos— lo abraza desde afuera. La Cabalá la llamó Maljut. Su número, 496, es exactamente la dimensión que la teoría de cuerdas necesita para que el universo sea posible.",
    ganchoFa:
      "تمامِ جهان از هم می‌گسلد: هر کهکشان از دیگران می‌گریزد، و هر دم تندتر. و با این همه از هم نمی‌پاشد. نیرویی نادیدنی —که علم هنوز نمی‌تواند توضیحش دهد، ۹۵٪ تاریکِ کیهان— آن را از بیرون در آغوش می‌گیرد. کابالا آن را مَلخوت نامید. عددش، ۴۹۶، دقیقاً همان بُعدی است که نظریهٔ ریسمان برای ممکن‌شدنِ جهان نیاز دارد.",
    ganchoEn:
      "The whole universe is flying apart: every galaxy fleeing the others, faster and faster. And yet it does not come undone. An invisible force —which science still cannot explain, the dark 95 % of the cosmos— embraces it from the outside. Kabbalah called it Malchut. Its number, 496, is exactly the dimension string theory needs for a universe to be possible.",
    serie: "ciencia",
    color: "#6d7bf0",
    orden: 15,
  },

  // ── SERIE "PARASHA" — Estudios completos de parashá con PaRDeS ───────────────
  // Cada entrada de parashá es el ÍNDICE de enseñanzas en /misterio/{slug}.
  // Las sub-enseñanzas viven en /misterio/{slug}/{enseñanza}/page.tsx.
  {
    slug: "parashat-korach",
    numero: "308",
    he: "פָּרָשַׁת קֹרַח",
    titulo: "Parashat Korach",
    tituloFa: "پاراشات قورَح",
    tituloEn: "Parashat Korach",
    gancho: "Korach tenía razón en el diagnóstico. Se equivocó en la prescripción.",
    ganchoFa: "قورَح در تشخیص درست بود. در نسخه اشتباه کرد.",
    ganchoEn: "Korach was right about the diagnosis. He was wrong about the prescription.",
    serie: "parasha",
    color: "#8b3a3a",
    orden: 16,
  },
];

export function getMisterio(slug: string): Misterio | undefined {
  return MISTERIOS.find((m) => m.slug === slug);
}

export const MISTERIOS_ORDENADOS = [...MISTERIOS].sort((a, b) => a.orden - b.orden);
