// AUTO-GENERADO desde el índice de Sefaria. No editar a mano.
// Solo textos primarios; los comentarios los trae el motor RAG.
export interface CatBook { id: string; label: string; he: string; type: "chapters" | "talmud"; units: number; firstDaf?: number; }
export interface CatSub { sub: string | null; subHe: string; books: CatBook[]; }
export interface CatGroup { id: string; he: string; es: string; subs: CatSub[]; }
export const CATALOG: CatGroup[] = [
  { id: "Tanakh", he: "תנ״ך", es: "Tanaj", subs: [
    { sub: "Torá", subHe: "תּוֹרָה", books: [
      { id: "Genesis", label: "Genesis", he: "בראשית", type: "chapters", units: 50 },
      { id: "Exodus", label: "Exodus", he: "שמות", type: "chapters", units: 40 },
      { id: "Leviticus", label: "Leviticus", he: "ויקרא", type: "chapters", units: 27 },
      { id: "Numbers", label: "Numbers", he: "במדבר", type: "chapters", units: 36 },
      { id: "Deuteronomy", label: "Deuteronomy", he: "דברים", type: "chapters", units: 34 },
    ] },
    { sub: "Profetas (Neviim)", subHe: "נְבִיאִים", books: [
      { id: "Joshua", label: "Joshua", he: "יהושע", type: "chapters", units: 24 },
      { id: "Judges", label: "Judges", he: "שופטים", type: "chapters", units: 21 },
      { id: "I Samuel", label: "I Samuel", he: "שמואל א", type: "chapters", units: 31 },
      { id: "II Samuel", label: "II Samuel", he: "שמואל ב", type: "chapters", units: 24 },
      { id: "I Kings", label: "I Kings", he: "מלכים א", type: "chapters", units: 22 },
      { id: "II Kings", label: "II Kings", he: "מלכים ב", type: "chapters", units: 25 },
      { id: "Isaiah", label: "Isaiah", he: "ישעיהו", type: "chapters", units: 66 },
      { id: "Jeremiah", label: "Jeremiah", he: "ירמיהו", type: "chapters", units: 52 },
      { id: "Ezekiel", label: "Ezekiel", he: "יחזקאל", type: "chapters", units: 48 },
      { id: "Hosea", label: "Hosea", he: "הושע", type: "chapters", units: 14 },
      { id: "Joel", label: "Joel", he: "יואל", type: "chapters", units: 4 },
      { id: "Amos", label: "Amos", he: "עמוס", type: "chapters", units: 9 },
      { id: "Obadiah", label: "Obadiah", he: "עובדיה", type: "chapters", units: 1 },
      { id: "Jonah", label: "Jonah", he: "יונה", type: "chapters", units: 4 },
      { id: "Micah", label: "Micah", he: "מיכה", type: "chapters", units: 7 },
      { id: "Nahum", label: "Nahum", he: "נחום", type: "chapters", units: 3 },
      { id: "Habakkuk", label: "Habakkuk", he: "חבקוק", type: "chapters", units: 3 },
      { id: "Zephaniah", label: "Zephaniah", he: "צפניה", type: "chapters", units: 3 },
      { id: "Haggai", label: "Haggai", he: "חגי", type: "chapters", units: 2 },
      { id: "Zechariah", label: "Zechariah", he: "זכריה", type: "chapters", units: 14 },
      { id: "Malachi", label: "Malachi", he: "מלאכי", type: "chapters", units: 3 },
    ] },
    { sub: "Escritos (Ketuvim)", subHe: "כְּתוּבִים", books: [
      { id: "Psalms", label: "Psalms", he: "תהילים", type: "chapters", units: 150 },
      { id: "Proverbs", label: "Proverbs", he: "משלי", type: "chapters", units: 31 },
      { id: "Job", label: "Job", he: "איוב", type: "chapters", units: 42 },
      { id: "Song of Songs", label: "Song of Songs", he: "שיר השירים", type: "chapters", units: 8 },
      { id: "Ruth", label: "Ruth", he: "רות", type: "chapters", units: 4 },
      { id: "Lamentations", label: "Lamentations", he: "איכה", type: "chapters", units: 5 },
      { id: "Ecclesiastes", label: "Ecclesiastes", he: "קהלת", type: "chapters", units: 12 },
      { id: "Esther", label: "Esther", he: "אסתר", type: "chapters", units: 10 },
      { id: "Daniel", label: "Daniel", he: "דניאל", type: "chapters", units: 12 },
      { id: "Ezra", label: "Ezra", he: "עזרא", type: "chapters", units: 10 },
      { id: "Nehemiah", label: "Nehemiah", he: "נחמיה", type: "chapters", units: 13 },
      { id: "I Chronicles", label: "I Chronicles", he: "דברי הימים א", type: "chapters", units: 29 },
      { id: "II Chronicles", label: "II Chronicles", he: "דברי הימים ב", type: "chapters", units: 36 },
    ] },
  ] },
  { id: "Mishnah", he: "מִשְׁנָה", es: "Mishná", subs: [
    { sub: "Séder Zeraim", subHe: "", books: [
      { id: "Mishnah Berakhot", label: "Mishnah Berakhot", he: "משנה ברכות", type: "chapters", units: 9 },
      { id: "Mishnah Peah", label: "Mishnah Peah", he: "משנה פאה", type: "chapters", units: 8 },
      { id: "Mishnah Demai", label: "Mishnah Demai", he: "משנה דמאי", type: "chapters", units: 7 },
      { id: "Mishnah Kilayim", label: "Mishnah Kilayim", he: "משנה כלאים", type: "chapters", units: 9 },
      { id: "Mishnah Sheviit", label: "Mishnah Sheviit", he: "משנה שביעית", type: "chapters", units: 10 },
      { id: "Mishnah Terumot", label: "Mishnah Terumot", he: "משנה תרומות", type: "chapters", units: 11 },
      { id: "Mishnah Maasrot", label: "Mishnah Maasrot", he: "משנה מעשרות", type: "chapters", units: 5 },
      { id: "Mishnah Maaser Sheni", label: "Mishnah Maaser Sheni", he: "משנה מעשר שני", type: "chapters", units: 5 },
      { id: "Mishnah Challah", label: "Mishnah Challah", he: "משנה חלה", type: "chapters", units: 4 },
      { id: "Mishnah Orlah", label: "Mishnah Orlah", he: "משנה ערלה", type: "chapters", units: 3 },
      { id: "Mishnah Bikkurim", label: "Mishnah Bikkurim", he: "משנה ביכורים", type: "chapters", units: 4 },
    ] },
    { sub: "Séder Moed", subHe: "", books: [
      { id: "Mishnah Shabbat", label: "Mishnah Shabbat", he: "משנה שבת", type: "chapters", units: 24 },
      { id: "Mishnah Eruvin", label: "Mishnah Eruvin", he: "משנה עירובין", type: "chapters", units: 10 },
      { id: "Mishnah Pesachim", label: "Mishnah Pesachim", he: "משנה פסחים", type: "chapters", units: 10 },
      { id: "Mishnah Shekalim", label: "Mishnah Shekalim", he: "משנה שקלים", type: "chapters", units: 8 },
      { id: "Mishnah Yoma", label: "Mishnah Yoma", he: "משנה יומא", type: "chapters", units: 8 },
      { id: "Mishnah Sukkah", label: "Mishnah Sukkah", he: "משנה סוכה", type: "chapters", units: 5 },
      { id: "Mishnah Beitzah", label: "Mishnah Beitzah", he: "משנה ביצה", type: "chapters", units: 5 },
      { id: "Mishnah Rosh Hashanah", label: "Mishnah Rosh Hashanah", he: "משנה ראש השנה", type: "chapters", units: 4 },
      { id: "Mishnah Ta'anit", label: "Mishnah Ta'anit", he: "משנה תענית", type: "chapters", units: 4 },
      { id: "Mishnah Megillah", label: "Mishnah Megillah", he: "משנה מגילה", type: "chapters", units: 4 },
      { id: "Mishnah Moed Katan", label: "Mishnah Moed Katan", he: "משנה מועד קטן", type: "chapters", units: 3 },
      { id: "Mishnah Chagigah", label: "Mishnah Chagigah", he: "משנה חגיגה", type: "chapters", units: 3 },
    ] },
    { sub: "Séder Nashim", subHe: "", books: [
      { id: "Mishnah Yevamot", label: "Mishnah Yevamot", he: "משנה יבמות", type: "chapters", units: 16 },
      { id: "Mishnah Ketubot", label: "Mishnah Ketubot", he: "משנה כתובות", type: "chapters", units: 13 },
      { id: "Mishnah Nedarim", label: "Mishnah Nedarim", he: "משנה נדרים", type: "chapters", units: 11 },
      { id: "Mishnah Nazir", label: "Mishnah Nazir", he: "משנה נזיר", type: "chapters", units: 9 },
      { id: "Mishnah Sotah", label: "Mishnah Sotah", he: "משנה סוטה", type: "chapters", units: 9 },
      { id: "Mishnah Gittin", label: "Mishnah Gittin", he: "משנה גיטין", type: "chapters", units: 9 },
      { id: "Mishnah Kiddushin", label: "Mishnah Kiddushin", he: "משנה קידושין", type: "chapters", units: 4 },
    ] },
    { sub: "Séder Nezikin", subHe: "", books: [
      { id: "Mishnah Bava Kamma", label: "Mishnah Bava Kamma", he: "משנה בבא קמא", type: "chapters", units: 10 },
      { id: "Mishnah Bava Metzia", label: "Mishnah Bava Metzia", he: "משנה בבא מציעא", type: "chapters", units: 10 },
      { id: "Mishnah Bava Batra", label: "Mishnah Bava Batra", he: "משנה בבא בתרא", type: "chapters", units: 10 },
      { id: "Mishnah Sanhedrin", label: "Mishnah Sanhedrin", he: "משנה סנהדרין", type: "chapters", units: 11 },
      { id: "Mishnah Makkot", label: "Mishnah Makkot", he: "משנה מכות", type: "chapters", units: 3 },
      { id: "Mishnah Shevuot", label: "Mishnah Shevuot", he: "משנה שבועות", type: "chapters", units: 8 },
      { id: "Mishnah Eduyot", label: "Mishnah Eduyot", he: "משנה עדיות", type: "chapters", units: 8 },
      { id: "Mishnah Avodah Zarah", label: "Mishnah Avodah Zarah", he: "משנה עבודה זרה", type: "chapters", units: 5 },
      { id: "Pirkei Avot", label: "Pirkei Avot", he: "משנה אבות", type: "chapters", units: 6 },
      { id: "Mishnah Horayot", label: "Mishnah Horayot", he: "משנה הוריות", type: "chapters", units: 3 },
    ] },
    { sub: "Séder Kodashim", subHe: "", books: [
      { id: "Mishnah Zevachim", label: "Mishnah Zevachim", he: "משנה זבחים", type: "chapters", units: 14 },
      { id: "Mishnah Menachot", label: "Mishnah Menachot", he: "משנה מנחות", type: "chapters", units: 13 },
      { id: "Mishnah Chullin", label: "Mishnah Chullin", he: "משנה חולין", type: "chapters", units: 12 },
      { id: "Mishnah Bekhorot", label: "Mishnah Bekhorot", he: "משנה בכורות", type: "chapters", units: 9 },
      { id: "Mishnah Arakhin", label: "Mishnah Arakhin", he: "משנה ערכין", type: "chapters", units: 9 },
      { id: "Mishnah Temurah", label: "Mishnah Temurah", he: "משנה תמורה", type: "chapters", units: 7 },
      { id: "Mishnah Keritot", label: "Mishnah Keritot", he: "משנה כריתות", type: "chapters", units: 6 },
      { id: "Mishnah Meilah", label: "Mishnah Meilah", he: "משנה מעילה", type: "chapters", units: 6 },
      { id: "Mishnah Tamid", label: "Mishnah Tamid", he: "משנה תמיד", type: "chapters", units: 7 },
      { id: "Mishnah Middot", label: "Mishnah Middot", he: "משנה מדות", type: "chapters", units: 5 },
      { id: "Mishnah Kinnim", label: "Mishnah Kinnim", he: "משנה קינים", type: "chapters", units: 3 },
    ] },
    { sub: "Séder Tahorot", subHe: "", books: [
      { id: "Mishnah Kelim", label: "Mishnah Kelim", he: "משנה כלים", type: "chapters", units: 30 },
      { id: "Mishnah Oholot", label: "Mishnah Oholot", he: "משנה אהלות", type: "chapters", units: 18 },
      { id: "Mishnah Negaim", label: "Mishnah Negaim", he: "משנה נגעים", type: "chapters", units: 14 },
      { id: "Mishnah Parah", label: "Mishnah Parah", he: "משנה פרה", type: "chapters", units: 12 },
      { id: "Mishnah Tahorot", label: "Mishnah Tahorot", he: "משנה טהרות", type: "chapters", units: 10 },
      { id: "Mishnah Mikvaot", label: "Mishnah Mikvaot", he: "משנה מקואות", type: "chapters", units: 10 },
      { id: "Mishnah Niddah", label: "Mishnah Niddah", he: "משנה נדה", type: "chapters", units: 10 },
      { id: "Mishnah Makhshirin", label: "Mishnah Makhshirin", he: "משנה מכשירין", type: "chapters", units: 6 },
      { id: "Mishnah Zavim", label: "Mishnah Zavim", he: "משנה זבים", type: "chapters", units: 5 },
      { id: "Mishnah Tevul Yom", label: "Mishnah Tevul Yom", he: "משנה טבול יום", type: "chapters", units: 4 },
      { id: "Mishnah Yadayim", label: "Mishnah Yadayim", he: "משנה ידים", type: "chapters", units: 4 },
      { id: "Mishnah Oktzin", label: "Mishnah Oktzin", he: "משנה עוקצים", type: "chapters", units: 3 },
    ] },
  ] },
  { id: "Talmud", he: "תַּלְמוּד בַּבְלִי", es: "Talmud Bavli", subs: [
    { sub: "Séder Zeraim", subHe: "", books: [
      { id: "Berakhot", label: "Berakhot", he: "ברכות", type: "talmud", units: 64, firstDaf: 2 },
    ] },
    { sub: "Séder Moed", subHe: "", books: [
      { id: "Shabbat", label: "Shabbat", he: "שבת", type: "talmud", units: 157, firstDaf: 2 },
      { id: "Eruvin", label: "Eruvin", he: "עירובין", type: "talmud", units: 104, firstDaf: 2 },
      { id: "Pesachim", label: "Pesachim", he: "פסחים", type: "talmud", units: 121, firstDaf: 2 },
      { id: "Rosh Hashanah", label: "Rosh Hashanah", he: "ראש השנה", type: "talmud", units: 34, firstDaf: 2 },
      { id: "Yoma", label: "Yoma", he: "יומא", type: "talmud", units: 88, firstDaf: 2 },
      { id: "Sukkah", label: "Sukkah", he: "סוכה", type: "talmud", units: 56, firstDaf: 2 },
      { id: "Beitzah", label: "Beitzah", he: "ביצה", type: "talmud", units: 40, firstDaf: 2 },
      { id: "Taanit", label: "Taanit", he: "תענית", type: "talmud", units: 30, firstDaf: 2 },
      { id: "Megillah", label: "Megillah", he: "מגילה", type: "talmud", units: 32, firstDaf: 2 },
      { id: "Moed Katan", label: "Moed Katan", he: "מועד קטן", type: "talmud", units: 28, firstDaf: 2 },
      { id: "Chagigah", label: "Chagigah", he: "חגיגה", type: "talmud", units: 26, firstDaf: 2 },
    ] },
    { sub: "Séder Nashim", subHe: "", books: [
      { id: "Yevamot", label: "Yevamot", he: "יבמות", type: "talmud", units: 122, firstDaf: 2 },
      { id: "Ketubot", label: "Ketubot", he: "כתובות", type: "talmud", units: 112, firstDaf: 2 },
      { id: "Nedarim", label: "Nedarim", he: "נדרים", type: "talmud", units: 91, firstDaf: 2 },
      { id: "Nazir", label: "Nazir", he: "נזיר", type: "talmud", units: 66, firstDaf: 2 },
      { id: "Sotah", label: "Sotah", he: "סוטה", type: "talmud", units: 49, firstDaf: 2 },
      { id: "Gittin", label: "Gittin", he: "גיטין", type: "talmud", units: 90, firstDaf: 2 },
      { id: "Kiddushin", label: "Kiddushin", he: "קידושין", type: "talmud", units: 82, firstDaf: 2 },
    ] },
    { sub: "Séder Nezikin", subHe: "", books: [
      { id: "Bava Kamma", label: "Bava Kamma", he: "בבא קמא", type: "talmud", units: 119, firstDaf: 2 },
      { id: "Bava Metzia", label: "Bava Metzia", he: "בבא מציעא", type: "talmud", units: 118, firstDaf: 2 },
      { id: "Bava Batra", label: "Bava Batra", he: "בבא בתרא", type: "talmud", units: 176, firstDaf: 2 },
      { id: "Sanhedrin", label: "Sanhedrin", he: "סנהדרין", type: "talmud", units: 113, firstDaf: 2 },
      { id: "Makkot", label: "Makkot", he: "מכות", type: "talmud", units: 24, firstDaf: 2 },
      { id: "Shevuot", label: "Shevuot", he: "שבועות", type: "talmud", units: 49, firstDaf: 2 },
      { id: "Avodah Zarah", label: "Avodah Zarah", he: "עבודה זרה", type: "talmud", units: 76, firstDaf: 2 },
      { id: "Horayot", label: "Horayot", he: "הוריות", type: "talmud", units: 14, firstDaf: 2 },
    ] },
    { sub: "Séder Kodashim", subHe: "", books: [
      { id: "Zevachim", label: "Zevachim", he: "זבחים", type: "talmud", units: 120, firstDaf: 2 },
      { id: "Menachot", label: "Menachot", he: "מנחות", type: "talmud", units: 110, firstDaf: 2 },
      { id: "Chullin", label: "Chullin", he: "חולין", type: "talmud", units: 142, firstDaf: 2 },
      { id: "Bekhorot", label: "Bekhorot", he: "בכורות", type: "talmud", units: 60, firstDaf: 2 },
      { id: "Arakhin", label: "Arakhin", he: "ערכין", type: "talmud", units: 34, firstDaf: 2 },
      { id: "Temurah", label: "Temurah", he: "תמורה", type: "talmud", units: 34, firstDaf: 2 },
      { id: "Keritot", label: "Keritot", he: "כריתות", type: "talmud", units: 28, firstDaf: 2 },
      { id: "Meilah", label: "Meilah", he: "מעילה", type: "talmud", units: 22, firstDaf: 2 },
      { id: "Tamid", label: "Tamid", he: "תמיד", type: "talmud", units: 33, firstDaf: 2 },
    ] },
    { sub: "Séder Tahorot", subHe: "", books: [
      { id: "Niddah", label: "Niddah", he: "נדה", type: "talmud", units: 72, firstDaf: 2 },
    ] },
  ] },
  { id: "Midrash", he: "מִדְרָשׁ", es: "Midrash", subs: [
    { sub: null, subHe: "", books: [
      { id: "Bereshit Rabbah", label: "Bereshit Rabbah", he: "בראשית רבה", type: "chapters", units: 100 },
      { id: "Shemot Rabbah", label: "Shemot Rabbah", he: "שמות רבה", type: "chapters", units: 52 },
      { id: "Vayikra Rabbah", label: "Vayikra Rabbah", he: "ויקרא רבה", type: "chapters", units: 37 },
      { id: "Bamidbar Rabbah", label: "Bamidbar Rabbah", he: "במדבר רבה", type: "chapters", units: 23 },
      { id: "Devarim Rabbah", label: "Devarim Rabbah", he: "דברים רבה", type: "chapters", units: 17 },
      { id: "Shir HaShirim Rabbah", label: "Shir HaShirim Rabbah", he: "שיר השירים רבה", type: "chapters", units: 8 },
      { id: "Ruth Rabbah", label: "Ruth Rabbah", he: "רות רבה", type: "chapters", units: 9 },
      { id: "Esther Rabbah", label: "Esther Rabbah", he: "אסתר רבה", type: "chapters", units: 10 },
      { id: "Kohelet Rabbah", label: "Kohelet Rabbah", he: "קוהלת רבה", type: "chapters", units: 12 },
      { id: "Eikhah Rabbah", label: "Eikhah Rabbah", he: "איכה רבה", type: "chapters", units: 5 },
      { id: "Ruth Rabbah (Lerner)", label: "Ruth Rabbah (Lerner)", he: "רות רבה (לרנר)", type: "chapters", units: 8 },
      { id: "Ein Yaakov", label: "Ein Yaakov", he: "עין יעקב", type: "chapters", units: 44 },
      { id: "Midrash Mishlei", label: "Midrash Mishlei", he: "מדרש משלי", type: "chapters", units: 31 },
      { id: "Midrash Tanchuma", label: "Midrash Tanchuma", he: "מדרש תנחומא", type: "chapters", units: 54 },
      { id: "Midrash Tanchuma Buber", label: "Midrash Tanchuma Buber", he: "תנחומא בובר", type: "chapters", units: 59 },
      { id: "Midrash Tehillim", label: "Midrash Tehillim", he: "מדרש תהילים", type: "chapters", units: 150 },
      { id: "Pesikta DeRav Kahana", label: "Pesikta DeRav Kahana", he: "פסיקתא דרב כהנא", type: "chapters", units: 28 },
      { id: "Pesikta Rabbati", label: "Pesikta Rabbati", he: "פסיקתא רבתי", type: "chapters", units: 47 },
      { id: "Pirkei DeRabbi Eliezer", label: "Pirkei DeRabbi Eliezer", he: "פרקי דרבי אליעזר", type: "chapters", units: 54 },
      { id: "Tanna DeBei Eliyahu Rabbah", label: "Tanna DeBei Eliyahu Rabbah", he: "תנא דבי אליהו רבה", type: "chapters", units: 31 },
      { id: "Yalkut Shimoni on Torah", label: "Yalkut Shimoni on Torah", he: "ילקוט שמעוני על התורה", type: "chapters", units: 966 },
      { id: "Mekhilta DeRabbi Yishmael", label: "Mekhilta DeRabbi Yishmael", he: "מכילתא דרבי ישמעאל", type: "chapters", units: 9 },
      { id: "Sifra", label: "Sifra", he: "ספרא", type: "chapters", units: 278 },
      { id: "Sifrei Bamidbar", label: "Sifrei Bamidbar", he: "ספרי במדבר", type: "chapters", units: 161 },
      { id: "Sifrei Devarim", label: "Sifrei Devarim", he: "ספרי דברים", type: "chapters", units: 357 },
    ] },
  ] },
  { id: "Kabbalah", he: "קַבָּלָה", es: "Cabalá", subs: [
    { sub: null, subHe: "", books: [
      { id: "Sefer Yetzirah", label: "Sefer Yetzirah", he: "ספר יצירה", type: "chapters", units: 6 },
      { id: "Sefer HaBahir", label: "Sefer HaBahir", he: "ספר הבהיר", type: "chapters", units: 200 },
      { id: "Zohar", label: "Zohar", he: "ספר הזהר", type: "chapters", units: 55 },
      { id: "Zohar Chadash", label: "Zohar Chadash", he: "זוהר חדש", type: "chapters", units: 30 },
      { id: "Tikkunei Zohar", label: "Tikkunei Zohar", he: "תקוני הזהר", type: "chapters", units: 295 },
      { id: "Pri Etz Chaim", label: "Pri Etz Chaim", he: "פרי עץ חיים", type: "chapters", units: 34 },
      { id: "Sefer Etz Chaim", label: "Sefer Etz Chaim", he: "עץ חיים", type: "chapters", units: 50 },
      { id: "Sha'ar HaGilgulim", label: "Sha'ar HaGilgulim", he: "שער הגלגולים", type: "chapters", units: 41 },
      { id: "Reshit Chokhmah", label: "Reshit Chokhmah", he: "ראשית חכמה", type: "chapters", units: 33 },
      { id: "Shaar HaKavanot, Introduction", label: "Shaar HaKavanot, Introduction", he: "שער הכוונות הקדמה", type: "chapters", units: 4 },
      { id: "Shaar HaKavanot, Sermons on Tzitzit", label: "Shaar HaKavanot, Sermons on Tzitzit", he: "דרושי הציצית", type: "chapters", units: 2 },
      { id: "Shaar HaKavanot, Sermons on Tefillin", label: "Shaar HaKavanot, Sermons on Tefillin", he: "דרושי התפילין", type: "chapters", units: 6 },
      { id: "Shaar HaKavanot, Sermons on Intentions of the Shema Recitation", label: "Shaar HaKavanot, Sermons on Intentions of the Shema Recitation", he: "דרושי קריאת שמע", type: "chapters", units: 19 },
      { id: "Shaar HaKavanot, Sermons on the Standing Prayer", label: "Shaar HaKavanot, Sermons on the Standing Prayer", he: "דרושי העמידה", type: "chapters", units: 2 },
    ] },
  ] },
  { id: "Chasidut", he: "חֲסִידוּת", es: "Jasidut", subs: [
    { sub: null, subHe: "", books: [
      { id: "Kedushat Levi", label: "Kedushat Levi", he: "קדושת לוי", type: "chapters", units: 85 },
      { id: "Me'or Einayim", label: "Me'or Einayim", he: "מאור עינים", type: "chapters", units: 49 },
      { id: "Tzava'at HaRivash", label: "Tzava'at HaRivash", he: "צוואת הריב\"ש", type: "chapters", units: 143 },
      { id: "Likutei Halakhot", label: "Likutei Halakhot", he: "ליקוטי הלכות", type: "chapters", units: 146 },
      { id: "Likutei Moharan", label: "Likutei Moharan", he: "ליקוטי מוהר\"ן", type: "chapters", units: 286 },
      { id: "Tanya", label: "Tanya", he: "תניא", type: "chapters", units: 9 },
      { id: "Mei HaShiloach", label: "Mei HaShiloach", he: "מי השלוח", type: "chapters", units: 284 },
      { id: "Bnei Yissaschar", label: "Bnei Yissaschar", he: "בני יששכר", type: "chapters", units: 13 },
      { id: "Degel Machaneh Ephraim", label: "Degel Machaneh Ephraim", he: "דגל מחנה אפרים", type: "chapters", units: 84 },
      { id: "Keter Shem Tov", label: "Keter Shem Tov", he: "כתר שם טוב", type: "chapters", units: 2 },
      { id: "Sefat Emet", label: "Sefat Emet", he: "שפת אמת", type: "chapters", units: 68 },
      { id: "Shem MiShmuel", label: "Shem MiShmuel", he: "שם משמואל", type: "chapters", units: 68 },
    ] },
  ] },
];
