// Las 14 etapas del proceso luriánico: Ein Sof → Tikún
// Cada etapa define: texto, visual params, referencia de estudio, comportamiento de partículas.

export interface CosmologyStage {
  id: string;
  nameHe: string;
  nameEs: string;
  nameFa: string;
  quoteEs: string;
  quoteFa: string;
  sourceHe?: string;
  sourceEs?: string;
  studyRef?: string;
  // Visual
  bgColor: string;       // color de fondo CSS
  particleColor: string; // color hex de partículas
  particleBehavior: "sphere-expand" | "sphere-contract" | "sparse" | "beam" | "humanoid"
    | "clusters-tight" | "clusters-loose" | "explode" | "rain" | "trapped"
    | "tree" | "planes" | "spiral-up" | "tree-glow";
  particleIntensity: number; // 0-1, cuántas partículas visibles
}

export const COSMOLOGY_STAGES: CosmologyStage[] = [
  {
    id: "ein-sof",
    nameHe: "אֵין סוֹף",
    nameEs: "Ein Sof — Lo Infinito",
    nameFa: "اِین سوف — بی‌نهایت",
    quoteEs: "Antes de toda emanación, no existía ninguna distinción. No había mundos, sefirot, criaturas ni tiempo. Solo Ein Sof, la infinitud divina sin límite.",
    quoteFa: "پیش از هر فیضی، هیچ تمایزی وجود نداشت. نه جهانی، نه سِفیروتی، نه مخلوقی، نه زمانی. تنها اِین سوف — بی‌نهایت الهی.",
    sourceHe: "דַּע כִּי טֶרֶם שֶׁנֶּאֱצְלוּ הַנֶּאֱצָלִים...",
    sourceEs: "Etz Jaim, Shaar HaHakdamot 1",
    studyRef: "Sefer Etz Chaim 1",
    bgColor: "#fffef8",
    particleColor: "#fffef0",
    particleBehavior: "sphere-expand",
    particleIntensity: 1.0,
  },
  {
    id: "tzimtzum",
    nameHe: "צִמְצוּם",
    nameEs: "Tzimtzum — La Contracción",
    nameFa: "تزیمتزوم — انقباض",
    quoteEs: "Para permitir la existencia de seres finitos, Ein Sof realizó el Tzimtzum: un ocultamiento de Su luz. No abandonó un lugar — Su luz dejó de manifestarse plenamente.",
    quoteFa: "برای اینکه موجودات محدود وجود داشته باشند، اِین سوف تزیمتزوم کرد: پنهان‌شدنِ نور. او جایی را ترک نکرد — نورش دیگر به‌طور کامل تجلی نیافت.",
    sourceHe: "צִמְצֵם אֶת עַצְמוֹ בַּנְּקוּדָּה הָאֶמְצָעִית",
    sourceEs: "Etz Jaim, Shaar HaAkudim 1",
    studyRef: "Sefer Etz Chaim 1",
    bgColor: "#08060f",
    particleColor: "#e8d880",
    particleBehavior: "sphere-contract",
    particleIntensity: 0.6,
  },
  {
    id: "reshimo",
    nameHe: "רְשִׁימוּ",
    nameEs: "Reshimó — La Huella",
    nameFa: "رِشیمو — ردّ پا",
    quoteEs: "El vacío nunca estuvo vacío. Después del Tzimtzum quedó una impresión luminosa — el Reshimó. Esta huella contiene el potencial de toda la creación futura.",
    quoteFa: "فضای خالی هرگز خالی نبود. پس از تزیمتزوم، یک نشانهٔ نورانی باقی ماند — رِشیمو. این ردّ، پتانسیل تمام آفرینش آینده را در خود دارد.",
    sourceEs: "Etz Jaim, Shaar HaAkudim",
    studyRef: "Sefer Etz Chaim 1",
    bgColor: "#04020a",
    particleColor: "#c9a43e",
    particleBehavior: "sparse",
    particleIntensity: 0.2,
  },
  {
    id: "kav",
    nameHe: "קַו",
    nameEs: "Kav — El Rayo",
    nameFa: "قَو — پرتو",
    quoteEs: "Un único rayo de luz divina penetra el espacio vacío. El Kav introduce la primera medida, la primera dirección. A través de él se formarán todos los mundos.",
    quoteFa: "یک پرتو منفرد از نور الهی فضای خالی را می‌شکافد. قَو اولین اندازه، اولین جهت را می‌آورد. از طریق آن همهٔ جهان‌ها شکل می‌گیرند.",
    sourceEs: "Etz Jaim, Shaar HaHakdamot",
    studyRef: "Sefer Etz Chaim 1",
    bgColor: "#050310",
    particleColor: "#f0e060",
    particleBehavior: "beam",
    particleIntensity: 0.7,
  },
  {
    id: "adam-kadmon",
    nameHe: "אָדָם קַדְמוֹן",
    nameEs: "Adam Kadmón — El Hombre Primordial",
    nameFa: "آدام قادمون — انسان اولیه",
    quoteEs: "La primera configuración espiritual: Adam Kadmón. No es un ser humano — es la arquitectura arquetípica que contiene en potencia toda la creación. De él emanan las futuras sefirot.",
    quoteFa: "اولین پیکربندی روحانی: آدام قادمون. این یک انسان نیست — معماری کهن‌الگویی است که پتانسیل تمام آفرینش را در خود دارد.",
    sourceEs: "Etz Jaim, Shaar Adam Kadmon",
    studyRef: "Sefer Etz Chaim 1",
    bgColor: "#07051a",
    particleColor: "#d4c8ff",
    particleBehavior: "humanoid",
    particleIntensity: 0.85,
  },
  {
    id: "akudim",
    nameHe: "עֲקוּדִים",
    nameEs: "Akudim — Los Ligados",
    nameFa: "عَقودیم — بسته‌شدگان",
    quoteEs: "Las diez luces de las sefirot surgen dentro de un único recipiente. Todo integrado, todo unido. Es la etapa de armonía primera antes de la individualización.",
    quoteFa: "ده نور سِفیروت درون یک ظرف واحد پدید می‌آیند. همه یکپارچه، همه پیوسته. مرحلهٔ هماهنگی اولیه پیش از فردی‌سازی.",
    bgColor: "#080616",
    particleColor: "#a8d4ff",
    particleBehavior: "clusters-tight",
    particleIntensity: 0.9,
  },
  {
    id: "nekudim",
    nameHe: "נְקוּדִים",
    nameEs: "Nekudim — Los Puntos",
    nameFa: "نِقودیم — نقطه‌ها",
    quoteEs: "Las sefirot se separan. Cada una actúa de forma aislada. Din — el rigor — predomina sin el equilibrio del amor. El problema fundamental está a punto de manifestarse.",
    quoteFa: "سِفیروت جدا می‌شوند. هرکدام به‌تنهایی عمل می‌کند. دین — سختگیری — بدون تعادل عشق غالب می‌شود. مشکل اساسی در شرف وقوع است.",
    bgColor: "#0a0418",
    particleColor: "#8888cc",
    particleBehavior: "clusters-loose",
    particleIntensity: 0.75,
  },
  {
    id: "shevirat",
    nameHe: "שְׁבִירַת הַכֵּלִים",
    nameEs: "Shevirat ha-Kelim — La Ruptura de los Vasos",
    nameFa: "شِویرات هَکِلیم — شکست ظروف",
    quoteEs: "Los recipientes no pudieron contener la intensidad de la luz. Los vasos se rompieron. Aquí se origina la raíz metafísica de todo desorden, toda fragmentación, todo exilio.",
    quoteFa: "ظروف نتوانستند شدت نور را تحمل کنند. ظروف شکستند. اینجاست که ریشهٔ متافیزیکی هر بی‌نظمی، هر تکه‌تکه‌شدن، هر تبعیدی شکل می‌گیرد.",
    sourceHe: "שְׁבִירַת הַכֵּלִים — מְקוֹר הָרָע",
    sourceEs: "Etz Jaim, Shaar Shevirat HaKelim",
    studyRef: "Sefer Etz Chaim 1",
    bgColor: "#0f0808",
    particleColor: "#ff8844",
    particleBehavior: "explode",
    particleIntensity: 1.0,
  },
  {
    id: "nitzotzot",
    nameHe: "נִיצוֹצוֹת",
    nameEs: "Nitzotzot — Las Chispas",
    nameFa: "نیتزوتزوت — جرقه‌ها",
    quoteEs: "Las chispas de santidad cayeron al exilio, atrapadas entre los fragmentos. Toda la historia cósmica posterior consiste en liberar esas chispas y elevarlas.",
    quoteFa: "جرقه‌های قدسی به تبعید افتادند، در میان تکه‌ها محبوس شدند. تمام تاریخ کیهانی پس از آن در آزاد کردن این جرقه‌ها و بالا بردن آن‌هاست.",
    bgColor: "#040210",
    particleColor: "#ffd04a",
    particleBehavior: "rain",
    particleIntensity: 0.9,
  },
  {
    id: "kelipot",
    nameHe: "קְלִיפּוֹת",
    nameEs: "Kelipot — Las Cáscaras",
    nameFa: "قِلیپوت — پوسته‌ها",
    quoteEs: "Las chispas quedaron atrapadas dentro de estructuras oscuras llamadas Kelipot. El mundo aparece mezclado: bien y mal, verdad y ocultamiento, santidad y exilio.",
    quoteFa: "جرقه‌ها درون ساختارهای تاریک به نام قِلیپوت محبوس ماندند. جهان آمیخته است: خیر و شر، حقیقت و پنهان‌سازی، قداست و تبعید.",
    bgColor: "#020108",
    particleColor: "#886644",
    particleBehavior: "trapped",
    particleIntensity: 0.5,
  },
  {
    id: "atzilut",
    nameHe: "אֲצִילוּת",
    nameEs: "Atzilut — La Emanación",
    nameFa: "عَتزیلوت — فیض",
    quoteEs: "Comienza la rectificación. Las sefirot se reorganizan en los Partzufim — Arij Anpín, Abba, Imma, Zeir Anpín, Nukvá. La cooperación reemplaza la separación.",
    quoteFa: "تیقون آغاز می‌شود. سِفیروت به پارتزوفیم سازماندهی می‌شوند — عریج آنپین، اَبا، اِما، زِئیر آنپین، نوقوا. همکاری جای جدایی را می‌گیرد.",
    sourceEs: "Zohar, Idra Rabba",
    studyRef: "Zohar, Idra Rabba 1",
    bgColor: "#060418",
    particleColor: "#c9a43e",
    particleBehavior: "tree",
    particleIntensity: 1.0,
  },
  {
    id: "abya",
    nameHe: "אַבְיַ\"ע",
    nameEs: "AByA — Los Cuatro Mundos",
    nameFa: "اَبیَع — چهار عالم",
    quoteEs: "La energía divina desciende: Atzilut → Beriá → Yetzirá → Asiá. Nuestro mundo físico pertenece al nivel más bajo de Asiá, pero contiene chispas de los mundos superiores.",
    quoteFa: "نیروی الهی نزول می‌کند: عَتزیلوت → بِریاه → یِتزیراه → عَسیاه. جهان فیزیکی ما به پایین‌ترین سطح عَسیاه تعلق دارد، اما جرقه‌هایی از عوالم بالاتر در خود دارد.",
    bgColor: "#04030e",
    particleColor: "#8899cc",
    particleBehavior: "planes",
    particleIntensity: 0.85,
  },
  {
    id: "avodah",
    nameHe: "עֲבוֹדָה",
    nameEs: "Avodá — El Trabajo Humano",
    nameFa: "عَوودا — کار انسانی",
    quoteEs: "El ser humano fue creado para participar en la reparación. Mediante mitzvot, torá, tefila, teshuvá y actos de bondad — se elevan las chispas dispersas.",
    quoteFa: "انسان آفریده شد تا در تیقون شرکت کند. از طریق میتزووت، تورات، تِفیلا، تِشووا و اعمال نیکی — جرقه‌های پراکنده بالا می‌روند.",
    bgColor: "#050410",
    particleColor: "#88ccaa",
    particleBehavior: "spiral-up",
    particleIntensity: 0.8,
  },
  {
    id: "tikun",
    nameHe: "תִּיקּוּן",
    nameEs: "Tikún — La Rectificación",
    nameFa: "تیقون — ترمیم",
    quoteEs: "Las luces y los recipientes alcanzan equilibrio. Las chispas son reunidas. El Tikún no es volver al estado anterior — es alcanzar un nivel más elevado: una unidad que integra la diversidad.",
    quoteFa: "نورها و ظروف به تعادل می‌رسند. جرقه‌ها گردآوری می‌شوند. تیقون بازگشت به حالت قبل نیست — رسیدن به سطحی والاتر است: وحدتی که تنوع را در خود می‌گنجاند.",
    sourceHe: "תִּיקּוּן — יַחַד שֶׁמְּשַׁלֵּב אֶת הָרִבּוּי",
    sourceEs: "Ramjal, Daat Tevunot",
    studyRef: "Sefer Etz Chaim 1",
    bgColor: "#fffbee",
    particleColor: "#ffe88a",
    particleBehavior: "tree-glow",
    particleIntensity: 1.0,
  },
];
