// Galería de gematrías sagradas — los números recurrentes del estudio cabalístico.
// Cada entrada: el número, las palabras que comparten ese valor, y sus
// asociaciones (sefirot, Nombres, estructuras de la creación).

export interface Gematria {
  num: number;
  he: string;            // palabra(s) hebrea(s) principal(es), separadas por ·
  titulo: string;        // título español (canónico)
  tituloFa: string;
  tituloEn?: string;     // inglés — lo llena el Sofer por fases ([[i18n-audit]])
  sig: string;           // una línea de significado (español)
  sigFa: string;
  sigEn?: string;        // inglés — lo llena el Sofer por fases
  asociaciones: string[];   // viñetas (español)
  asociacionesFa: string[];
  asociacionesEn?: string[]; // inglés — lo llena el Sofer por fases
  color: string;
  mystery?: string;         // slug de misterio dedicado (ej. "137"), si lo tiene
}

export const GEMATRIAS: Gematria[] = [
  {
    num: 13, he: "אֶחָד · אַהֲבָה", titulo: "Unidad y Amor", tituloFa: "یگانگی و عشق",
    sig: "Ejad (Uno) y Ahavá (Amor) comparten el mismo valor: la unidad de Dios es el amor.",
    sigFa: "اِچاد (یک) و اَهاوا (عشق) یک ارزش دارند: یگانگیِ خدا همان عشق است.",
    asociaciones: ["אֶחָד (Ejad, «Uno») = 13", "אַהֲבָה (Ahavá, «Amor») = 13", "Los 13 atributos de misericordia"],
    asociacionesFa: ["اِچاد («یک») = ۱۳", "اَهاوا («عشق») = ۱۳", "سیزده صفتِ رحمت"],
    color: "#e0a850",
  },
  {
    num: 18, he: "חַי", titulo: "Vida", tituloFa: "زندگی",
    sig: "Jai («vivo») — el número de la vida, presente en bendiciones y donaciones.",
    sigFa: "خَی («زنده») — عددِ زندگی، در برکات و بخشش‌ها.",
    asociaciones: ["חַי (Jai, «vivo») = 18", "Doblado (36) = los 36 justos ocultos"],
    asociacionesFa: ["خَی («زنده») = ۱۸", "دوبرابر (۳۶) = سی‌وشش صدّیقِ پنهان"],
    color: "#5a9a6a",
  },
  {
    num: 26, he: "יהוה", titulo: "El Nombre", tituloFa: "نامِ خدا",
    sig: "El Tetragrámaton (YHVH), el Nombre divino más sagrado: Yud(10) Hei(5) Vav(6) Hei(5).",
    sigFa: "تتراگرامتون (یهوه)، مقدّس‌ترین نامِ الهی: یود(۱۰) هی(۵) واو(۶) هی(۵).",
    asociaciones: ["יהוה = 26", "Ejad(13) + Ahavá(13) = 26", "La estructura del Árbol de la Vida"],
    asociacionesFa: ["یهوه = ۲۶", "اِچاد(۱۳) + اَهاوا(۱۳) = ۲۶", "ساختارِ درختِ زندگی"],
    color: "#c9a43e",
  },
  {
    num: 32, he: "לֵב", titulo: "Los 32 senderos", tituloFa: "سی‌ودو مسیر",
    sig: "Lev («corazón») = 32 — los 32 senderos de sabiduría del Sefer Yetzirá.",
    sigFa: "لِو («قلب») = ۳۲ — سی‌ودو مسیرِ حکمت در سِفِر یِتزیرا.",
    asociaciones: ["10 sefirot + 22 letras = 32", "לֵב (Lev, «corazón») = 32", "Comienza y termina la Torá (Bet…Lamed = Lev)"],
    asociacionesFa: ["۱۰ سِفیرا + ۲۲ حرف = ۳۲", "لِو («قلب») = ۳۲", "آغاز و انجامِ تورات (بِت…لَمِد)"],
    color: "#cc5555",
  },
  {
    num: 42, he: "מ\"ב", titulo: "El Nombre de 42", tituloFa: "نامِ چهل‌ودو",
    sig: "El Nombre de 42 letras — la oración Ana BeKoaj, la Cabalá contemplativa de la ascensión.",
    sigFa: "نامِ چهل‌ودو حرفی — دعای اَنا بِکوآح، کابالای تأمّلیِ عروج.",
    asociaciones: ["El Nombre de 42 letras", "Aná BeKoaj (7 versos × 6 palabras)", "Los 42 viajes del desierto"],
    asociacionesFa: ["نامِ چهل‌ودو حرفی", "اَنا بِکوآح (۷ بند × ۶ واژه)", "چهل‌ودو سفرِ بیابان"],
    color: "#7a8ad0",
  },
  {
    num: 45, he: "אָדָם · מ\"ה", titulo: "Adam y el Tikún", tituloFa: "آدام و تیقون",
    sig: "Adam = 45 = Mah, la expansión del Nombre asociada al mundo de la rectificación.",
    sigFa: "آدام = ۴۵ = مَه، گسترشِ نام مرتبط با عالمِ تیقون.",
    asociaciones: ["אָדָם (Adam) = 45", "מ\"ה (Mah) — el milui del Tikún", "El mundo de Yetzirá / Zeir Anpín"],
    asociacionesFa: ["آدام = ۴۵", "مَه — میلویِ تیقون", "عالمِ یِتزیراه / زِئیر آنپین"],
    color: "#b89a4e",
  },
  {
    num: 49, he: "מ\"ט", titulo: "Las 49 puertas", tituloFa: "چهل‌ونه دروازه",
    sig: "7 × 7 — los 49 días del Ómer, los 49 niveles de comprensión y refinamiento.",
    sigFa: "۷ × ۷ — چهل‌ونه روزِ عُمِر، چهل‌ونه سطحِ فهم و پالایش.",
    asociaciones: ["7 × 7 = 49", "Los 49 días del Ómer", "Las 49 puertas de Biná (la 50ª es oculta)"],
    asociacionesFa: ["۷ × ۷ = ۴۹", "چهل‌ونه روزِ عُمِر", "چهل‌ونه دروازهٔ بینا (پنجاهمی پنهان است)"],
    color: "#6a9ac0",
  },
  {
    num: 50, he: "נ", titulo: "Los 50 portales", tituloFa: "پنجاه دروازه",
    sig: "Los 50 portales de Biná y el Jubileo (Yovel) — la libertad y el entendimiento supremo.",
    sigFa: "پنجاه دروازهٔ بینا و یوبیل (یووِل) — آزادی و فهمِ والا.",
    asociaciones: ["50 portales de Biná", "El Yovel (Jubileo)", "La letra Nun (נ) = 50"],
    asociacionesFa: ["پنجاه دروازهٔ بینا", "یووِل (یوبیل)", "حرفِ نون = ۵۰"],
    color: "#8866cc",
  },
  {
    num: 52, he: "בֶּן · ב\"ן", titulo: "El Hijo, Maljut", tituloFa: "پسر، مَلخوت",
    sig: "Ben («hijo») = 52 = Ban, la expansión del Nombre asociada a Maljut, el mundo manifestado.",
    sigFa: "بِن («پسر») = ۵۲ = بَن، گسترشِ نام مرتبط با مَلخوت، عالمِ آشکار.",
    asociaciones: ["בֶּן (Ben, «hijo») = 52", "ב\"ן (Ban) — el milui de Maljut", "El mundo de Asiá / la Nukva"],
    asociacionesFa: ["بِن («پسر») = ۵۲", "بَن — میلویِ مَلخوت", "عالمِ عَسیاه / نوقوا"],
    color: "#a06a8e",
  },
  {
    num: 63, he: "ס\"ג", titulo: "Biná, Sag", tituloFa: "بینا، سَگ",
    sig: "Sag — la expansión del Nombre relacionada con Biná, el entendimiento superior.",
    sigFa: "سَگ — گسترشِ نام مرتبط با بینا، فهمِ والا.",
    asociaciones: ["ס\"ג (Sag) = 63", "El mundo de Beriá", "La Ima superna (la Madre)"],
    asociacionesFa: ["سَگ = ۶۳", "عالمِ بِریاه", "ایمای علیا (مادر)"],
    color: "#6688cc",
  },
  {
    num: 70, he: "סוֹד · יַיִן", titulo: "Las 70 caras", tituloFa: "هفتاد چهره",
    sig: "Sod («secreto») = Yayin («vino») = 70 — «entró el vino, salió el secreto». Las 70 caras de la Torá.",
    sigFa: "سود («راز») = یَیین («شراب») = ۷۰ — «شراب درآمد، راز برآمد». هفتاد چهرهٔ تورات.",
    asociaciones: ["סוֹד (Sod, «secreto») = 70", "יַיִן (Yayin, «vino») = 70", "Las 70 naciones, los 70 ancianos, las 70 facetas"],
    asociacionesFa: ["سود («راز») = ۷۰", "یَیین («شراب») = ۷۰", "هفتاد ملت، هفتاد پیر، هفتاد چهره"],
    color: "#9a3a3a",
  },
  {
    num: 72, he: "ע\"ב · חֶסֶד", titulo: "El Nombre de 72", tituloFa: "نامِ هفتادودو",
    sig: "AB = 72 = Jésed — el Shem HaMeforash de 72 tripletes, nacido de la partición del mar.",
    sigFa: "عَب = ۷۲ = خِسِد — شِم هَمِفوراش از هفتادودو سه‌گانه، زادهٔ شکافتنِ دریا.",
    asociaciones: ["ע\"ב (AB) = 72", "חֶסֶד (Jésed) = 72", "Los 72 Nombres (Éxodo 14:19-21) = 216 letras"],
    asociacionesFa: ["عَب = ۷۲", "خِسِد = ۷۲", "هفتادودو نام (خروج ۱۴) = ۲۱۶ حرف"],
    color: "#d4a838",
  },
  {
    num: 91, he: "אָמֵן", titulo: "La unificación", tituloFa: "یگانه‌سازی",
    sig: "26 (YHVH) + 65 (Adonai) = 91 = Amén — la unión del Nombre oculto y el revelado.",
    sigFa: "۲۶ (یهوه) + ۶۵ (اَدونای) = ۹۱ = آمین — پیوندِ نامِ پنهان و آشکار.",
    asociaciones: ["יהוה (26) + אֲדֹנָי (65) = 91", "אָמֵן (Amén) = 91", "Decir «Amén» une ambos Nombres"],
    asociacionesFa: ["یهوه (۲۶) + اَدونای (۶۵) = ۹۱", "آمین = ۹۱", "گفتنِ «آمین» دو نام را می‌پیوندد"],
    color: "#c9a43e",
  },
  {
    num: 112, he: "יַבֹּק", titulo: "Yabok, las kavanot", tituloFa: "یَبوق",
    sig: "Yabok = 112 — donde Jacob luchó con el ángel; las kavanot del Arí: YHVH + Adonai + Ehyeh.",
    sigFa: "یَبوق = ۱۱۲ — جایی که یعقوب با فرشته کشتی گرفت؛ کاوانوتِ آری.",
    asociaciones: ["יַבֹּק (Yabok) = 112", "יהוה(26)+אדני(65)+אהיה(21) = 112", "Las kavanot de unificación del Arí"],
    asociacionesFa: ["یَبوق = ۱۱۲", "یهوه+اَدونای+اِهیه = ۱۱۲", "کاوانوتِ یگانه‌سازیِ آری"],
    color: "#7a8ad0",
  },
  {
    num: 137, he: "קַבָּלָה", titulo: "El acertijo de la creación", tituloFa: "معمای آفرینش",
    sig: "Kabalah («recibir») = 137. Y la constante de estructura fina α ≈ 1/137 — donde la Cabalá toca la física (Rav Ginsburgh, «137: The Riddle of Creation»).",
    sigFa: "قبالا («دریافت») = ۱۳۷. و ثابتِ ساختارِ ریز α ≈ ۱/۱۳۷ — جایی که کابالا به فیزیک می‌رسد (راو گینزبورگ).",
    asociaciones: [
      "קַבָּלָה (Kabbalah, «recibir») = 137",
      "La constante de estructura fina: α ≈ 1/137 (la física)",
      "Tres vivieron 137 años: Ishmael, Leví, Amram",
      "אוֹפָן (Ofan, «rueda» de Yejezkel) = 137",
      "מוֹצָא (Motza, «origen, fuente») = 137",
      "תֹּהוּ (Tohu, «caos») = 411 = 3 × 137",
      "יֵשׁ מֵאַיִן («algo de la nada») = 411 = 3 × 137",
      "Génesis 1 tiene exactamente 137 palabras de 3 letras",
    ],
    asociacionesFa: [
      "قبالا («دریافت») = ۱۳۷",
      "ثابتِ ساختارِ ریز: α ≈ ۱/۱۳۷ (فیزیک)",
      "سه تن ۱۳۷ سال زیستند: اسماعیل، لاوی، عَمرام",
      "اوֹفان («چرخِ» یحزقیل) = ۱۳۷",
      "موצا («سرچشمه») = ۱۳۷",
      "توهو («آشوب») = ۴۱۱ = ۳ × ۱۳۷",
      "یِش مِاَین («هستی از نیستی») = ۴۱۱ = ۳ × ۱۳۷",
      "پیدایش ۱ دقیقاً ۱۳۷ واژهٔ سه‌حرفی دارد",
    ],
    color: "#9a6a8e",
    mystery: "137",
  },
  {
    num: 248, he: "אַבְרָהָם", titulo: "Avraham y los 248", tituloFa: "اَبراهام",
    sig: "Avraham = 248 — los 248 órganos del cuerpo y los 248 mandamientos positivos.",
    sigFa: "اَبراهام = ۲۴۸ — دویست‌وچهل‌وهشت اندامِ بدن و میتزووتِ مثبت.",
    asociaciones: ["אַבְרָהָם (Avraham) = 248", "248 miembros espirituales del cuerpo", "248 mitzvot positivas"],
    asociacionesFa: ["اَبراهام = ۲۴۸", "دویست‌وچهل‌وهشت اندامِ روحانی", "میتزووتِ مثبت"],
    color: "#5a9a6a",
  },
  {
    num: 613, he: "תרי\"ג", titulo: "Las 613 mitzvot", tituloFa: "ششصدوسیزده میتزوا",
    sig: "El total de los mandamientos de la Torá: 248 positivos + 365 negativos.",
    sigFa: "مجموعِ احکامِ تورات: ۲۴۸ مثبت + ۳۶۵ منفی.",
    asociaciones: ["248 positivas + 365 negativas = 613", "365 = días del año / preceptos negativos", "תרי\"ג (Taryag)"],
    asociacionesFa: ["۲۴۸ مثبت + ۳۶۵ منفی = ۶۱۳", "۳۶۵ = روزهای سال", "تَریَگ"],
    color: "#c9a43e",
  },
  {
    num: 620, he: "כֶּתֶר", titulo: "Kéter, la Corona", tituloFa: "کِتِر، تاج",
    sig: "Kéter («corona») = 620 — la sefirá suprema; las 613 mitzvot más los 7 preceptos rabínicos.",
    sigFa: "کِتِر («تاج») = ۶۲۰ — سِفیرای والا؛ ۶۱۳ میتزوا به‌علاوهٔ هفت حکمِ ربانی.",
    asociaciones: ["כֶּתֶר (Kéter) = 620", "613 mitzvot + 7 preceptos = 620", "La corona suprema, sobre el intelecto"],
    asociacionesFa: ["کِتِر = ۶۲۰", "۶۱۳ + ۷ = ۶۲۰", "تاجِ والا، فراتر از عقل"],
    color: "#f0d878",
  },
  {
    num: 86, he: "אֱלֹהִים · הַטֶּבַע", titulo: "Dios y la Naturaleza", tituloFa: "خدا و طبیعت",
    sig: "Elohim = HaTeva («la naturaleza») = 86 — el Nombre que crea es la naturaleza misma (Ginsburgh).",
    sigFa: "اِلوهیم = هَطِبَع («طبیعت») = ۸۶ — نامی که می‌آفریند، خودِ طبیعت است (گینزبورگ).",
    asociaciones: [
      "אֱלֹהִים (Elohim) = 86",
      "הַטֶּבַע (HaTeva, «la naturaleza») = 86",
      "Elohim es el Nombre del juicio y del orden natural",
      "כּוֹס (Kos, «copa» de bendición) = 86",
    ],
    asociacionesFa: [
      "اِلوهیم = ۸۶",
      "هَطِبَع («طبیعت») = ۸۶",
      "اِلوهیم نامِ داوری و نظمِ طبیعت است",
      "کوס («جامِ» برکت) = ۸۶",
    ],
    color: "#5a9a6a",
  },
  {
    num: 358, he: "מָשִׁיחַ · נָחָשׁ", titulo: "Mashíaj y la serpiente", tituloFa: "ماشیَح و مار",
    sig: "Mashíaj = Najash («serpiente») = 358 — el redentor rectifica exactamente lo que la serpiente corrompió.",
    sigFa: "ماشیَح = ناخاش («مار») = ۳۵۸ — رهاننده دقیقاً همان را تیقون می‌کند که مار فاسد کرد.",
    asociaciones: [
      "מָשִׁיחַ (Mashíaj) = 358",
      "נָחָשׁ (Najash, «serpiente») = 358",
      "El Mashíaj eleva la caída del Edén (Dos Filos)",
    ],
    asociacionesFa: [
      "ماشیَح = ۳۵۸",
      "ناخاش («مار») = ۳۵۸",
      "ماشیَح سقوطِ عَدَن را برمی‌کشد (دو لبه)",
    ],
    color: "#9a3a3a",
  },
  {
    num: 314, he: "שַׁדַּי · מטטרון", titulo: "Shaddai y Metatrón", tituloFa: "شَدّای و مِتاترون",
    sig: "Shaddai = Metatrón = 314 — el Nombre del límite y el ángel del Trono comparten valor.",
    sigFa: "شَدّای = مِتاترون = ۳۱۴ — نامِ مرز و فرشتهٔ تخت یک ارزش دارند.",
    asociaciones: [
      "שַׁדַּי (Shaddai) = 314",
      "מטטרון (Metatrón, el ángel del Trono) = 314",
      "Shaddai: «el que dijo a su mundo: ¡basta!» (Jaguigá 12a)",
    ],
    asociacionesFa: [
      "شَدّای = ۳۱۴",
      "مِتاترون (فرشتهٔ تخت) = ۳۱۴",
      "شَدّای: «آن‌که به جهانش گفت: بس!» (حگیگا ۱۲a)",
    ],
    color: "#7a8ad0",
  },
  {
    num: 541, he: "יִשְׂרָאֵל", titulo: "Israel", tituloFa: "اسرائیل",
    sig: "Israel = 541 — el nombre que Jacob recibió tras luchar con el ángel (Gn 32:29).",
    sigFa: "ایسرائل = ۵۴۱ — نامی که یعقوب پس از کشتی با فرشته یافت (پیدایش ۳۲).",
    asociaciones: [
      "יִשְׂרָאֵל (Israel) = 541",
      "«Has luchado con Dios y con hombres y has vencido» (Gn 32:29)",
      "Israel contiene las iniciales de los Patriarcas y Matriarcas",
    ],
    asociacionesFa: [
      "ایسرائل = ۵۴۱",
      "«با خدا و انسان‌ها کشتی گرفتی و پیروز شدی» (پیدایش ۳۲)",
      "ایسرائل دربردارندهٔ سرحروفِ پدران و مادرانِ قوم است",
    ],
    color: "#6a9ac0",
  },
  {
    num: 611, he: "תּוֹרָה", titulo: "La Torá recibida", tituloFa: "توراتِ دریافت‌شده",
    sig: "Torá = 611 — las mitzvot que recibimos por boca de Moshé; las otras dos (Yo soy / No tendrás) las oyó Israel de Dios directo.",
    sigFa: "تورات = ۶۱۱ — احکامی که از زبانِ موسی دریافت کردیم؛ دو فرمانِ نخست را قوم مستقیم از خدا شنید.",
    asociaciones: [
      "תּוֹרָה (Torá) = 611",
      "611 + 2 (los dos primeros mandamientos oídos directo) = 613",
      "«Torá nos ordenó Moshé» (Dt 33:4) — Makot 23b-24a",
    ],
    asociacionesFa: [
      "تورات = ۶۱۱",
      "۶۱۱ + ۲ (دو فرمانِ نخست که مستقیم شنیده شد) = ۶۱۳",
      "«تورات را موسی به ما فرمان داد» (تثنیه ۳۳) — مَکوت ۲۴a",
    ],
    color: "#c9a43e",
  },
  {
    num: 207, he: "אוֹר · רָז", titulo: "La luz y el secreto", tituloFa: "نور و راز",
    sig: "Or («luz») = Raz («secreto») = Ein Sof = 207 — la luz oculta es el secreto del Infinito (Ginsburgh).",
    sigFa: "اور («نور») = راز = اِین سوف = ۲۰۷ — نورِ پنهان، رازِ بی‌نهایت است (گینزبورگ).",
    asociaciones: [
      "אוֹר (Or, «luz») = 207",
      "רָז (Raz, «secreto») = 207",
      "אֵין סוֹף (Ein Sof, «el Infinito») = 207",
      "Revelar el secreto (raz) es revelar la luz (or)",
    ],
    asociacionesFa: [
      "اور («نور») = ۲۰۷",
      "راز = ۲۰۷",
      "اِین سوف («بی‌نهایت») = ۲۰۷",
      "آشکار کردنِ راز، آشکار کردنِ نور است",
    ],
    color: "#f0d878",
  },
  {
    num: 111, he: "אָלֶף · פֶּלֶא", titulo: "El Álef y la maravilla", tituloFa: "اَلِف و شگفتی",
    sig: "Álef deletreada (אלף) = Pele («maravilla») = 111 — la primera letra es la maravilla oculta del Uno.",
    sigFa: "اَلِف به‌حروف (אלף) = پِلِه («شگفتی») = ۱۱۱ — نخستین حرف، شگفتیِ پنهانِ یگانه است.",
    asociaciones: [
      "אָלֶף (Álef, deletreada א-ל-ף) = 111",
      "פֶּלֶא (Pele, «maravilla») = 111",
      "Álef y Pele tienen las mismas letras (anagrama)",
      "111 = 3 × 37; el Álef vale 1 y mil (élef) a la vez",
    ],
    asociacionesFa: [
      "اَلِف (به‌حروف א-ל-ף) = ۱۱۱",
      "پِلِه («شگفتی») = ۱۱۱",
      "اَلِف و پِلِه هم‌حرف‌اند (واروخوانی)",
      "۱۱۱ = ۳ × ۳۷؛ اَلِف هم‌زمان یک و هزار (اِلِف) است",
    ],
    color: "#d4a838",
  },
  {
    num: 216, he: "גְּבוּרָה · אַרְיֵה", titulo: "Guevurá y el león", tituloFa: "گِوورا و شیر",
    sig: "Guevurá = Aryé («león») = 216 — el rigor ruge como león; las 216 letras de los 72 Nombres.",
    sigFa: "گِوورا = اَریه («شیر») = ۲۱۶ — سخت‌گیری چون شیر می‌غرّد؛ ۲۱۶ حرفِ هفتادودو نام.",
    asociaciones: [
      "גְּבוּרָה (Guevurá, «rigor/fuerza») = 216",
      "אַרְיֵה (Aryé, «león») = 216",
      "72 Nombres × 3 letras = 216 letras (Éx 14:19-21)",
      "216 = 6³ — el cubo del seis",
    ],
    asociacionesFa: [
      "گِوورا («سخت‌گیری») = ۲۱۶",
      "اَریه («شیر») = ۲۱۶",
      "هفتادودو نام × ۳ حرف = ۲۱۶ حرف (خروج ۱۴)",
      "۲۱۶ = ۶³ — مکعبِ شش",
    ],
    color: "#cc5555",
  },
  {
    num: 232, he: "ע\"ב ס\"ג מ\"ה ב\"ן", titulo: "Las cuatro expansiones", tituloFa: "چهار گسترش",
    sig: "72 + 63 + 45 + 52 = 232 — la suma de los cuatro miluim del Nombre YHVH, los cuatro mundos.",
    sigFa: "۷۲ + ۶۳ + ۴۵ + ۵۲ = ۲۳۲ — مجموعِ چهار میلویِ نامِ یهوه، چهار عالم.",
    asociaciones: [
      "AB(72) + Sag(63) + Mah(45) + Ban(52) = 232",
      "Las cuatro expansiones de Havayá = los 4 mundos (Atzilut, Beriá, Yetzirá, Asiá)",
      "232 = 8 × 29; abarca toda la estructura del Nombre",
    ],
    asociacionesFa: [
      "عَب(۷۲) + سَگ(۶۳) + مَه(۴۵) + بَن(۵۲) = ۲۳۲",
      "چهار گسترشِ هَوایا = چهار عالم (آتزیلوت، بِریاه، یِتزیراه، عَسیاه)",
      "۲۳۲ = ۸ × ۲۹؛ تمامِ ساختارِ نام را دربر می‌گیرد",
    ],
    color: "#c9a43e",
  },
  {
    num: 65, he: "אֲדֹנָי · הֵיכָל", titulo: "Adonai y el palacio", tituloFa: "اَدونای و معبد",
    sig: "Adonai = Heijal («palacio/templo») = Halel = 65 — el Nombre revelado es el palacio donde se alaba a Dios.",
    sigFa: "اَدونای = هِیخال («معبد») = هَلِل = ۶۵ — نامِ آشکار، معبدی است که در آن خدا را می‌ستایند.",
    asociaciones: [
      "אֲדֹנָי (Adonai, «mi Señor») = 65",
      "הֵיכָל (Heijal, «palacio, santuario») = 65",
      "הַלֵּל (Halel, «alabanza») = 65",
      "Adonai = el Nombre revelado, complemento de YHVH",
    ],
    asociacionesFa: [
      "اَدونای («پروردگارِ من») = ۶۵",
      "هِیخال («معبد، حرم») = ۶۵",
      "هَلِل («ستایش») = ۶۵",
      "اَدونای = نامِ آشکار، مکمّلِ یهوه",
    ],
    color: "#a06a8e",
  },
  {
    num: 543, he: "אֶהְיֶה אֲשֶׁר אֶהְיֶה", titulo: "«Seré el que seré»", tituloFa: "«خواهم بود آنکه خواهم بود»",
    sig: "Ehyé Asher Ehyé = 543 — la respuesta de Dios a Moshé en la zarza (Éx 3:14): el Nombre del ser puro.",
    sigFa: "اِهیه اَشِر اِهیه = ۵۴۳ — پاسخِ خدا به موسی در بوته (خروج ۳): نامِ هستیِ ناب.",
    asociaciones: [
      "אֶהְיֶה אֲשֶׁר אֶהְיֶה (Ehyé Asher Ehyé) = 543",
      "Cada אֶהְיֶה (Ehyé) = 21; el Nombre de Kéter",
      "Éxodo 3:14 — el Nombre del futuro, «el que será»",
    ],
    asociacionesFa: [
      "اِهیه اَشِر اِهیه = ۵۴۳",
      "هر اِهیه = ۲۱؛ نامِ کِتِر",
      "خروج ۳ — نامِ آینده، «آنکه خواهد بود»",
    ],
    color: "#b89a4e",
  },
  {
    num: 1820, he: "יהוה ×1820", titulo: "El Nombre en la Torá", tituloFa: "نام در تورات",
    sig: "1820 = las veces que aparece el Nombre YHVH en la Torá = 26 × 70 — el Nombre (26) por las 70 caras.",
    sigFa: "۱۸۲۰ = شمارِ ظهورِ نامِ یهوه در تورات = ۲۶ × ۷۰ — نام (۲۶) ضرب در هفتاد چهره.",
    asociaciones: [
      "El Nombre יהוה aparece 1820 veces en la Torá",
      "1820 = 26 (YHVH) × 70 (las 70 facetas / naciones)",
      "Es un conteo de apariciones, no un valor de letras",
    ],
    asociacionesFa: [
      "نامِ یهوه ۱۸۲۰ بار در تورات می‌آید",
      "۱۸۲۰ = ۲۶ (یهوه) × ۷۰ (هفتاد چهره / ملت)",
      "این شمارشِ ظهور است، نه ارزشِ حروف",
    ],
    color: "#d4a838",
  },
  {
    num: 401, he: "אֵת", titulo: "Del Álef al Tav", tituloFa: "از اَلِف تا تاو",
    sig: "Et (אֵת) = 401 — Álef(1) + Tav(400): de la primera a la última letra, la totalidad del alefbet.",
    sigFa: "اِت (אֵת) = ۴۰۱ — اَلِف(۱) + تاو(۴۰۰): از نخستین تا واپسین حرف، تمامیِ الفبا.",
    asociaciones: [
      "אֵת (Et) = 401 = Álef(1) + Tav(400)",
      "El segundo «et» de Génesis 1:1 abarca cielo y tierra enteros",
      "Contiene «del álef al tav»: toda la Torá y la creación",
    ],
    asociacionesFa: [
      "اِت = ۴۰۱ = اَلِف(۱) + تاو(۴۰۰)",
      "«اِت»ِ دومِ پیدایش ۱:۱ آسمان و زمین را به‌تمامی دربر می‌گیرد",
      "«از اَلِف تا تاو»: تمامِ تورات و آفرینش",
    ],
    color: "#8866cc",
  },
  {
    num: 240, he: "עֲמָלֵק · סָפֵק", titulo: "Amalek y la duda", tituloFa: "عَمالِق و تردید",
    sig: "Amalek = Safek («duda») = 240 — el enemigo interior es la duda que enfría la fe (Ginsburgh).",
    sigFa: "عَمالِق = سَفِک («تردید») = ۲۴۰ — دشمنِ درونی، همان تردیدی است که ایمان را سرد می‌کند (گینزبورگ).",
    asociaciones: [
      "עֲמָלֵק (Amalek) = 240",
      "סָפֵק (Safek, «duda») = 240",
      "Amalek «enfrió» a Israel en el camino (Dt 25:18 — «karja»)",
      "Borrar a Amalek = disolver la duda",
    ],
    asociacionesFa: [
      "عَمالِق = ۲۴۰",
      "سَفِک («تردید») = ۲۴۰",
      "عَمالِق در راه قوم را «سرد» کرد (تثنیه ۲۵)",
      "محوِ عَمالِق = زدودنِ تردید",
    ],
    color: "#9a3a3a",
  },
  {
    num: 169, he: "13²", titulo: "Trece al cuadrado", tituloFa: "سیزده به توان دو",
    sig: "169 = 13² — Ejad (Uno) y Ahavá (Amor), ambos 13, elevados al cuadrado: la unidad multiplicada por sí misma.",
    sigFa: "۱۶۹ = ۱۳² — اِچاد (یک) و اَهاوا (عشق)، هر دو ۱۳، به توانِ دو: یگانگی در خودش ضرب‌شده.",
    asociaciones: [
      "13 × 13 = 169",
      "13 = אֶחָד (Ejad, «Uno») = אַהֲבָה (Ahavá, «Amor»)",
      "El cuadrado de la unidad y del amor",
    ],
    asociacionesFa: [
      "۱۳ × ۱۳ = ۱۶۹",
      "۱۳ = اِچاد («یک») = اَهاوا («عشق»)",
      "مربعِ یگانگی و عشق",
    ],
    color: "#e0a850",
  },
  {
    num: 90, he: "מֶלֶךְ · מַיִם", titulo: "El rey y el agua", tituloFa: "پادشاه و آب",
    sig: "Melej («rey») = Mayim («agua») = 90 — la realeza fluye y se derrama como agua sobre el reino.",
    sigFa: "مِلِخ («پادشاه») = مَیِم («آب») = ۹۰ — پادشاهی چون آب بر قلمرو جاری و افشانده می‌شود.",
    asociaciones: [
      "מֶלֶךְ (Melej, «rey») = 90",
      "מַיִם (Mayim, «agua») = 90",
      "La letra Tzadi final (ץ) = 90; el «tzadik» justo",
    ],
    asociacionesFa: [
      "مِلِخ («پادشاه») = ۹۰",
      "مَیِم («آب») = ۹۰",
      "حرفِ تزادیِ پایانی (ץ) = ۹۰؛ «تزادیک»ِ صدّیق",
    ],
    color: "#6688cc",
  },
  {
    num: 121, he: "11²", titulo: "Once al cuadrado", tituloFa: "یازده به توان دو",
    sig: "121 = 11² — el once, número de los inciensos del Templo y de las sefirot contando Daat.",
    sigFa: "۱۲۱ = ۱۱² — یازده، عددِ بخورهای معبد و سِفیراها با احتسابِ دَعَت.",
    asociaciones: [
      "11 × 11 = 121",
      "11 especias del incienso del Templo (Keritot 6a)",
      "10 sefirot + Daat (la oculta) = 11",
    ],
    asociacionesFa: [
      "۱۱ × ۱۱ = ۱۲۱",
      "یازده گیاهِ بخورِ معبد (کِریتوت ۶a)",
      "ده سِفیرا + دَعَت (پنهان) = یازده",
    ],
    color: "#7a8ad0",
  },
  {
    num: 376, he: "שָׁלוֹם · עֵשָׂו", titulo: "La paz y Esav", tituloFa: "صلح و عِساو",
    sig: "Shalom («paz») = Esav = 376 — el mismo valor para la paz y para el hermano hostil: el filo doble del encuentro de Jacob (Gn 33).",
    sigFa: "شالوم («صلح») = عِساو = ۳۷۶ — یک ارزش برای صلح و برای برادرِ خصم: لبهٔ دوگانهٔ دیدارِ یعقوب (پیدایش ۳۳).",
    asociaciones: [
      "שָׁלוֹם (Shalom, «paz») = 376",
      "עֵשָׂו (Esav) = 376",
      "Jacob busca «shalom» con Esav (Gn 33:4) — Dos Filos: enemigo y paz comparten número",
    ],
    asociacionesFa: [
      "شالوم («صلح») = ۳۷۶",
      "عِساو = ۳۷۶",
      "یعقوب با عِساو در پیِ «شالوم» است (پیدایش ۳۳) — دو لبه: دشمن و صلح هم‌عددند",
    ],
    color: "#a06a8e",
  },
  {
    num: 39, he: "יהוה אֶחָד · טַל", titulo: "«El Señor es Uno» y el rocío", tituloFa: "«خداوند یگانه است» و شبنم",
    sig: "YHVH Ejad («el Señor es Uno», del Shemá) = Tal («rocío») = 39 — la declaración de la unidad desciende como rocío de resurrección.",
    sigFa: "یهوه اِچاد («خداوند یگانه است»، از شِمَع) = طَل («شبنم») = ۳۹ — اعلانِ یگانگی چون شبنمِ رستاخیز فرود می‌آید.",
    asociaciones: [
      "יהוה אֶחָד (YHVH Ejad) = 26 + 13 = 39",
      "טַל (Tal, «rocío») = 39",
      "El rocío de la resurrección (Tal de Tjiat HaMetim)",
    ],
    asociacionesFa: [
      "یهوه اِچاد = ۲۶ + ۱۳ = ۳۹",
      "طَل («شبنم») = ۳۹",
      "شبنمِ رستاخیز (طَلِ زنده‌شدنِ مردگان)",
    ],
    color: "#6a9ac0",
  },
  {
    num: 58, he: "נֹחַ · חֵן", titulo: "Noaj y la gracia", tituloFa: "نوح و فیض",
    sig: "Noaj = Jen («gracia») = 58 — y la Torá lo dice literal: «Noaj halló gracia (jen) ante Dios» (Gn 6:8).",
    sigFa: "نوح = خِن («فیض») = ۵۸ — و تورات تصریح می‌کند: «نوح در نظرِ خدا فیض یافت» (پیدایش ۶).",
    asociaciones: [
      "נֹחַ (Noaj) = 58",
      "חֵן (Jen, «gracia») = 58 — anagrama de Noaj",
      "«וְנֹחַ מָצָא חֵן» — «Noaj halló gracia» (Génesis 6:8)",
      "נֹגַהּ (Noga, «resplandor») = 58",
    ],
    asociacionesFa: [
      "نوح = ۵۸",
      "خِن («فیض») = ۵۸ — واروخوانیِ نوح",
      "«وְنֹחַ מָצָא חֵן» — «نوح فیض یافت» (پیدایش ۶)",
      "نوגَه («درخشش») = ۵۸",
    ],
    color: "#5a9a6a",
  },
  {
    num: 61, he: "אֲנִי · אַיִן", titulo: "El «Yo» y la Nada", tituloFa: "«من» و نیستی",
    sig: "Ani («yo») = Ayin («nada») = 61 — las mismas letras: el yo (ani) revuelto se vuelve nada (ayin); ego e infinito comparten número.",
    sigFa: "اَنی («من») = اَین («نیستی») = ۶۱ — همان حروف: «منِ» (اَنی) درهم‌ریخته «نیستی» (اَین) می‌شود؛ خودی و بی‌نهایت هم‌عددند.",
    asociaciones: [
      "אֲנִי (Ani, «yo») = 61",
      "אַיִן (Ayin, «nada») = 61 — anagrama de Ani",
      "El tzimtzum: el «yo» se anula en la Nada divina (bitul)",
    ],
    asociacionesFa: [
      "اَنی («من») = ۶۱",
      "اَین («نیستی») = ۶۱ — واروخوانیِ اَنی",
      "تزیمتزوم: «من» در نیستیِ الهی محو می‌شود (بیطول)",
    ],
    color: "#8866cc",
  },
  {
    num: 130, he: "סֻלָּם · סִינַי", titulo: "La escalera y el Sinaí", tituloFa: "نردبان و سینا",
    sig: "Sulam («escalera» de Jacob) = Sinaí = 130 — la escalera del sueño y el monte de la Torá son la misma vía al cielo.",
    sigFa: "سولام («نردبانِ» یعقوب) = سینای = ۱۳۰ — نردبانِ رؤیا و کوهِ تورات، یک راه به آسمان‌اند.",
    asociaciones: [
      "סֻלָּם (Sulam, «escalera», Gn 28:12) = 130",
      "סִינַי (Sinaí) = 130",
      "Ambos: el puente entre cielo y tierra (Midrash)",
      "130 = 5 × 26 (cinco veces el Nombre)",
    ],
    asociacionesFa: [
      "سولام («نردبان»، پیدایش ۲۸) = ۱۳۰",
      "سینای = ۱۳۰",
      "هر دو: پلِ میانِ آسمان و زمین (میدراش)",
      "۱۳۰ = ۵ × ۲۶ (پنج بار نام)",
    ],
    color: "#6688cc",
  },
  {
    num: 156, he: "יוֹסֵף · צִיּוֹן", titulo: "Yosef y Tzión", tituloFa: "یوسف و صهیون",
    sig: "Yosef = Tzión = 156 — el justo que sostiene al mundo y la ciudad santa comparten valor (= 6 × 26).",
    sigFa: "یوسف = صهیون = ۱۵۶ — صدّیقی که جهان را نگاه می‌دارد و شهرِ مقدّس یک ارزش دارند (= ۶ × ۲۶).",
    asociaciones: [
      "יוֹסֵף (Yosef) = 156",
      "צִיּוֹן (Tzión) = 156",
      "Yosef HaTzadik = el fundamento (Yesod) del mundo",
      "156 = 6 × 26 (seis veces el Nombre)",
    ],
    asociacionesFa: [
      "یوسف = ۱۵۶",
      "صهیون = ۱۵۶",
      "یوسفِ صدّیق = بنیادِ (یِسود) جهان",
      "۱۵۶ = ۶ × ۲۶ (شش بار نام)",
    ],
    color: "#b89a4e",
  },
  {
    num: 78, he: "לֶחֶם · מֶלַח", titulo: "El pan y la sal", tituloFa: "نان و نمک",
    sig: "Lejem («pan») = Melaj («sal») = 78 — las mismas tres letras reordenadas; el sustento y el pacto comparten valor (= 3 × 26).",
    sigFa: "لِخِم («نان») = مِلَح («نمک») = ۷۸ — همان سه حرفِ جابجاشده؛ روزی و پیمان یک ارزش دارند (= ۳ × ۲۶).",
    asociaciones: [
      "לֶחֶם (Lejem, «pan») = 78",
      "מֶלַח (Melaj, «sal») = 78 — anagrama de Lejem (mismas letras)",
      "El «pacto de sal» eterno (Lv 2:13); pan y sal sobre la mesa-altar",
      "78 = 3 × 26 (tres veces el Nombre YHVH)",
    ],
    asociacionesFa: [
      "لِخِم («نان») = ۷۸",
      "مِلَح («نمک») = ۷۸ — واروخوانیِ لِخِم (همان حروف)",
      "«پیمانِ نمک»ِ ابدی (لاویان ۲:۱۳)؛ نان و نمک بر سفره-مذبح",
      "۷۸ = ۳ × ۲۶ (سه بار نامِ یهوه)",
    ],
    color: "#b89a4e",
  },
  {
    num: 182, he: "יַעֲקֹב", titulo: "Yaakov, el séptuple Nombre", tituloFa: "یعقوب",
    sig: "Yaakov = 182 = 7 × 26 — el tercer patriarca, columna central (Tiferet), contiene siete veces el Nombre YHVH.",
    sigFa: "یعقوب = ۱۸۲ = ۷ × ۲۶ — سومین پدرِ قوم، ستونِ میانی (تیفِرِت)، هفت بار نامِ یهوه را دربر دارد.",
    asociaciones: [
      "יַעֲקֹב (Yaakov) = 182",
      "182 = 7 × 26 (siete veces el Nombre YHVH)",
      "Yaakov = Tiferet, la columna central del Árbol de la Vida",
      "Junto a Yosef (156 = 6×26) forma la cadena de múltiplos del Nombre",
    ],
    asociacionesFa: [
      "یعقوب = ۱۸۲",
      "۱۸۲ = ۷ × ۲۶ (هفت بار نامِ یهوه)",
      "یعقوب = تیفِرِت، ستونِ میانیِ درختِ زندگی",
      "همراه با یوسف (۱۵۶ = ۶×۲۶) زنجیرهٔ مضاربِ نام را می‌سازد",
    ],
    color: "#c9a43e",
  },
  {
    num: 345, he: "מֹשֶׁה · הַשֵּׁם", titulo: "Moshé, el espejo del Nombre", tituloFa: "موسی، آینهٔ نام",
    sig: "Moshé = HaShem («el Nombre») = 345 — y su valor invertido, 543, es Ehyé Asher Ehyé, el Nombre que oyó en la zarza (Arí).",
    sigFa: "موسی = هَشِم («نام») = ۳۴۵ — و ارزشِ واژگونش، ۵۴۳، همان اِهیه اَشِر اِهیه است، نامی که در بوته شنید (آری).",
    asociaciones: [
      "מֹשֶׁה (Moshé) = 345",
      "הַשֵּׁם (HaShem, «el Nombre») = 345",
      "345 invertido = 543 = Ehyé Asher Ehyé, el Nombre de la zarza (Éx 3:14)",
    ],
    asociacionesFa: [
      "موسی = ۳۴۵",
      "هَشِم («نام») = ۳۴۵",
      "۳۴۵ واژگون = ۵۴۳ = اِهیه اَشِر اِهیه، نامِ بوته (خروج ۳:۱۴)",
    ],
    color: "#7a8ad0",
  },
  {
    num: 395, he: "נְשָׁמָה · הַשָּׁמַיִם", titulo: "El alma y los cielos", tituloFa: "روح و آسمان‌ها",
    sig: "Neshamá («alma») = HaShamayim («los cielos») = 395 — el alma comparte valor con los cielos: su raíz está arriba.",
    sigFa: "نِشاما («روح») = هَشامَییم («آسمان‌ها») = ۳۹۵ — روح با آسمان‌ها هم‌ارزش است: ریشه‌اش در بالاست.",
    asociaciones: [
      "נְשָׁמָה (Neshamá, «alma») = 395",
      "הַשָּׁמַיִם (HaShamayim, «los cielos») = 395",
      "El alma es «porción de Dios desde lo alto» (Job 31:2)",
      "Dios sopló el alma de vida en el hombre (Gn 2:7)",
    ],
    asociacionesFa: [
      "نِشاما («روح») = ۳۹۵",
      "هَشامَییم («آسمان‌ها») = ۳۹۵",
      "روح «بهره‌ای از خدا از فراز» است (ایوب ۳۱:۲)",
      "خدا نَفَسِ زندگی در آدم دمید (پیدایش ۲:۷)",
    ],
    color: "#8866cc",
  },
  {
    num: 441, he: "אֱמֶת", titulo: "Emet, el sello de verdad", tituloFa: "اِمِت، مُهرِ حقیقت",
    sig: "Emet («verdad») = 441 = 21² — el cuadrado de Ehyé (21); «el sello de Dios es la verdad» (Shabat 55a).",
    sigFa: "اِمِت («حقیقت») = ۴۴۱ = ۲۱² — مربعِ اِهیه (۲۱)؛ «مُهرِ خدا حقیقت است» (شَبات ۵۵a).",
    asociaciones: [
      "אֱמֶת (Emet, «verdad») = 441",
      "441 = 21² — el cuadrado de אֶהְיֶה (Ehyé, 21)",
      "Sus letras א-מ-ת abarcan el principio, el medio y el fin del alefbet",
      "«El sello del Santo, bendito sea, es la verdad» (Shabat 55a)",
    ],
    asociacionesFa: [
      "اِمِت («حقیقت») = ۴۴۱",
      "۴۴۱ = ۲۱² — مربعِ اِهیه (۲۱)",
      "حروفِ א-מ-ת آغاز، میان و پایانِ الفبا را دربر می‌گیرند",
      "«مُهرِ قدّوسِ متبارک حقیقت است» (شَبات ۵۵a)",
    ],
    color: "#d4a838",
  },
];
