// Galería de gematrías sagradas — los números recurrentes del estudio cabalístico.
// Cada entrada: el número, las palabras que comparten ese valor, y sus
// asociaciones (sefirot, Nombres, estructuras de la creación).

export interface Gematria {
  num: number;
  he: string;            // palabra(s) hebrea(s) principal(es), separadas por ·
  titulo: string;        // título español (canónico)
  tituloFa: string;
  tituloEn?: string;     // inglés — lo llena el Sofer por fases ([[i18n-audit]])
  sig: string;           // una línea de significado (español)
  sigFa: string;
  sigEn?: string;        // inglés — lo llena el Sofer por fases
  asociaciones: string[];   // viñetas (español)
  asociacionesFa: string[];
  asociacionesEn?: string[]; // inglés — lo llena el Sofer por fases
  color: string;
  mystery?: string;         // slug de misterio dedicado (ej. "137"), si lo tiene
}

export const GEMATRIAS: Gematria[] = [
  {
    num: 13, he: "אֶחָד · אַהֲבָה", titulo: "Unidad y Amor", tituloFa: "یگانگی و عشق", tituloEn: "Oneness and Love",
    sig: "Ejad (Uno) y Ahavá (Amor) comparten el mismo valor: la unidad de Dios es el amor.",
    sigFa: "اِچاد (یک) و اَهاوا (عشق) یک ارزش دارند: یگانگیِ خدا همان عشق است.",
    sigEn: "Echad (One) and Ahavah (Love) share the same value: the oneness of God is love.",
    asociaciones: ["אֶחָד (Ejad, «Uno») = 13", "אַהֲבָה (Ahavá, «Amor») = 13", "Los 13 atributos de misericordia"],
    asociacionesFa: ["اِچاد («یک») = ۱۳", "اَهاوا («عشق») = ۱۳", "سیزده صفتِ رحمت"],
    asociacionesEn: [
      "אֶחָד (Echad, “One”) = 13",
      "אַהֲבָה (Ahavah, “Love”) = 13",
      "The 13 attributes of mercy",
    ],
    color: "#e0a850",
  },
  {
    num: 18, he: "חַי", titulo: "Vida", tituloFa: "زندگی", tituloEn: "Life",
    sig: "Jai («vivo») — el número de la vida, presente en bendiciones y donaciones.",
    sigFa: "خَی («زنده») — عددِ زندگی، در برکات و بخشش‌ها.",
    sigEn: "Chai (“alive”) — the number of life, present in blessings and charitable gifts.",
    asociaciones: ["חַי (Jai, «vivo») = 18", "Doblado (36) = los 36 justos ocultos"],
    asociacionesFa: ["خَی («زنده») = ۱۸", "دوبرابر (۳۶) = سی‌وشش صدّیقِ پنهان"],
    asociacionesEn: [
      "חַי (Chai, “alive”) = 18",
      "Doubled (36) = the 36 hidden righteous ones",
    ],
    color: "#5a9a6a",
  },
  {
    num: 26, he: "יהוה", titulo: "El Nombre", tituloFa: "نامِ خدا", tituloEn: "The Name",
    sig: "El Tetragrámaton (YHVH), el Nombre divino más sagrado: Yud(10) Hei(5) Vav(6) Hei(5).",
    sigFa: "تتراگرامتون (یهوه)، مقدّس‌ترین نامِ الهی: یود(۱۰) هی(۵) واو(۶) هی(۵).",
    sigEn: "The Tetragrammaton (YHVH), the most sacred divine Name: Yud(10) Hei(5) Vav(6) Hei(5).",
    asociaciones: ["יהוה = 26", "Ejad(13) + Ahavá(13) = 26", "La estructura del Árbol de la Vida"],
    asociacionesFa: ["یهوه = ۲۶", "اِچاد(۱۳) + اَهاوا(۱۳) = ۲۶", "ساختارِ درختِ زندگی"],
    asociacionesEn: [
      "יהוה = 26",
      "Echad(13) + Ahavah(13) = 26",
      "The structure of the Tree of Life",
    ],
    color: "#c9a43e",
  },
  {
    num: 32, he: "לֵב", titulo: "Los 32 senderos", tituloFa: "سی‌ودو مسیر", tituloEn: "The 32 Paths",
    sig: "Lev («corazón») = 32 — los 32 senderos de sabiduría del Sefer Yetzirá.",
    sigFa: "لِو («قلب») = ۳۲ — سی‌ودو مسیرِ حکمت در سِفِر یِتزیرا.",
    sigEn: "Lev (“heart”) = 32 — the 32 paths of wisdom of Sefer Yetzirah.",
    asociaciones: ["10 sefirot + 22 letras = 32", "לֵב (Lev, «corazón») = 32", "Comienza y termina la Torá (Bet…Lamed = Lev)"],
    asociacionesFa: ["۱۰ سِفیرا + ۲۲ حرف = ۳۲", "لِو («قلب») = ۳۲", "آغاز و انجامِ تورات (بِت…لَمِد)"],
    asociacionesEn: [
      "10 sefirot + 22 letters = 32",
      "לֵב (Lev, “heart”) = 32",
      "The Torah begins and ends with them (Bet…Lamed = Lev)",
    ],
    color: "#cc5555",
  },
  {
    num: 42, he: "מ\"ב", titulo: "El Nombre de 42", tituloFa: "نامِ چهل‌ودو", tituloEn: "The Name of 42",
    sig: "El Nombre de 42 letras — la oración Ana BeKoaj, la Cabalá contemplativa de la ascensión.",
    sigFa: "نامِ چهل‌ودو حرفی — دعای اَنا بِکوآح، کابالای تأمّلیِ عروج.",
    sigEn: "The 42-letter Name — the Ana BeKoach prayer, the contemplative Kabbalah of ascent.",
    asociaciones: ["El Nombre de 42 letras", "Aná BeKoaj (7 versos × 6 palabras)", "Los 42 viajes del desierto"],
    asociacionesFa: ["نامِ چهل‌ودو حرفی", "اَنا بِکوآح (۷ بند × ۶ واژه)", "چهل‌ودو سفرِ بیابان"],
    asociacionesEn: [
      "The 42-letter Name",
      "Ana BeKoach (7 lines × 6 words)",
      "The 42 journeys in the wilderness",
    ],
    color: "#7a8ad0",
  },
  {
    num: 45, he: "אָדָם · מ\"ה", titulo: "Adam y el Tikún", tituloFa: "آدام و تیقون", tituloEn: "Adam and the Tikkun",
    sig: "Adam = 45 = Mah, la expansión del Nombre asociada al mundo de la rectificación.",
    sigFa: "آدام = ۴۵ = مَه، گسترشِ نام مرتبط با عالمِ تیقون.",
    sigEn: "Adam = 45 = Mah, the expansion of the Name associated with the world of rectification.",
    asociaciones: ["אָדָם (Adam) = 45", "מ\"ה (Mah) — el milui del Tikún", "El mundo de Yetzirá / Zeir Anpín"],
    asociacionesFa: ["آدام = ۴۵", "مَه — میلویِ تیقون", "عالمِ یِتزیراه / زِئیر آنپین"],
    asociacionesEn: [
      "אָדָם (Adam) = 45",
      "מ\"ה (Mah) — the milui of Tikkun",
      "The world of Yetzirah / Zeir Anpin",
    ],
    color: "#b89a4e",
  },
  {
    num: 49, he: "מ\"ט", titulo: "Las 49 puertas", tituloFa: "چهل‌ونه دروازه", tituloEn: "The 49 Gates",
    sig: "7 × 7 — los 49 días del Ómer, los 49 niveles de comprensión y refinamiento.",
    sigFa: "۷ × ۷ — چهل‌ونه روزِ عُمِر، چهل‌ونه سطحِ فهم و پالایش.",
    sigEn: "7 × 7 — the 49 days of the Omer, the 49 levels of understanding and refinement.",
    asociaciones: ["7 × 7 = 49", "Los 49 días del Ómer", "Las 49 puertas de Biná (la 50ª es oculta)"],
    asociacionesFa: ["۷ × ۷ = ۴۹", "چهل‌ونه روزِ عُمِر", "چهل‌ونه دروازهٔ بینا (پنجاهمی پنهان است)"],
    asociacionesEn: [
      "7 × 7 = 49",
      "The 49 days of the Omer",
      "The 49 gates of Binah (the 50th is hidden)",
    ],
    color: "#6a9ac0",
  },
  {
    num: 50, he: "נ", titulo: "Los 50 portales", tituloFa: "پنجاه دروازه", tituloEn: "The 50 Gates",
    sig: "Los 50 portales de Biná y el Jubileo (Yovel) — la libertad y el entendimiento supremo.",
    sigFa: "پنجاه دروازهٔ بینا و یوبیل (یووِل) — آزادی و فهمِ والا.",
    sigEn: "The 50 gates of Binah and the Jubilee (Yovel) — freedom and supreme understanding.",
    asociaciones: ["50 portales de Biná", "El Yovel (Jubileo)", "La letra Nun (נ) = 50"],
    asociacionesFa: ["پنجاه دروازهٔ بینا", "یووِل (یوبیل)", "حرفِ نون = ۵۰"],
    asociacionesEn: [
      "The 50 gates of Binah",
      "The Yovel (Jubilee)",
      "The letter Nun (נ) = 50",
    ],
    color: "#8866cc",
  },
  {
    num: 52, he: "בֶּן · ב\"ן", titulo: "El Hijo, Maljut", tituloFa: "پسر، مَلخوت", tituloEn: "The Son, Malchut",
    sig: "Ben («hijo») = 52 = Ban, la expansión del Nombre asociada a Maljut, el mundo manifestado.",
    sigFa: "بِن («پسر») = ۵۲ = بَن، گسترشِ نام مرتبط با مَلخوت، عالمِ آشکار.",
    sigEn: "Ben (“son”) = 52 = Ban, the expansion of the Name associated with Malchut, the manifest world.",
    asociaciones: ["בֶּן (Ben, «hijo») = 52", "ב\"ן (Ban) — el milui de Maljut", "El mundo de Asiá / la Nukva"],
    asociacionesFa: ["بِن («پسر») = ۵۲", "بَن — میلویِ مَلخوت", "عالمِ عَسیاه / نوقوا"],
    asociacionesEn: [
      "בֶּן (Ben, “son”) = 52",
      "ב\"ן (Ban) — the milui of Malchut",
      "The world of Asiyah / the Nukva",
    ],
    color: "#a06a8e",
  },
  {
    num: 63, he: "ס\"ג", titulo: "Biná, Sag", tituloFa: "بینا، سَگ", tituloEn: "Binah, Sag",
    sig: "Sag — la expansión del Nombre relacionada con Biná, el entendimiento superior.",
    sigFa: "سَگ — گسترشِ نام مرتبط با بینا، فهمِ والا.",
    sigEn: "Sag — the expansion of the Name related to Binah, the higher understanding.",
    asociaciones: ["ס\"ג (Sag) = 63", "El mundo de Beriá", "La Ima superna (la Madre)"],
    asociacionesFa: ["سَگ = ۶۳", "عالمِ بِریاه", "ایمای علیا (مادر)"],
    asociacionesEn: [
      "ס\"ג (Sag) = 63",
      "The world of Beriah",
      "The supernal Ima (the Mother)",
    ],
    color: "#6688cc",
  },
  {
    num: 70, he: "סוֹד · יַיִן", titulo: "Las 70 caras", tituloFa: "هفتاد چهره", tituloEn: "The 70 Faces",
    sig: "Sod («secreto») = Yayin («vino») = 70 — «entró el vino, salió el secreto». Las 70 caras de la Torá.",
    sigFa: "سود («راز») = یَیین («شراب») = ۷۰ — «شراب درآمد، راز برآمد». هفتاد چهرهٔ تورات.",
    sigEn: "Sod (“secret”) = Yayin (“wine”) = 70 — “wine went in, the secret came out.” The 70 faces of the Torah.",
    asociaciones: ["סוֹד (Sod, «secreto») = 70", "יַיִן (Yayin, «vino») = 70", "Las 70 naciones, los 70 ancianos, las 70 facetas"],
    asociacionesFa: ["سود («راز») = ۷۰", "یَیین («شراب») = ۷۰", "هفتاد ملت، هفتاد پیر، هفتاد چهره"],
    asociacionesEn: [
      "סוֹד (Sod, “secret”) = 70",
      "יַיִן (Yayin, “wine”) = 70",
      "The 70 nations, the 70 elders, the 70 facets",
    ],
    color: "#9a3a3a",
  },
  {
    num: 72, he: "ע\"ב · חֶסֶד", titulo: "El Nombre de 72", tituloFa: "نامِ هفتادودو", tituloEn: "The Name of 72",
    sig: "AB = 72 = Jésed — el Shem HaMeforash de 72 tripletes, nacido de la partición del mar.",
    sigFa: "عَب = ۷۲ = خِسِد — شِم هَمِفوراش از هفتادودو سه‌گانه، زادهٔ شکافتنِ دریا.",
    sigEn: "Av = 72 = Chesed — the Shem HaMeforash of 72 triplets, born from the splitting of the sea.",
    asociaciones: ["ע\"ב (AB) = 72", "חֶסֶד (Jésed) = 72", "Los 72 Nombres (Éxodo 14:19-21) = 216 letras"],
    asociacionesFa: ["عَب = ۷۲", "خِسِد = ۷۲", "هفتادودو نام (خروج ۱۴) = ۲۱۶ حرف"],
    asociacionesEn: [
      "ע\"ב (Av) = 72",
      "חֶסֶד (Chesed) = 72",
      "The 72 Names (Exodus 14:19-21) = 216 letters",
    ],
    color: "#d4a838",
  },
  {
    num: 91, he: "אָמֵן", titulo: "La unificación", tituloFa: "یگانه‌سازی", tituloEn: "The Unification",
    sig: "26 (YHVH) + 65 (Adonai) = 91 = Amén — la unión del Nombre oculto y el revelado.",
    sigFa: "۲۶ (یهوه) + ۶۵ (اَدونای) = ۹۱ = آمین — پیوندِ نامِ پنهان و آشکار.",
    sigEn: "26 (YHVH) + 65 (Adonai) = 91 = Amen — the union of the hidden Name and the revealed one.",
    asociaciones: ["יהוה (26) + אֲדֹנָי (65) = 91", "אָמֵן (Amén) = 91", "Decir «Amén» une ambos Nombres"],
    asociacionesFa: ["یهوه (۲۶) + اَدونای (۶۵) = ۹۱", "آمین = ۹۱", "گفتنِ «آمین» دو نام را می‌پیوندد"],
    asociacionesEn: [
      "יהוה (26) + אֲדֹנָי (65) = 91",
      "אָמֵן (Amen) = 91",
      "Saying “Amen” joins both Names",
    ],
    color: "#c9a43e",
  },
  {
    num: 112, he: "יַבֹּק", titulo: "Yabok, las kavanot", tituloFa: "یَبوق", tituloEn: "Yabok, the Kavanot",
    sig: "Yabok = 112 — donde Jacob luchó con el ángel; las kavanot del Arí: YHVH + Adonai + Ehyeh.",
    sigFa: "یَبوق = ۱۱۲ — جایی که یعقوب با فرشته کشتی گرفت؛ کاوانوتِ آری.",
    sigEn: "Yabok = 112 — where Jacob wrestled with the angel; the kavanot of the Ari: YHVH + Adonai + Ehyeh.",
    asociaciones: ["יַבֹּק (Yabok) = 112", "יהוה(26)+אדני(65)+אהיה(21) = 112", "Las kavanot de unificación del Arí"],
    asociacionesFa: ["یَبوق = ۱۱۲", "یهوه+اَدونای+اِهیه = ۱۱۲", "کاوانوتِ یگانه‌سازیِ آری"],
    asociacionesEn: [
      "יַבֹּק (Yabok) = 112",
      "יהוה(26)+אדני(65)+אהיה(21) = 112",
      "The Ari's kavanot of unification",
    ],
    color: "#7a8ad0",
  },
  {
    num: 137, he: "קַבָּלָה", titulo: "El acertijo de la creación", tituloFa: "معمای آفرینش", tituloEn: "The Riddle of Creation",
    sig: "Kabalah («recibir») = 137. Y la constante de estructura fina α ≈ 1/137 — donde la Cabalá toca la física (Rav Ginsburgh, «137: The Riddle of Creation»).",
    sigFa: "قبالا («دریافت») = ۱۳۷. و ثابتِ ساختارِ ریز α ≈ ۱/۱۳۷ — جایی که کابالا به فیزیک می‌رسد (راو گینزبورگ).",
    sigEn: "Kabbalah (“to receive”) = 137. And the fine-structure constant α ≈ 1/137 — where Kabbalah touches physics (Rav Ginsburgh, “137: The Riddle of Creation”).",
    asociaciones: [
      "קַבָּלָה (Kabbalah, «recibir») = 137",
      "La constante de estructura fina: α ≈ 1/137 (la física)",
      "Tres vivieron 137 años: Ishmael, Leví, Amram",
      "אוֹפָן (Ofan, «rueda» de Yejezkel) = 137",
      "מוֹצָא (Motza, «origen, fuente») = 137",
      "תֹּהוּ (Tohu, «caos») = 411 = 3 × 137",
      "יֵשׁ מֵאַיִן («algo de la nada») = 411 = 3 × 137",
      "Génesis 1 tiene exactamente 137 palabras de 3 letras",
    ],
    asociacionesFa: [
      "قبالا («دریافت») = ۱۳۷",
      "ثابتِ ساختارِ ریز: α ≈ ۱/۱۳۷ (فیزیک)",
      "سه تن ۱۳۷ سال زیستند: اسماعیل، لاوی، عَمرام",
      "اوֹفان («چرخِ» یحزقیل) = ۱۳۷",
      "موצا («سرچشمه») = ۱۳۷",
      "توهو («آشوب») = ۴۱۱ = ۳ × ۱۳۷",
      "یِش مِاَین («هستی از نیستی») = ۴۱۱ = ۳ × ۱۳۷",
      "پیدایش ۱ دقیقاً ۱۳۷ واژهٔ سه‌حرفی دارد",
    ],
    asociacionesEn: [
      "קַבָּלָה (Kabbalah, “to receive”) = 137",
      "The fine-structure constant: α ≈ 1/137 (physics)",
      "Three lived 137 years: Ishmael, Levi, Amram",
      "אוֹפָן (Ofan, the “wheel” of Ezekiel) = 137",
      "מוֹצָא (Motza, “origin, source”) = 137",
      "תֹּהוּ (Tohu, “chaos”) = 411 = 3 × 137",
      "יֵשׁ מֵאַיִן (“something from nothing”) = 411 = 3 × 137",
      "Genesis 1 has exactly 137 three-letter words",
    ],
    color: "#9a6a8e",
    mystery: "137",
  },
  {
    num: 248, he: "אַבְרָהָם", titulo: "Avraham y los 248", tituloFa: "اَبراهام", tituloEn: "Avraham and the 248",
    sig: "Avraham = 248 — los 248 órganos del cuerpo y los 248 mandamientos positivos.",
    sigFa: "اَبراهام = ۲۴۸ — دویست‌وچهل‌وهشت اندامِ بدن و میتزووتِ مثبت.",
    sigEn: "Avraham = 248 — the 248 organs of the body and the 248 positive commandments.",
    asociaciones: ["אַבְרָהָם (Avraham) = 248", "248 miembros espirituales del cuerpo", "248 mitzvot positivas"],
    asociacionesFa: ["اَبراهام = ۲۴۸", "دویست‌وچهل‌وهشت اندامِ روحانی", "میتزووتِ مثبت"],
    asociacionesEn: [
      "אַבְרָהָם (Avraham) = 248",
      "248 spiritual limbs of the body",
      "248 positive mitzvot",
    ],
    color: "#5a9a6a",
  },
  {
    num: 613, he: "תרי\"ג", titulo: "Las 613 mitzvot", tituloFa: "ششصدوسیزده میتزوا", tituloEn: "The 613 Mitzvot",
    sig: "El total de los mandamientos de la Torá: 248 positivos + 365 negativos.",
    sigFa: "مجموعِ احکامِ تورات: ۲۴۸ مثبت + ۳۶۵ منفی.",
    sigEn: "The total of the Torah's commandments: 248 positive + 365 negative.",
    asociaciones: ["248 positivas + 365 negativas = 613", "365 = días del año / preceptos negativos", "תרי\"ג (Taryag)"],
    asociacionesFa: ["۲۴۸ مثبت + ۳۶۵ منفی = ۶۱۳", "۳۶۵ = روزهای سال", "تَریَگ"],
    asociacionesEn: [
      "248 positive + 365 negative = 613",
      "365 = days of the year / negative precepts",
      "תרי\"ג (Taryag)",
    ],
    color: "#c9a43e",
  },
  {
    num: 620, he: "כֶּתֶר", titulo: "Kéter, la Corona", tituloFa: "کِتِر، تاج", tituloEn: "Keter, the Crown",
    sig: "Kéter («corona») = 620 — la sefirá suprema; las 613 mitzvot más los 7 preceptos rabínicos.",
    sigFa: "کِتِر («تاج») = ۶۲۰ — سِفیرای والا؛ ۶۱۳ میتزوا به‌علاوهٔ هفت حکمِ ربانی.",
    sigEn: "Keter (“crown”) = 620 — the supreme sefirah; the 613 mitzvot plus the 7 rabbinic precepts.",
    asociaciones: ["כֶּתֶר (Kéter) = 620", "613 mitzvot + 7 preceptos = 620", "La corona suprema, sobre el intelecto"],
    asociacionesFa: ["کِتِر = ۶۲۰", "۶۱۳ + ۷ = ۶۲۰", "تاجِ والا، فراتر از عقل"],
    asociacionesEn: [
      "כֶּתֶר (Keter) = 620",
      "613 mitzvot + 7 precepts = 620",
      "The supreme crown, above the intellect",
    ],
    color: "#f0d878",
  },
  {
    num: 86, he: "אֱלֹהִים · הַטֶּבַע", titulo: "Dios y la Naturaleza", tituloFa: "خدا و طبیعت", tituloEn: "God and Nature",
    sig: "Elohim = HaTeva («la naturaleza») = 86 — el Nombre que crea es la naturaleza misma (Ginsburgh).",
    sigFa: "اِلوهیم = هَطِبَع («طبیعت») = ۸۶ — نامی که می‌آفریند، خودِ طبیعت است (گینزبورگ).",
    sigEn: "Elohim = HaTeva (“nature”) = 86 — the Name that creates is nature itself (Ginsburgh).",
    asociaciones: [
      "אֱלֹהִים (Elohim) = 86",
      "הַטֶּבַע (HaTeva, «la naturaleza») = 86",
      "Elohim es el Nombre del juicio y del orden natural",
      "כּוֹס (Kos, «copa» de bendición) = 86",
    ],
    asociacionesFa: [
      "اِلوهیم = ۸۶",
      "هَطِبَع («طبیعت») = ۸۶",
      "اِلوهیم نامِ داوری و نظمِ طبیعت است",
      "کوס («جامِ» برکت) = ۸۶",
    ],
    asociacionesEn: [
      "אֱלֹהִים (Elohim) = 86",
      "הַטֶּבַע (HaTeva, “nature”) = 86",
      "Elohim is the Name of judgment and of the natural order",
      "כּוֹס (Kos, the “cup” of blessing) = 86",
    ],
    color: "#5a9a6a",
  },
  {
    num: 358, he: "מָשִׁיחַ · נָחָשׁ", titulo: "Mashíaj y la serpiente", tituloFa: "ماشیَح و مار", tituloEn: "Mashiach and the Serpent",
    sig: "Mashíaj = Najash («serpiente») = 358 — el redentor rectifica exactamente lo que la serpiente corrompió.",
    sigFa: "ماشیَح = ناخاش («مار») = ۳۵۸ — رهاننده دقیقاً همان را تیقون می‌کند که مار فاسد کرد.",
    sigEn: "Mashiach = Nachash (“serpent”) = 358 — the redeemer rectifies exactly what the serpent corrupted.",
    asociaciones: [
      "מָשִׁיחַ (Mashíaj) = 358",
      "נָחָשׁ (Najash, «serpiente») = 358",
      "El Mashíaj eleva la caída del Edén (Dos Filos)",
    ],
    asociacionesFa: [
      "ماشیَح = ۳۵۸",
      "ناخاش («مار») = ۳۵۸",
      "ماشیَح سقوطِ عَدَن را برمی‌کشد (دو لبه)",
    ],
    asociacionesEn: [
      "מָשִׁיחַ (Mashiach) = 358",
      "נָחָשׁ (Nachash, “serpent”) = 358",
      "Mashiach raises up the fall of Eden (Two Edges)",
    ],
    color: "#9a3a3a",
  },
  {
    num: 314, he: "שַׁדַּי · מטטרון", titulo: "Shaddai y Metatrón", tituloFa: "شَدّای و مِتاترون", tituloEn: "Shaddai and Metatron",
    sig: "Shaddai = Metatrón = 314 — el Nombre del límite y el ángel del Trono comparten valor.",
    sigFa: "شَدّای = مِتاترون = ۳۱۴ — نامِ مرز و فرشتهٔ تخت یک ارزش دارند.",
    sigEn: "Shaddai = Metatron = 314 — the Name of the boundary and the angel of the Throne share one value.",
    asociaciones: [
      "שַׁדַּי (Shaddai) = 314",
      "מטטרון (Metatrón, el ángel del Trono) = 314",
      "Shaddai: «el que dijo a su mundo: ¡basta!» (Jaguigá 12a)",
    ],
    asociacionesFa: [
      "شَدّای = ۳۱۴",
      "مِتاترون (فرشتهٔ تخت) = ۳۱۴",
      "شَدّای: «آن‌که به جهانش گفت: بس!» (حگیگا ۱۲a)",
    ],
    asociacionesEn: [
      "שַׁדַּי (Shaddai) = 314",
      "מטטרון (Metatron, the angel of the Throne) = 314",
      "Shaddai: “He who said to His world: enough!” (Chagigah 12a)",
    ],
    color: "#7a8ad0",
  },
  {
    num: 541, he: "יִשְׂרָאֵל", titulo: "Israel", tituloFa: "اسرائیل", tituloEn: "Israel",
    sig: "Israel = 541 — el nombre que Jacob recibió tras luchar con el ángel (Gn 32:29).",
    sigFa: "ایسرائل = ۵۴۱ — نامی که یعقوب پس از کشتی با فرشته یافت (پیدایش ۳۲).",
    sigEn: "Israel = 541 — the name Jacob received after wrestling with the angel (Gen 32:29).",
    asociaciones: [
      "יִשְׂרָאֵל (Israel) = 541",
      "«Has luchado con Dios y con hombres y has vencido» (Gn 32:29)",
      "Israel contiene las iniciales de los Patriarcas y Matriarcas",
    ],
    asociacionesFa: [
      "ایسرائل = ۵۴۱",
      "«با خدا و انسان‌ها کشتی گرفتی و پیروز شدی» (پیدایش ۳۲)",
      "ایسرائل دربردارندهٔ سرحروفِ پدران و مادرانِ قوم است",
    ],
    asociacionesEn: [
      "יִשְׂרָאֵל (Israel) = 541",
      "“You have striven with God and with men, and have prevailed” (Gen 32:29)",
      "Israel contains the initials of the Patriarchs and Matriarchs",
    ],
    color: "#6a9ac0",
  },
  {
    num: 611, he: "תּוֹרָה", titulo: "La Torá recibida", tituloFa: "توراتِ دریافت‌شده", tituloEn: "The Torah Received",
    sig: "Torá = 611 — las mitzvot que recibimos por boca de Moshé; las otras dos (Yo soy / No tendrás) las oyó Israel de Dios directo.",
    sigFa: "تورات = ۶۱۱ — احکامی که از زبانِ موسی دریافت کردیم؛ دو فرمانِ نخست را قوم مستقیم از خدا شنید.",
    sigEn: "Torah = 611 — the mitzvot we received from the mouth of Moshe; the other two (I am / You shall have no) Israel heard directly from God.",
    asociaciones: [
      "תּוֹרָה (Torá) = 611",
      "611 + 2 (los dos primeros mandamientos oídos directo) = 613",
      "«Torá nos ordenó Moshé» (Dt 33:4) — Makot 23b-24a",
    ],
    asociacionesFa: [
      "تورات = ۶۱۱",
      "۶۱۱ + ۲ (دو فرمانِ نخست که مستقیم شنیده شد) = ۶۱۳",
      "«تورات را موسی به ما فرمان داد» (تثنیه ۳۳) — مَکوت ۲۴a",
    ],
    asociacionesEn: [
      "תּוֹרָה (Torah) = 611",
      "611 + 2 (the first two commandments heard directly) = 613",
      "“Moshe commanded us Torah” (Deut 33:4) — Makkot 23b-24a",
    ],
    color: "#c9a43e",
  },
  {
    num: 207, he: "אוֹר · רָז", titulo: "La luz y el secreto", tituloFa: "نور و راز", tituloEn: "The Light and the Secret",
    sig: "Or («luz») = Raz («secreto») = Ein Sof = 207 — la luz oculta es el secreto del Infinito (Ginsburgh).",
    sigFa: "اور («نور») = راز = اِین سوف = ۲۰۷ — نورِ پنهان، رازِ بی‌نهایت است (گینزبورگ).",
    sigEn: "Or (“light”) = Raz (“secret”) = Ein Sof = 207 — the hidden light is the secret of the Infinite (Ginsburgh).",
    asociaciones: [
      "אוֹר (Or, «luz») = 207",
      "רָז (Raz, «secreto») = 207",
      "אֵין סוֹף (Ein Sof, «el Infinito») = 207",
      "Revelar el secreto (raz) es revelar la luz (or)",
    ],
    asociacionesFa: [
      "اور («نور») = ۲۰۷",
      "راز = ۲۰۷",
      "اِین سوف («بی‌نهایت») = ۲۰۷",
      "آشکار کردنِ راز، آشکار کردنِ نور است",
    ],
    asociacionesEn: [
      "אוֹר (Or, “light”) = 207",
      "רָז (Raz, “secret”) = 207",
      "אֵין סוֹף (Ein Sof, “the Infinite”) = 207",
      "To reveal the secret (raz) is to reveal the light (or)",
    ],
    color: "#f0d878",
  },
  {
    num: 111, he: "אָלֶף · פֶּלֶא", titulo: "El Álef y la maravilla", tituloFa: "اَلِف و شگفتی", tituloEn: "The Alef and the Wonder",
    sig: "Álef deletreada (אלף) = Pele («maravilla») = 111 — la primera letra es la maravilla oculta del Uno.",
    sigFa: "اَلِف به‌حروف (אלף) = پِلِه («شگفتی») = ۱۱۱ — نخستین حرف، شگفتیِ پنهانِ یگانه است.",
    sigEn: "Alef spelled out (אלף) = Pele (“wonder”) = 111 — the first letter is the hidden wonder of the One.",
    asociaciones: [
      "אָלֶף (Álef, deletreada א-ל-ף) = 111",
      "פֶּלֶא (Pele, «maravilla») = 111",
      "Álef y Pele tienen las mismas letras (anagrama)",
      "111 = 3 × 37; el Álef vale 1 y mil (élef) a la vez",
    ],
    asociacionesFa: [
      "اَلِف (به‌حروف א-ל-ף) = ۱۱۱",
      "پِلِه («شگفتی») = ۱۱۱",
      "اَلِف و پِلِه هم‌حرف‌اند (واروخوانی)",
      "۱۱۱ = ۳ × ۳۷؛ اَلِف هم‌زمان یک و هزار (اِلِف) است",
    ],
    asociacionesEn: [
      "אָלֶף (Alef, spelled א-ל-ף) = 111",
      "פֶּלֶא (Pele, “wonder”) = 111",
      "Alef and Pele share the same letters (anagram)",
      "111 = 3 × 37; the Alef is worth one and a thousand (elef) at once",
    ],
    color: "#d4a838",
  },
  {
    num: 216, he: "גְּבוּרָה · אַרְיֵה", titulo: "Guevurá y el león", tituloFa: "گِوورا و شیر", tituloEn: "Gevurah and the Lion",
    sig: "Guevurá = Aryé («león») = 216 — el rigor ruge como león; las 216 letras de los 72 Nombres.",
    sigFa: "گِوورا = اَریه («شیر») = ۲۱۶ — سخت‌گیری چون شیر می‌غرّد؛ ۲۱۶ حرفِ هفتادودو نام.",
    sigEn: "Gevurah = Aryeh (“lion”) = 216 — rigor roars like a lion; the 216 letters of the 72 Names.",
    asociaciones: [
      "גְּבוּרָה (Guevurá, «rigor/fuerza») = 216",
      "אַרְיֵה (Aryé, «león») = 216",
      "72 Nombres × 3 letras = 216 letras (Éx 14:19-21)",
      "216 = 6³ — el cubo del seis",
    ],
    asociacionesFa: [
      "گِوورا («سخت‌گیری») = ۲۱۶",
      "اَریه («شیر») = ۲۱۶",
      "هفتادودو نام × ۳ حرف = ۲۱۶ حرف (خروج ۱۴)",
      "۲۱۶ = ۶³ — مکعبِ شش",
    ],
    asociacionesEn: [
      "גְּבוּרָה (Gevurah, “rigor/strength”) = 216",
      "אַרְיֵה (Aryeh, “lion”) = 216",
      "72 Names × 3 letters = 216 letters (Ex 14:19-21)",
      "216 = 6³ — the cube of six",
    ],
    color: "#cc5555",
  },
  {
    num: 232, he: "ע\"ב ס\"ג מ\"ה ב\"ן", titulo: "Las cuatro expansiones", tituloFa: "چهار گسترش", tituloEn: "The Four Expansions",
    sig: "72 + 63 + 45 + 52 = 232 — la suma de los cuatro miluim del Nombre YHVH, los cuatro mundos.",
    sigFa: "۷۲ + ۶۳ + ۴۵ + ۵۲ = ۲۳۲ — مجموعِ چهار میلویِ نامِ یهوه، چهار عالم.",
    sigEn: "72 + 63 + 45 + 52 = 232 — the sum of the four miluim of the Name YHVH, the four worlds.",
    asociaciones: [
      "AB(72) + Sag(63) + Mah(45) + Ban(52) = 232",
      "Las cuatro expansiones de Havayá = los 4 mundos (Atzilut, Beriá, Yetzirá, Asiá)",
      "232 = 8 × 29; abarca toda la estructura del Nombre",
    ],
    asociacionesFa: [
      "عَب(۷۲) + سَگ(۶۳) + مَه(۴۵) + بَن(۵۲) = ۲۳۲",
      "چهار گسترشِ هَوایا = چهار عالم (آتزیلوت، بِریاه، یِتزیراه، عَسیاه)",
      "۲۳۲ = ۸ × ۲۹؛ تمامِ ساختارِ نام را دربر می‌گیرد",
    ],
    asociacionesEn: [
      "Av(72) + Sag(63) + Mah(45) + Ban(52) = 232",
      "The four expansions of Havayah = the 4 worlds (Atzilut, Beriah, Yetzirah, Asiyah)",
      "232 = 8 × 29; it spans the whole structure of the Name",
    ],
    color: "#c9a43e",
  },
  {
    num: 65, he: "אֲדֹנָי · הֵיכָל", titulo: "Adonai y el palacio", tituloFa: "اَدونای و معبد", tituloEn: "Adonai and the Palace",
    sig: "Adonai = Heijal («palacio/templo») = Halel = 65 — el Nombre revelado es el palacio donde se alaba a Dios.",
    sigFa: "اَدونای = هِیخال («معبد») = هَلِل = ۶۵ — نامِ آشکار، معبدی است که در آن خدا را می‌ستایند.",
    sigEn: "Adonai = Heichal (“palace/temple”) = Hallel = 65 — the revealed Name is the palace where God is praised.",
    asociaciones: [
      "אֲדֹנָי (Adonai, «mi Señor») = 65",
      "הֵיכָל (Heijal, «palacio, santuario») = 65",
      "הַלֵּל (Halel, «alabanza») = 65",
      "Adonai = el Nombre revelado, complemento de YHVH",
    ],
    asociacionesFa: [
      "اَدونای («پروردگارِ من») = ۶۵",
      "هِیخال («معبد، حرم») = ۶۵",
      "هَلِل («ستایش») = ۶۵",
      "اَدونای = نامِ آشکار، مکمّلِ یهوه",
    ],
    asociacionesEn: [
      "אֲדֹנָי (Adonai, “my Lord”) = 65",
      "הֵיכָל (Heichal, “palace, sanctuary”) = 65",
      "הַלֵּל (Hallel, “praise”) = 65",
      "Adonai = the revealed Name, complement of YHVH",
    ],
    color: "#a06a8e",
  },
  {
    num: 543, he: "אֶהְיֶה אֲשֶׁר אֶהְיֶה", titulo: "«Seré el que seré»", tituloFa: "«خواهم بود آنکه خواهم بود»", tituloEn: "“I Shall Be What I Shall Be”",
    sig: "Ehyé Asher Ehyé = 543 — la respuesta de Dios a Moshé en la zarza (Éx 3:14): el Nombre del ser puro.",
    sigFa: "اِهیه اَشِر اِهیه = ۵۴۳ — پاسخِ خدا به موسی در بوته (خروج ۳): نامِ هستیِ ناب.",
    sigEn: "Ehyeh Asher Ehyeh = 543 — God's answer to Moshe at the bush (Ex 3:14): the Name of pure being.",
    asociaciones: [
      "אֶהְיֶה אֲשֶׁר אֶהְיֶה (Ehyé Asher Ehyé) = 543",
      "Cada אֶהְיֶה (Ehyé) = 21; el Nombre de Kéter",
      "Éxodo 3:14 — el Nombre del futuro, «el que será»",
    ],
    asociacionesFa: [
      "اِهیه اَشِر اِهیه = ۵۴۳",
      "هر اِهیه = ۲۱؛ نامِ کِتِر",
      "خروج ۳ — نامِ آینده، «آنکه خواهد بود»",
    ],
    asociacionesEn: [
      "אֶהְיֶה אֲשֶׁר אֶהְיֶה (Ehyeh Asher Ehyeh) = 543",
      "Each אֶהְיֶה (Ehyeh) = 21; the Name of Keter",
      "Exodus 3:14 — the Name of the future, “He who shall be”",
    ],
    color: "#b89a4e",
  },
  {
    num: 1820, he: "יהוה ×1820", titulo: "El Nombre en la Torá", tituloFa: "نام در تورات", tituloEn: "The Name in the Torah",
    sig: "1820 = las veces que aparece el Nombre YHVH en la Torá = 26 × 70 — el Nombre (26) por las 70 caras.",
    sigFa: "۱۸۲۰ = شمارِ ظهورِ نامِ یهوه در تورات = ۲۶ × ۷۰ — نام (۲۶) ضرب در هفتاد چهره.",
    sigEn: "1820 = the number of times the Name YHVH appears in the Torah = 26 × 70 — the Name (26) times the 70 faces.",
    asociaciones: [
      "El Nombre יהוה aparece 1820 veces en la Torá",
      "1820 = 26 (YHVH) × 70 (las 70 facetas / naciones)",
      "Es un conteo de apariciones, no un valor de letras",
    ],
    asociacionesFa: [
      "نامِ یهوه ۱۸۲۰ بار در تورات می‌آید",
      "۱۸۲۰ = ۲۶ (یهوه) × ۷۰ (هفتاد چهره / ملت)",
      "این شمارشِ ظهور است، نه ارزشِ حروف",
    ],
    asociacionesEn: [
      "The Name יהוה appears 1820 times in the Torah",
      "1820 = 26 (YHVH) × 70 (the 70 facets / nations)",
      "This is a count of occurrences, not a letter value",
    ],
    color: "#d4a838",
  },
  {
    num: 401, he: "אֵת", titulo: "Del Álef al Tav", tituloFa: "از اَلِف تا تاو", tituloEn: "From Alef to Tav",
    sig: "Et (אֵת) = 401 — Álef(1) + Tav(400): de la primera a la última letra, la totalidad del alefbet.",
    sigFa: "اِت (אֵת) = ۴۰۱ — اَلِف(۱) + تاو(۴۰۰): از نخستین تا واپسین حرف، تمامیِ الفبا.",
    sigEn: "Et (אֵת) = 401 — Alef(1) + Tav(400): from the first letter to the last, the totality of the alef-bet.",
    asociaciones: [
      "אֵת (Et) = 401 = Álef(1) + Tav(400)",
      "El segundo «et» de Génesis 1:1 abarca cielo y tierra enteros",
      "Contiene «del álef al tav»: toda la Torá y la creación",
    ],
    asociacionesFa: [
      "اِت = ۴۰۱ = اَلِف(۱) + تاو(۴۰۰)",
      "«اِت»ِ دومِ پیدایش ۱:۱ آسمان و زمین را به‌تمامی دربر می‌گیرد",
      "«از اَلِف تا تاو»: تمامِ تورات و آفرینش",
    ],
    asociacionesEn: [
      "אֵת (Et) = 401 = Alef(1) + Tav(400)",
      "The second “et” of Genesis 1:1 embraces heaven and earth in full",
      "It contains “from alef to tav”: all of Torah and creation",
    ],
    color: "#8866cc",
  },
  {
    num: 240, he: "עֲמָלֵק · סָפֵק", titulo: "Amalek y la duda", tituloFa: "عَمالِق و تردید", tituloEn: "Amalek and Doubt",
    sig: "Amalek = Safek («duda») = 240 — el enemigo interior es la duda que enfría la fe (Ginsburgh).",
    sigFa: "عَمالِق = سَفِک («تردید») = ۲۴۰ — دشمنِ درونی، همان تردیدی است که ایمان را سرد می‌کند (گینزبورگ).",
    sigEn: "Amalek = Safek (“doubt”) = 240 — the inner enemy is the doubt that cools faith (Ginsburgh).",
    asociaciones: [
      "עֲמָלֵק (Amalek) = 240",
      "סָפֵק (Safek, «duda») = 240",
      "Amalek «enfrió» a Israel en el camino (Dt 25:18 — «karja»)",
      "Borrar a Amalek = disolver la duda",
    ],
    asociacionesFa: [
      "عَمالِق = ۲۴۰",
      "سَفِک («تردید») = ۲۴۰",
      "عَمالِق در راه قوم را «سرد» کرد (تثنیه ۲۵)",
      "محوِ عَمالِق = زدودنِ تردید",
    ],
    asociacionesEn: [
      "עֲמָלֵק (Amalek) = 240",
      "סָפֵק (Safek, “doubt”) = 240",
      "Amalek “cooled” Israel on the way (Deut 25:18 — “karcha”)",
      "To erase Amalek = to dissolve doubt",
    ],
    color: "#9a3a3a",
  },
  {
    num: 169, he: "13²", titulo: "Trece al cuadrado", tituloFa: "سیزده به توان دو", tituloEn: "Thirteen Squared",
    sig: "169 = 13² — Ejad (Uno) y Ahavá (Amor), ambos 13, elevados al cuadrado: la unidad multiplicada por sí misma.",
    sigFa: "۱۶۹ = ۱۳² — اِچاد (یک) و اَهاوا (عشق)، هر دو ۱۳، به توانِ دو: یگانگی در خودش ضرب‌شده.",
    sigEn: "169 = 13² — Echad (One) and Ahavah (Love), both 13, raised to the square: oneness multiplied by itself.",
    asociaciones: [
      "13 × 13 = 169",
      "13 = אֶחָד (Ejad, «Uno») = אַהֲבָה (Ahavá, «Amor»)",
      "El cuadrado de la unidad y del amor",
    ],
    asociacionesFa: [
      "۱۳ × ۱۳ = ۱۶۹",
      "۱۳ = اِچاد («یک») = اَهاوا («عشق»)",
      "مربعِ یگانگی و عشق",
    ],
    asociacionesEn: [
      "13 × 13 = 169",
      "13 = אֶחָד (Echad, “One”) = אַהֲבָה (Ahavah, “Love”)",
      "The square of oneness and of love",
    ],
    color: "#e0a850",
  },
  {
    num: 90, he: "מֶלֶךְ · מַיִם", titulo: "El rey y el agua", tituloFa: "پادشاه و آب", tituloEn: "The King and the Water",
    sig: "Melej («rey») = Mayim («agua») = 90 — la realeza fluye y se derrama como agua sobre el reino.",
    sigFa: "مِلِخ («پادشاه») = مَیِم («آب») = ۹۰ — پادشاهی چون آب بر قلمرو جاری و افشانده می‌شود.",
    sigEn: "Melech (“king”) = Mayim (“water”) = 90 — kingship flows and pours itself out like water over the realm.",
    asociaciones: [
      "מֶלֶךְ (Melej, «rey») = 90",
      "מַיִם (Mayim, «agua») = 90",
      "La letra Tzadi final (ץ) = 90; el «tzadik» justo",
    ],
    asociacionesFa: [
      "مِلِخ («پادشاه») = ۹۰",
      "مَیِم («آب») = ۹۰",
      "حرفِ تزادیِ پایانی (ץ) = ۹۰؛ «تزادیک»ِ صدّیق",
    ],
    asociacionesEn: [
      "מֶלֶךְ (Melech, “king”) = 90",
      "מַיִם (Mayim, “water”) = 90",
      "The final Tzadi (ץ) = 90; the righteous “tzaddik”",
    ],
    color: "#6688cc",
  },
  {
    num: 121, he: "11²", titulo: "Once al cuadrado", tituloFa: "یازده به توان دو", tituloEn: "Eleven Squared",
    sig: "121 = 11² — el once, número de los inciensos del Templo y de las sefirot contando Daat.",
    sigFa: "۱۲۱ = ۱۱² — یازده، عددِ بخورهای معبد و سِفیراها با احتسابِ دَعَت.",
    sigEn: "121 = 11² — eleven, the number of the Temple incense spices and of the sefirot counting Daat.",
    asociaciones: [
      "11 × 11 = 121",
      "11 especias del incienso del Templo (Keritot 6a)",
      "10 sefirot + Daat (la oculta) = 11",
    ],
    asociacionesFa: [
      "۱۱ × ۱۱ = ۱۲۱",
      "یازده گیاهِ بخورِ معبد (کِریتوت ۶a)",
      "ده سِفیرا + دَعَت (پنهان) = یازده",
    ],
    asociacionesEn: [
      "11 × 11 = 121",
      "The 11 spices of the Temple incense (Keritot 6a)",
      "10 sefirot + Daat (the hidden one) = 11",
    ],
    color: "#7a8ad0",
  },
  {
    num: 376, he: "שָׁלוֹם · עֵשָׂו", titulo: "La paz y Esav", tituloFa: "صلح و عِساو", tituloEn: "Peace and Esav",
    sig: "Shalom («paz») = Esav = 376 — el mismo valor para la paz y para el hermano hostil: el filo doble del encuentro de Jacob (Gn 33).",
    sigFa: "شالوم («صلح») = عِساو = ۳۷۶ — یک ارزش برای صلح و برای برادرِ خصم: لبهٔ دوگانهٔ دیدارِ یعقوب (پیدایش ۳۳).",
    sigEn: "Shalom (“peace”) = Esav = 376 — the same value for peace and for the hostile brother: the double edge of Jacob's encounter (Gen 33).",
    asociaciones: [
      "שָׁלוֹם (Shalom, «paz») = 376",
      "עֵשָׂו (Esav) = 376",
      "Jacob busca «shalom» con Esav (Gn 33:4) — Dos Filos: enemigo y paz comparten número",
    ],
    asociacionesFa: [
      "شالوم («صلح») = ۳۷۶",
      "عِساو = ۳۷۶",
      "یعقوب با عِساو در پیِ «شالوم» است (پیدایش ۳۳) — دو لبه: دشمن و صلح هم‌عددند",
    ],
    asociacionesEn: [
      "שָׁלוֹם (Shalom, “peace”) = 376",
      "עֵשָׂו (Esav) = 376",
      "Jacob seeks “shalom” with Esav (Gen 33:4) — Two Edges: enemy and peace share one number",
    ],
    color: "#a06a8e",
  },
  {
    num: 39, he: "יהוה אֶחָד · טַל", titulo: "«El Señor es Uno» y el rocío", tituloFa: "«خداوند یگانه است» و شبنم", tituloEn: "“The Lord Is One” and the Dew",
    sig: "YHVH Ejad («el Señor es Uno», del Shemá) = Tal («rocío») = 39 — la declaración de la unidad desciende como rocío de resurrección.",
    sigFa: "یهوه اِچاد («خداوند یگانه است»، از شِمَع) = طَل («شبنم») = ۳۹ — اعلانِ یگانگی چون شبنمِ رستاخیز فرود می‌آید.",
    sigEn: "YHVH Echad (“the Lord is One,” from the Shema) = Tal (“dew”) = 39 — the declaration of oneness descends like the dew of resurrection.",
    asociaciones: [
      "יהוה אֶחָד (YHVH Ejad) = 26 + 13 = 39",
      "טַל (Tal, «rocío») = 39",
      "El rocío de la resurrección (Tal de Tjiat HaMetim)",
    ],
    asociacionesFa: [
      "یهوه اِچاد = ۲۶ + ۱۳ = ۳۹",
      "طَل («شبنم») = ۳۹",
      "شبنمِ رستاخیز (طَلِ زنده‌شدنِ مردگان)",
    ],
    asociacionesEn: [
      "יהוה אֶחָד (YHVH Echad) = 26 + 13 = 39",
      "טַל (Tal, “dew”) = 39",
      "The dew of resurrection (the Tal of Techiyat HaMetim)",
    ],
    color: "#6a9ac0",
  },
  {
    num: 58, he: "נֹחַ · חֵן", titulo: "Noaj y la gracia", tituloFa: "نوح و فیض", tituloEn: "Noach and Grace",
    sig: "Noaj = Jen («gracia») = 58 — y la Torá lo dice literal: «Noaj halló gracia (jen) ante Dios» (Gn 6:8).",
    sigFa: "نوح = خِن («فیض») = ۵۸ — و تورات تصریح می‌کند: «نوح در نظرِ خدا فیض یافت» (پیدایش ۶).",
    sigEn: "Noach = Chen (“grace”) = 58 — and the Torah says it outright: “Noach found grace (chen) in the eyes of God” (Gen 6:8).",
    asociaciones: [
      "נֹחַ (Noaj) = 58",
      "חֵן (Jen, «gracia») = 58 — anagrama de Noaj",
      "«וְנֹחַ מָצָא חֵן» — «Noaj halló gracia» (Génesis 6:8)",
      "נֹגַהּ (Noga, «resplandor») = 58",
    ],
    asociacionesFa: [
      "نوح = ۵۸",
      "خِن («فیض») = ۵۸ — واروخوانیِ نوح",
      "«وְنֹחַ מָצָא חֵן» — «نوح فیض یافت» (پیدایش ۶)",
      "نوגَه («درخشش») = ۵۸",
    ],
    asociacionesEn: [
      "נֹחַ (Noach) = 58",
      "חֵן (Chen, “grace”) = 58 — anagram of Noach",
      "«וְנֹחַ מָצָא חֵן» — “Noach found grace” (Genesis 6:8)",
      "נֹגַהּ (Nogah, “radiance”) = 58",
    ],
    color: "#5a9a6a",
  },
  {
    num: 61, he: "אֲנִי · אַיִן", titulo: "El «Yo» y la Nada", tituloFa: "«من» و نیستی", tituloEn: "The “I” and Nothingness",
    sig: "Ani («yo») = Ayin («nada») = 61 — las mismas letras: el yo (ani) revuelto se vuelve nada (ayin); ego e infinito comparten número.",
    sigFa: "اَنی («من») = اَین («نیستی») = ۶۱ — همان حروف: «منِ» (اَنی) درهم‌ریخته «نیستی» (اَین) می‌شود؛ خودی و بی‌نهایت هم‌عددند.",
    sigEn: "Ani (“I”) = Ayin (“nothing”) = 61 — the same letters: the self (ani) rearranged becomes nothing (ayin); ego and the infinite share one number.",
    asociaciones: [
      "אֲנִי (Ani, «yo») = 61",
      "אַיִן (Ayin, «nada») = 61 — anagrama de Ani",
      "El tzimtzum: el «yo» se anula en la Nada divina (bitul)",
    ],
    asociacionesFa: [
      "اَنی («من») = ۶۱",
      "اَین («نیستی») = ۶۱ — واروخوانیِ اَنی",
      "تزیمتزوم: «من» در نیستیِ الهی محو می‌شود (بیطول)",
    ],
    asociacionesEn: [
      "אֲנִי (Ani, “I”) = 61",
      "אַיִן (Ayin, “nothing”) = 61 — anagram of Ani",
      "The tzimtzum: the “I” annuls itself in the divine Nothing (bitul)",
    ],
    color: "#8866cc",
  },
  {
    num: 130, he: "סֻלָּם · סִינַי", titulo: "La escalera y el Sinaí", tituloFa: "نردبان و سینا", tituloEn: "The Ladder and Sinai",
    sig: "Sulam («escalera» de Jacob) = Sinaí = 130 — la escalera del sueño y el monte de la Torá son la misma vía al cielo.",
    sigFa: "سولام («نردبانِ» یعقوب) = سینای = ۱۳۰ — نردبانِ رؤیا و کوهِ تورات، یک راه به آسمان‌اند.",
    sigEn: "Sulam (Jacob's “ladder”) = Sinai = 130 — the ladder of the dream and the mountain of the Torah are the same road to heaven.",
    asociaciones: [
      "סֻלָּם (Sulam, «escalera», Gn 28:12) = 130",
      "סִינַי (Sinaí) = 130",
      "Ambos: el puente entre cielo y tierra (Midrash)",
      "130 = 5 × 26 (cinco veces el Nombre)",
    ],
    asociacionesFa: [
      "سولام («نردبان»، پیدایش ۲۸) = ۱۳۰",
      "سینای = ۱۳۰",
      "هر دو: پلِ میانِ آسمان و زمین (میدراش)",
      "۱۳۰ = ۵ × ۲۶ (پنج بار نام)",
    ],
    asociacionesEn: [
      "סֻלָּם (Sulam, “ladder,” Gen 28:12) = 130",
      "סִינַי (Sinai) = 130",
      "Both: the bridge between heaven and earth (Midrash)",
      "130 = 5 × 26 (five times the Name)",
    ],
    color: "#6688cc",
  },
  {
    num: 156, he: "יוֹסֵף · צִיּוֹן", titulo: "Yosef y Tzión", tituloFa: "یوسف و صهیون", tituloEn: "Yosef and Tzion",
    sig: "Yosef = Tzión = 156 — el justo que sostiene al mundo y la ciudad santa comparten valor (= 6 × 26).",
    sigFa: "یوسف = صهیون = ۱۵۶ — صدّیقی که جهان را نگاه می‌دارد و شهرِ مقدّس یک ارزش دارند (= ۶ × ۲۶).",
    sigEn: "Yosef = Tzion = 156 — the righteous one who sustains the world and the holy city share one value (= 6 × 26).",
    asociaciones: [
      "יוֹסֵף (Yosef) = 156",
      "צִיּוֹן (Tzión) = 156",
      "Yosef HaTzadik = el fundamento (Yesod) del mundo",
      "156 = 6 × 26 (seis veces el Nombre)",
    ],
    asociacionesFa: [
      "یوسف = ۱۵۶",
      "صهیون = ۱۵۶",
      "یوسفِ صدّیق = بنیادِ (یِسود) جهان",
      "۱۵۶ = ۶ × ۲۶ (شش بار نام)",
    ],
    asociacionesEn: [
      "יוֹסֵף (Yosef) = 156",
      "צִיּוֹן (Tzion) = 156",
      "Yosef HaTzaddik = the foundation (Yesod) of the world",
      "156 = 6 × 26 (six times the Name)",
    ],
    color: "#b89a4e",
  },
  {
    num: 78, he: "לֶחֶם · מֶלַח", titulo: "El pan y la sal", tituloFa: "نان و نمک", tituloEn: "Bread and Salt",
    sig: "Lejem («pan») = Melaj («sal») = 78 — las mismas tres letras reordenadas; el sustento y el pacto comparten valor (= 3 × 26).",
    sigFa: "لِخِم («نان») = مِلَح («نمک») = ۷۸ — همان سه حرفِ جابجاشده؛ روزی و پیمان یک ارزش دارند (= ۳ × ۲۶).",
    sigEn: "Lechem (“bread”) = Melach (“salt”) = 78 — the same three letters rearranged; sustenance and covenant share one value (= 3 × 26).",
    asociaciones: [
      "לֶחֶם (Lejem, «pan») = 78",
      "מֶלַח (Melaj, «sal») = 78 — anagrama de Lejem (mismas letras)",
      "El «pacto de sal» eterno (Lv 2:13); pan y sal sobre la mesa-altar",
      "78 = 3 × 26 (tres veces el Nombre YHVH)",
    ],
    asociacionesFa: [
      "لِخِم («نان») = ۷۸",
      "مِلَح («نمک») = ۷۸ — واروخوانیِ لِخِم (همان حروف)",
      "«پیمانِ نمک»ِ ابدی (لاویان ۲:۱۳)؛ نان و نمک بر سفره-مذبح",
      "۷۸ = ۳ × ۲۶ (سه بار نامِ یهوه)",
    ],
    asociacionesEn: [
      "לֶחֶם (Lechem, “bread”) = 78",
      "מֶלַח (Melach, “salt”) = 78 — anagram of Lechem (same letters)",
      "The eternal “covenant of salt” (Lev 2:13); bread and salt on the table-altar",
      "78 = 3 × 26 (three times the Name YHVH)",
    ],
    color: "#b89a4e",
  },
  {
    num: 182, he: "יַעֲקֹב", titulo: "Yaakov, el séptuple Nombre", tituloFa: "یعقوب", tituloEn: "Yaakov, the Sevenfold Name",
    sig: "Yaakov = 182 = 7 × 26 — el tercer patriarca, columna central (Tiferet), contiene siete veces el Nombre YHVH.",
    sigFa: "یعقوب = ۱۸۲ = ۷ × ۲۶ — سومین پدرِ قوم، ستونِ میانی (تیفِرِت)، هفت بار نامِ یهوه را دربر دارد.",
    sigEn: "Yaakov = 182 = 7 × 26 — the third patriarch, the central pillar (Tiferet), contains the Name YHVH seven times.",
    asociaciones: [
      "יַעֲקֹב (Yaakov) = 182",
      "182 = 7 × 26 (siete veces el Nombre YHVH)",
      "Yaakov = Tiferet, la columna central del Árbol de la Vida",
      "Junto a Yosef (156 = 6×26) forma la cadena de múltiplos del Nombre",
    ],
    asociacionesFa: [
      "یعقوب = ۱۸۲",
      "۱۸۲ = ۷ × ۲۶ (هفت بار نامِ یهوه)",
      "یعقوب = تیفِرِت، ستونِ میانیِ درختِ زندگی",
      "همراه با یوسف (۱۵۶ = ۶×۲۶) زنجیرهٔ مضاربِ نام را می‌سازد",
    ],
    asociacionesEn: [
      "יַעֲקֹב (Yaakov) = 182",
      "182 = 7 × 26 (seven times the Name YHVH)",
      "Yaakov = Tiferet, the central pillar of the Tree of Life",
      "Together with Yosef (156 = 6×26) he forms the chain of multiples of the Name",
    ],
    color: "#c9a43e",
  },
  {
    num: 345, he: "מֹשֶׁה · הַשֵּׁם", titulo: "Moshé, el espejo del Nombre", tituloFa: "موسی، آینهٔ نام", tituloEn: "Moshe, the Mirror of the Name",
    sig: "Moshé = HaShem («el Nombre») = 345 — y su valor invertido, 543, es Ehyé Asher Ehyé, el Nombre que oyó en la zarza (Arí).",
    sigFa: "موسی = هَشِم («نام») = ۳۴۵ — و ارزشِ واژگونش، ۵۴۳، همان اِهیه اَشِر اِهیه است، نامی که در بوته شنید (آری).",
    sigEn: "Moshe = HaShem (“the Name”) = 345 — and his value reversed, 543, is Ehyeh Asher Ehyeh, the Name he heard at the bush (Ari).",
    asociaciones: [
      "מֹשֶׁה (Moshé) = 345",
      "הַשֵּׁם (HaShem, «el Nombre») = 345",
      "345 invertido = 543 = Ehyé Asher Ehyé, el Nombre de la zarza (Éx 3:14)",
    ],
    asociacionesFa: [
      "موسی = ۳۴۵",
      "هَشِم («نام») = ۳۴۵",
      "۳۴۵ واژگون = ۵۴۳ = اِهیه اَشِر اِهیه، نامِ بوته (خروج ۳:۱۴)",
    ],
    asociacionesEn: [
      "מֹשֶׁה (Moshe) = 345",
      "הַשֵּׁם (HaShem, “the Name”) = 345",
      "345 reversed = 543 = Ehyeh Asher Ehyeh, the Name of the bush (Ex 3:14)",
    ],
    color: "#7a8ad0",
  },
  {
    num: 395, he: "נְשָׁמָה · הַשָּׁמַיִם", titulo: "El alma y los cielos", tituloFa: "روح و آسمان‌ها", tituloEn: "The Soul and the Heavens",
    sig: "Neshamá («alma») = HaShamayim («los cielos») = 395 — el alma comparte valor con los cielos: su raíz está arriba.",
    sigFa: "نِشاما («روح») = هَشامَییم («آسمان‌ها») = ۳۹۵ — روح با آسمان‌ها هم‌ارزش است: ریشه‌اش در بالاست.",
    sigEn: "Neshamah (“soul”) = HaShamayim (“the heavens”) = 395 — the soul shares its value with the heavens: its root is above.",
    asociaciones: [
      "נְשָׁמָה (Neshamá, «alma») = 395",
      "הַשָּׁמַיִם (HaShamayim, «los cielos») = 395",
      "El alma es «porción de Dios desde lo alto» (Job 31:2)",
      "Dios sopló el alma de vida en el hombre (Gn 2:7)",
    ],
    asociacionesFa: [
      "نِشاما («روح») = ۳۹۵",
      "هَشامَییم («آسمان‌ها») = ۳۹۵",
      "روح «بهره‌ای از خدا از فراز» است (ایوب ۳۱:۲)",
      "خدا نَفَسِ زندگی در آدم دمید (پیدایش ۲:۷)",
    ],
    asociacionesEn: [
      "נְשָׁמָה (Neshamah, “soul”) = 395",
      "הַשָּׁמַיִם (HaShamayim, “the heavens”) = 395",
      "The soul is “a portion of God from on high” (Job 31:2)",
      "God breathed the soul of life into man (Gen 2:7)",
    ],
    color: "#8866cc",
  },
  {
    num: 441, he: "אֱמֶת", titulo: "Emet, el sello de verdad", tituloFa: "اِمِت، مُهرِ حقیقت", tituloEn: "Emet, the Seal of Truth",
    sig: "Emet («verdad») = 441 = 21² — el cuadrado de Ehyé (21); «el sello de Dios es la verdad» (Shabat 55a).",
    sigFa: "اِمِت («حقیقت») = ۴۴۱ = ۲۱² — مربعِ اِهیه (۲۱)؛ «مُهرِ خدا حقیقت است» (شَبات ۵۵a).",
    sigEn: "Emet (“truth”) = 441 = 21² — the square of Ehyeh (21); “the seal of God is truth” (Shabbat 55a).",
    asociaciones: [
      "אֱמֶת (Emet, «verdad») = 441",
      "441 = 21² — el cuadrado de אֶהְיֶה (Ehyé, 21)",
      "Sus letras א-מ-ת abarcan el principio, el medio y el fin del alefbet",
      "«El sello del Santo, bendito sea, es la verdad» (Shabat 55a)",
    ],
    asociacionesFa: [
      "اِمِت («حقیقت») = ۴۴۱",
      "۴۴۱ = ۲۱² — مربعِ اِهیه (۲۱)",
      "حروفِ א-מ-ת آغاز، میان و پایانِ الفبا را دربر می‌گیرند",
      "«مُهرِ قدّوسِ متبارک حقیقت است» (شَبات ۵۵a)",
    ],
    asociacionesEn: [
      "אֱמֶת (Emet, “truth”) = 441",
      "441 = 21² — the square of אֶהְיֶה (Ehyeh, 21)",
      "Its letters א-מ-ת span the beginning, the middle and the end of the alef-bet",
      "“The seal of the Holy One, blessed be He, is truth” (Shabbat 55a)",
    ],
    color: "#d4a838",
  },
  {
    num: 15, he: "יָהּ · ט\"ו", titulo: "Yah, el Nombre del 15", tituloFa: "یاه، نامِ پانزده", tituloEn: "Yah, the Name of 15",
    sig: "Yah (יה) = 15 — la mitad del Nombre; por eso el día 15 se escribe ט\"ו (9+6) y no יה, para no escribir parte del Nombre divino.",
    sigFa: "یاه (یה) = ۱۵ — نیمی از نام؛ از این رو روزِ پانزدهم را ט\"ו (۹+۶) می‌نویسند، نه یה، تا بخشی از نامِ الهی نوشته نشود.",
    sigEn: "Yah (יה) = 15 — half of the Name; that is why the 15th day is written ט\"ו (9+6) and not יה, so as not to write part of the divine Name.",
    asociaciones: [
      "יָהּ (Yah) = 15 = Yud(10) + Hei(5)",
      "El 15 del mes se escribe ט\"ו (9+6), no יה, por respeto al Nombre",
      "«Yah es mi fuerza y mi canción» (Éx 15:2 — el Canto del Mar)",
      "Los 15 Cánticos de las Gradas (Shir HaMaalot, Salmos 120–134)",
    ],
    asociacionesFa: [
      "یاه = ۱۵ = یود(۱۰) + هی(۵)",
      "پانزدهمِ ماه را ט\"ו (۹+۶) می‌نویسند، نه یה، به‌احترامِ نام",
      "«یاه قوّت و سرودِ من است» (خروج ۱۵:۲ — سرودِ دریا)",
      "پانزده سرودِ پلّه‌ها (شیر هَمَعَلوت، مزامیر ۱۲۰–۱۳۴)",
    ],
    asociacionesEn: [
      "יָהּ (Yah) = 15 = Yud(10) + Hei(5)",
      "The 15th of the month is written ט\"ו (9+6), not יה, out of reverence for the Name",
      "“Yah is my strength and my song” (Ex 15:2 — the Song of the Sea)",
      "The 15 Songs of Ascents (Shir HaMaalot, Psalms 120–134)",
    ],
    color: "#c9a43e",
  },
  {
    num: 36, he: "ל\"ו · לוֹ", titulo: "Los 36 ocultos", tituloFa: "سی‌وشش پنهان", tituloEn: "The 36 Hidden Ones",
    sig: "Lamed-Vav (ל\"ו) = 36 — los 36 justos ocultos que sostienen el mundo; y 36 = doble de Jai (18), la vida duplicada.",
    sigFa: "لَمِد-واو (ל\"ו) = ۳۶ — سی‌وشش صدّیقِ پنهان که جهان را نگاه می‌دارند؛ و ۳۶ = دوبرابرِ خَی (۱۸)، زندگیِ دوچندان.",
    sigEn: "Lamed-Vav (ל\"ו) = 36 — the 36 hidden righteous who sustain the world; and 36 = double Chai (18), life doubled.",
    asociaciones: [
      "ל\"ו (Lamed-Vav) = 36 — los 36 tzadikim ocultos (Suká 45b, Sanhedrín 97b)",
      "36 = 2 × 18 (חַי, «vida») — la vida duplicada",
      "Las 36 velas de Janucá en total (1+2+…+8, sin el shamash)",
      "לוֹ (Lo, «a él») = 36",
    ],
    asociacionesFa: [
      "ל\"ו (لَمِد-واو) = ۳۶ — سی‌وشش تزادیکِ پنهان (سوکا ۴۵b، سنهدرین ۹۷b)",
      "۳۶ = ۲ × ۱۸ (خَی، «زندگی») — زندگیِ دوچندان",
      "سی‌وشش شمعِ حنوکا روی‌هم (۱+۲+…+۸، بی‌شامش)",
      "لوֹ («به او») = ۳۶",
    ],
    asociacionesEn: [
      "ל\"ו (Lamed-Vav) = 36 — the 36 hidden tzaddikim (Sukkah 45b, Sanhedrin 97b)",
      "36 = 2 × 18 (חַי, “life”) — life doubled",
      "The 36 Chanukah lights in all (1+2+…+8, without the shamash)",
      "לוֹ (Lo, “to him”) = 36",
    ],
    color: "#5a9a6a",
  },
  {
    num: 311, he: "אִישׁ · אִשָּׁה · אֵשׁ", titulo: "El hombre, la mujer y el fuego", tituloFa: "مرد، زن و آتش", tituloEn: "The Man, the Woman and the Fire",
    sig: "Ish («hombre») = 311, Ishá («mujer») = 306; quita la י de él y la ה de ella —el Nombre יה (15)— y a ambos les queda אֵשׁ («fuego») = 301: con Dios entre ellos, paz; sin Él, fuego (Sotá 17a).",
    sigFa: "ایش («مرد») = ۳۱۱، ایشا («زن») = ۳۰۶؛ یِ او و هِ او —نامِ یה (۱۵)— را بردار، برای هر دو אֵשׁ («آتش») = ۳۰۱ می‌ماند: با خدا میانشان، صلح؛ بی او، آتش (سوطا ۱۷a).",
    sigEn: "Ish (“man”) = 311, Ishah (“woman”) = 306; remove his י and her ה —the Name יה (15)— and both are left with אֵשׁ (“fire”) = 301: with God between them, peace; without Him, fire (Sotah 17a).",
    asociaciones: [
      "אִישׁ (Ish, «hombre») = 311",
      "אִשָּׁה (Ishá, «mujer») = 306",
      "Quita la י (de ish) y la ה (de ishá) → a ambos les queda אֵשׁ (esh, «fuego») = 301",
      "Esas dos letras forman יָהּ (Yah, 15): si lo merecen, la Presencia mora entre ellos; si no, el fuego los consume (Sotá 17a)",
    ],
    asociacionesFa: [
      "ایش («مرد») = ۳۱۱",
      "ایشا («زن») = ۳۰۶",
      "یِ ایش و هِ ایشا را بردار → برای هر دو אֵשׁ (اِش، «آتش») = ۳۰۱ می‌ماند",
      "این دو حرف یָהּ (یاه، ۱۵) را می‌سازند: اگر سزاوار باشند، شخینا میانشان ساکن می‌شود؛ وگرنه آتش آنان را می‌بلعد (سوطا ۱۷a)",
    ],
    asociacionesEn: [
      "אִישׁ (Ish, “man”) = 311",
      "אִשָּׁה (Ishah, “woman”) = 306",
      "Remove the י (from ish) and the ה (from ishah) → both are left with אֵשׁ (esh, “fire”) = 301",
      "Those two letters form יָהּ (Yah, 15): if they are worthy, the Presence dwells between them; if not, fire consumes them (Sotah 17a)",
    ],
    color: "#cc5555",
  },
  {
    num: 430, he: "נֶפֶשׁ", titulo: "Néfesh, el alma y el exilio", tituloFa: "نِفِش، روح و تبعید", tituloEn: "Nefesh, the Soul and the Exile",
    sig: "Néfesh («alma viva») = 430 — el nivel del alma ligado al cuerpo; y 430 = los años de la estancia en Egipto (Éx 12:40).",
    sigFa: "نِفِش («روحِ زنده») = ۴۳۰ — سطحی از روح که به بدن بسته است؛ و ۴۳۰ = سال‌های اقامت در مصر (خروج ۱۲:۴۰).",
    sigEn: "Nefesh (“living soul”) = 430 — the level of the soul bound to the body; and 430 = the years of the sojourn in Egypt (Ex 12:40).",
    asociaciones: [
      "נֶפֶשׁ (Néfesh, «alma») = 430",
      "El Néfesh es el más bajo de los niveles del alma, vinculado a la sangre y al cuerpo (Lv 17:11)",
      "430 = los años de la estancia de Israel en Egipto (Éx 12:40) — conteo, no valor de letras",
    ],
    asociacionesFa: [
      "نِفِش («روح») = ۴۳۰",
      "نِفِش پایین‌ترین سطحِ روح است، بسته به خون و بدن (لاویان ۱۷:۱۱)",
      "۴۳۰ = سال‌های اقامتِ اسرائیل در مصر (خروج ۱۲:۴۰) — شمارش، نه ارزشِ حروف",
    ],
    asociacionesEn: [
      "נֶפֶשׁ (Nefesh, “soul”) = 430",
      "The Nefesh is the lowest level of the soul, bound to the blood and the body (Lev 17:11)",
      "430 = the years of Israel's sojourn in Egypt (Ex 12:40) — a count, not a letter value",
    ],
    color: "#8866cc",
  },
  {
    num: 600, he: "צִיצִית", titulo: "Tzitzit y las 613", tituloFa: "تزیتزیت و ششصدوسیزده", tituloEn: "Tzitzit and the 613",
    sig: "Tzitzit (deletreado pleno) = 600; más los 8 hilos y los 5 nudos suma 613 — al ver el tzitzit se recuerdan todas las mitzvot (Rashi a Núm 15:39).",
    sigFa: "تزیتزیت (به‌حروفِ کامل) = ۶۰۰؛ به‌علاوهٔ ۸ رشته و ۵ گره می‌شود ۶۱۳ — با دیدنِ تزیتزیت همهٔ میتزووت به یاد می‌آید (راشی بر اعداد ۱۵:۳۹).",
    sigEn: "Tzitzit (spelled in full) = 600; add the 8 threads and the 5 knots and it reaches 613 — seeing the tzitzit recalls all the mitzvot (Rashi on Num 15:39).",
    asociaciones: [
      "צִיצִית (Tzitzit, deletreo pleno) = 600",
      "600 + 8 hilos + 5 nudos = 613 (todas las mitzvot) — Rashi a Números 15:39",
      "«Lo veréis y recordaréis todos los mandamientos del Señor» (Núm 15:39)",
      "El hilo de tejelet (azul) evoca el mar, el cielo y el Trono de gloria (Menajot 43b)",
    ],
    asociacionesFa: [
      "צִיצִית (تزیتزیت، به‌حروفِ کامل) = ۶۰۰",
      "۶۰۰ + ۸ رشته + ۵ گره = ۶۱۳ (همهٔ میتزووت) — راشی بر اعداد ۱۵:۳۹",
      "«آن را ببینید و همهٔ احکامِ خداوند را به یاد آورید» (اعداد ۱۵:۳۹)",
      "رشتهٔ تِخِلِت (آبی) یادآورِ دریا، آسمان و تختِ جلال است (مِناخوت ۴۳b)",
    ],
    asociacionesEn: [
      "צִיצִית (Tzitzit, full spelling) = 600",
      "600 + 8 threads + 5 knots = 613 (all the mitzvot) — Rashi on Numbers 15:39",
      "“You shall see it and remember all the commandments of the Lord” (Num 15:39)",
      "The thread of techelet (blue) evokes the sea, the sky and the Throne of Glory (Menachot 43b)",
    ],
    color: "#6688cc",
  },
  {
    num: 14, he: "דָּוִד · יָד", titulo: "David y la mano", tituloFa: "داوود و دست", tituloEn: "David and the Hand",
    sig: "David (דָּוִד) = Yad («mano») = 14 — el rey ungido, raíz de Maljut y del Mashíaj, comparte valor con la «mano» que unge y gobierna.",
    sigFa: "داوود (דָוִד) = یَد («دست») = ۱۴ — پادشاهِ مسح‌شده، ریشهٔ مَلخوت و ماشیَح، با «دست»ی که مسح می‌کند و حکم می‌راند هم‌ارزش است.",
    sigEn: "David (דָּוִד) = Yad (“hand”) = 14 — the anointed king, root of Malchut and of Mashiach, shares his value with the “hand” that anoints and rules.",
    asociaciones: [
      "דָּוִד (David) = 14 = ד(4)+ו(6)+ד(4)",
      "יָד (Yad, «mano») = 14",
      "David encarna Maljut, el reino, y es la raíz del Mashíaj ben David",
      "Sus letras ד-ו-ד: dos «puertas» (dalet) unidas por la «vav» del vínculo",
    ],
    asociacionesFa: [
      "דָּוִד (داوود) = ۱۴ = د(۴)+و(۶)+د(۴)",
      "יָד (یَد، «دست») = ۱۴",
      "داوود تجسّمِ مَلخوت است، پادشاهی و ریشهٔ ماشیَح بن داوود",
      "حروفِ ד-ו-ד: دو «دروازه» (دالِت) که با «واو»ِ پیوند به‌هم می‌رسند",
    ],
    asociacionesEn: [
      "דָּוִד (David) = 14 = ד(4)+ו(6)+ד(4)",
      "יָד (Yad, “hand”) = 14",
      "David embodies Malchut, kingship, and is the root of Mashiach ben David",
      "His letters ד-ו-ד: two “doors” (dalet) joined by the “vav” of connection",
    ],
    color: "#a06a8e",
  },
  {
    num: 148, he: "נֵצַח · פֶּסַח", titulo: "Netzaj y Pésaj", tituloFa: "نِتزَح و پِسَح", tituloEn: "Netzach and Pesach",
    sig: "Netzaj («eternidad/victoria») = Pésaj = 148 — la fiesta de la liberación es, en su valor, la séfira de la victoria que perdura.",
    sigFa: "نِتزَح («ابدیت/پیروزی») = پِسَح (فِصح) = ۱۴۸ — جشنِ رهایی در ارزشش همان سِفیرای پیروزیِ ماندگار است.",
    sigEn: "Netzach (“eternity/victory”) = Pesach = 148 — the festival of liberation is, in its value, the sefirah of enduring victory.",
    asociaciones: [
      "נֵצַח (Netzaj, «victoria, eternidad») = 148",
      "פֶּסַח (Pésaj) = 148",
      "Netzaj significa a la vez «victoria» y «eternidad»; Pésaj es el triunfo perdurable del éxodo",
      "La raíz נצח da «lamnatzéaj» (al director del coro) en los Salmos",
    ],
    asociacionesFa: [
      "נֵצַח (نِتزَح، «پیروزی، ابدیت») = ۱۴۸",
      "פֶּסַח (پِسَح) = ۱۴۸",
      "نِتزَح هم «پیروزی» است و هم «ابدیت»؛ پِسَح پیروزیِ ماندگارِ خروج است",
      "ریشهٔ נצח در مزامیر «لَمنَتزِح» (سرپرستِ سرود) را می‌سازد",
    ],
    asociacionesEn: [
      "נֵצַח (Netzach, “victory, eternity”) = 148",
      "פֶּסַח (Pesach) = 148",
      "Netzach means both “victory” and “eternity”; Pesach is the enduring triumph of the Exodus",
      "The root נצח gives “lamnatzeach” (to the choirmaster) in the Psalms",
    ],
    color: "#5a9a6a",
  },
  {
    num: 208, he: "יִצְחָק", titulo: "Yitzjak, el óctuple Nombre", tituloFa: "اسحاق", tituloEn: "Yitzchak, the Eightfold Name",
    sig: "Yitzjak = 208 = 8 × 26 — el segundo patriarca, séfira de Guevurá, contiene ocho veces el Nombre YHVH; completa la cadena con Yosef (156=6×26) y Yaakov (182=7×26).",
    sigFa: "اسحاق = ۲۰۸ = ۸ × ۲۶ — دومین پدرِ قوم، سِفیرای گِوورا، هشت بار نامِ یهوه را دربر دارد؛ زنجیره را با یوسف (۱۵۶=۶×۲۶) و یعقوب (۱۸۲=۷×۲۶) کامل می‌کند.",
    sigEn: "Yitzchak = 208 = 8 × 26 — the second patriarch, the sefirah of Gevurah, contains the Name YHVH eight times; he completes the chain with Yosef (156=6×26) and Yaakov (182=7×26).",
    asociaciones: [
      "יִצְחָק (Yitzjak) = 208",
      "208 = 8 × 26 (ocho veces el Nombre YHVH)",
      "Yitzjak = Guevurá, el rigor; «el Temor (Pajad) de Yitzjak» (Gn 31:42)",
      "Cadena de múltiplos del Nombre: Yosef 156 (6×26), Yaakov 182 (7×26), Yitzjak 208 (8×26)",
    ],
    asociacionesFa: [
      "יִצְחָק (اسحاق) = ۲۰۸",
      "۲۰۸ = ۸ × ۲۶ (هشت بار نامِ یهوه)",
      "اسحاق = گِوورا، سخت‌گیری؛ «هراسِ (پَحَد) اسحاق» (پیدایش ۳۱:۴۲)",
      "زنجیرهٔ مضاربِ نام: یوسف ۱۵۶ (۶×۲۶)، یعقوب ۱۸۲ (۷×۲۶)، اسحاق ۲۰۸ (۸×۲۶)",
    ],
    asociacionesEn: [
      "יִצְחָק (Yitzchak) = 208",
      "208 = 8 × 26 (eight times the Name YHVH)",
      "Yitzchak = Gevurah, rigor; “the Fear (Pachad) of Yitzchak” (Gen 31:42)",
      "Chain of multiples of the Name: Yosef 156 (6×26), Yaakov 182 (7×26), Yitzchak 208 (8×26)",
    ],
    color: "#cc5555",
  },
  {
    num: 410, he: "שְׁמַע · קָדוֹשׁ", titulo: "Escucha y santidad", tituloFa: "شِمَع و قدّوس", tituloEn: "Hearing and Holiness",
    sig: "Shemá («escucha») = Kadosh («santo») = 410 — el llamado a escuchar la unidad comparte valor con la santidad; y el Primer Templo se mantuvo en pie 410 años.",
    sigFa: "شِمَع («بشنو») = کادوش («مقدّس») = ۴۱۰ — فراخوانِ شنیدنِ یگانگی با قداست هم‌ارزش است؛ و معبدِ نخست ۴۱۰ سال برپا ماند.",
    sigEn: "Shema (“hear”) = Kadosh (“holy”) = 410 — the call to hear the oneness shares its value with holiness; and the First Temple stood for 410 years.",
    asociaciones: [
      "שְׁמַע (Shemá, «escucha») = 410",
      "קָדוֹשׁ (Kadosh, «santo») = 410",
      "El Primer Templo permaneció en pie 410 años (Yomá 9a) — dato histórico, no valor de letras",
      "«Shemá Israel»: escuchar es el acto de santificar la unidad de Dios",
    ],
    asociacionesFa: [
      "שְׁמַע (شِمَع، «بشنو») = ۴۱۰",
      "קָדוֹשׁ (کادوش، «مقدّس») = ۴۱۰",
      "معبدِ نخست ۴۱۰ سال برپا ماند (یوما ۹a) — دادهٔ تاریخی، نه ارزشِ حروف",
      "«شِمَع ییسرائل»: شنیدن، همان عملِ تقدیسِ یگانگیِ خداست",
    ],
    asociacionesEn: [
      "שְׁמַע (Shema, “hear”) = 410",
      "קָדוֹשׁ (Kadosh, “holy”) = 410",
      "The First Temple stood for 410 years (Yoma 9a) — a historical datum, not a letter value",
      "“Shema Yisrael”: hearing is the act of sanctifying God's oneness",
    ],
    color: "#c9a43e",
  },
  {
    num: 301, he: "מְנוֹרָה · אֵשׁ", titulo: "La menorá y el fuego", tituloFa: "منورا و آتش", tituloEn: "The Menorah and the Fire",
    sig: "Menorá = Esh («fuego») = 301 — el candelabro del Templo es, en su valor, el fuego mismo: luz que arde sin consumirse.",
    sigFa: "منورا = اِش («آتش») = ۳۰۱ — چراغدانِ معبد در ارزشش همان آتش است: نوری که می‌سوزد بی‌آنکه فانی شود.",
    sigEn: "Menorah = Esh (“fire”) = 301 — the Temple lampstand is, in its value, fire itself: light that burns without being consumed.",
    asociaciones: [
      "מְנוֹרָה (Menorá) = 301",
      "אֵשׁ (Esh, «fuego») = 301",
      "La menorá porta la llama: su esencia numérica es el fuego/luz",
      "אֵשׁ (301) reaparece entre «ish» e «ishá» (ver 311): el fuego que une o consume",
    ],
    asociacionesFa: [
      "מְנוֹרָה (منورا) = ۳۰۱",
      "אֵשׁ (اِش، «آتش») = ۳۰۱",
      "منورا حاملِ شعله است: ذاتِ عددی‌اش آتش/نور است",
      "אֵשׁ (۳۰۱) میانِ «ایش» و «ایشا» نیز بازمی‌گردد (نگاه کنید به ۳۱۱): آتشی که می‌پیوندد یا می‌بلعد",
    ],
    asociacionesEn: [
      "מְנוֹרָה (Menorah) = 301",
      "אֵשׁ (Esh, “fire”) = 301",
      "The menorah bears the flame: its numerical essence is fire/light",
      "אֵשׁ (301) reappears between “ish” and “ishah” (see 311): the fire that joins or consumes",
    ],
    color: "#d4a838",
  },
  {
    num: 31, he: "אֵל · לֹא", titulo: "«Dios» y «no»", tituloFa: "«خدا» و «نه»", tituloEn: "“God” and “No”",
    sig: "El («Dios») = Lo («no») = 31 — las mismas dos letras invertidas: el Nombre del poder divino se esconde dentro de la negación misma.",
    sigFa: "اِل («خدا») = لو («نه») = ۳۱ — همان دو حرفِ واژگون: نامِ نیرویِ الهی در دلِ خودِ نفی پنهان است.",
    sigEn: "El (“God”) = Lo (“no”) = 31 — the same two letters reversed: the Name of divine power hides within negation itself.",
    asociaciones: [
      "אֵל (El, «Dios», el Nombre de Jésed) = 31 = א(1)+ל(30)",
      "לֹא (Lo, «no») = 31 — las mismas letras de El, invertidas (anagrama)",
      "Aun en el «no» se oculta el «El»: ningún lugar está vacío de Dios",
      "Yehoshúa venció a 31 reyes de Canaán (Jos 12:24) — conteo, no valor de letras",
    ],
    asociacionesFa: [
      "اِل («خدا»، نامِ خِسِد) = ۳۱ = א(۱)+ל(۳۰)",
      "لو («نه») = ۳۱ — همان حروفِ اِل، واژگون (واروخوانی)",
      "حتی در «نه» نیز «اِل» پنهان است: هیچ جا از خدا تهی نیست",
      "یهوشَع بر سی‌ویک پادشاهِ کنعان پیروز شد (یوشَع ۱۲) — شمارش، نه ارزشِ حروف",
    ],
    asociacionesEn: [
      "אֵל (El, “God,” the Name of Chesed) = 31 = א(1)+ל(30)",
      "לֹא (Lo, “no”) = 31 — the same letters as El, reversed (anagram)",
      "Even in the “no” the “El” is hidden: no place is empty of God",
      "Yehoshua defeated 31 kings of Canaan (Josh 12:24) — a count, not a letter value",
    ],
    color: "#d4a838",
  },
  {
    num: 73, he: "חָכְמָה · כֹּחַ־מָה", titulo: "Jojmá, «el poder del qué»", tituloFa: "حُخما، «نیرویِ چیستی»", tituloEn: "Chochmah, “the Power of What”",
    sig: "Jojmá («sabiduría») = 73 = Kóaj Mah («el poder del qué/de la humildad») — la sabiduría es el poder de anularse ante el Infinito (Zohar, Ginsburgh).",
    sigFa: "حُخما («حکمت») = ۷۳ = کوآح مَه («نیرویِ چیستی/فروتنی») — حکمت، توانِ خودانکاری در برابرِ بی‌نهایت است (زوهر، گینزبورگ).",
    sigEn: "Chochmah (“wisdom”) = 73 = Koach Mah (“the power of what / of selflessness”) — wisdom is the power to annul oneself before the Infinite (Zohar, Ginsburgh).",
    asociaciones: [
      "חָכְמָה (Jojmá, «sabiduría») = 73",
      "חָכְמָה se lee כֹּחַ־מָה: כֹּחַ (Kóaj, 28) + מָה (Mah, 45) = 73",
      "Jojmá es la segunda sefirá, el primer destello de la intuición",
      "Génesis 1:1 tiene exactamente 28 letras = כֹּחַ (Kóaj, «poder») — conteo de letras",
    ],
    asociacionesFa: [
      "חָכְמָה (حُخما، «حکمت») = ۷۳",
      "חָכְמָה را کوآح مَه می‌خوانند: כֹּחַ (کوآح، ۲۸) + מָה (مَه، ۴۵) = ۷۳",
      "حُخما دومین سِفیراست، نخستین جرقهٔ شهود",
      "پیدایش ۱:۱ دقیقاً ۲۸ حرف دارد = כֹּחַ (کوآح، «نیرو») — شمارشِ حروف",
    ],
    asociacionesEn: [
      "חָכְמָה (Chochmah, “wisdom”) = 73",
      "חָכְמָה is read כֹּחַ־מָה: כֹּחַ (Koach, 28) + מָה (Mah, 45) = 73",
      "Chochmah is the second sefirah, the first flash of intuition",
      "Genesis 1:1 has exactly 28 letters = כֹּחַ (Koach, “power”) — a letter count",
    ],
    color: "#6688cc",
  },
  {
    num: 364, he: "הַשָּׂטָן", titulo: "Los días del acusador", tituloFa: "روزهای مدّعی", tituloEn: "The Days of the Accuser",
    sig: "HaSatán («el Acusador») = 364 — los días del año en que tiene permiso para acusar; en el 365º, Yom Kipur, calla (Yomá 20a).",
    sigFa: "هَساطان («مدّعی») = ۳۶۴ — روزهای سال که اجازهٔ اتهام دارد؛ در ۳۶۵مین، یوم کیپور، خاموش می‌شود (یوما ۲۰a).",
    sigEn: "HaSatan (“the Accuser”) = 364 — the days of the year on which he has license to accuse; on the 365th, Yom Kippur, he falls silent (Yoma 20a).",
    asociaciones: [
      "הַשָּׂטָן (HaSatán, «el Acusador») = 364",
      "364 = los días del año en que Satán acusa; en Yom Kipur (el 365º) no tiene poder (Yomá 20a)",
      "שָׂטָן (Satán, sin el artículo) = 359",
      "Su fuerza es la del juicio (Guevurá) que tienta y prueba",
    ],
    asociacionesFa: [
      "הַשָּׂטָן (هَساطان، «مدّعی») = ۳۶۴",
      "۳۶۴ = روزهای سال که ساطان اتهام می‌زند؛ در یوم کیپور (۳۶۵م) قدرتی ندارد (یوما ۲۰a)",
      "שָׂטָן (ساطان، بی‌حرفِ تعریف) = ۳۵۹",
      "نیرویش نیرویِ داوری (گِوورا) است که می‌آزماید و وسوسه می‌کند",
    ],
    asociacionesEn: [
      "הַשָּׂטָן (HaSatan, “the Accuser”) = 364",
      "364 = the days of the year on which Satan accuses; on Yom Kippur (the 365th) he has no power (Yoma 20a)",
      "שָׂטָן (Satan, without the article) = 359",
      "His force is that of judgment (Gevurah), which tempts and tests",
    ],
    color: "#9a3a3a",
  },
  {
    num: 378, he: "חַשְׁמַל", titulo: "Jashmal, el silencio que habla", tituloFa: "خشمل، سکوتی که سخن می‌گوید", tituloEn: "Chashmal, the Silence That Speaks",
    sig: "Jashmal = 378 — el resplandor enigmático de la visión de Yejezkel (Ez 1:4); jash (silencio) + mal (habla): los ángeles que callan y hablan (Jaguigá 13b). Es el nombre de este proyecto.",
    sigFa: "خشمل = ۳۷۸ — درخششِ معمّاییِ رؤیای یحزقیل (یحزقیل ۱:۴)؛ خَش (سکوت) + مَل (سخن): فرشتگانی که گاه خاموش و گاه گویایند (حگیگا ۱۳b). نامِ همین پروژه است.",
    sigEn: "Chashmal = 378 — the enigmatic radiance of Ezekiel's vision (Ez 1:4); chash (silence) + mal (speech): the angels who fall silent and speak (Chagigah 13b). It is the name of this project (Jashmal).",
    asociaciones: [
      "חַשְׁמַל (Jashmal) = 378 = ח(8)+ש(300)+מ(40)+ל(30)",
      "Aparece en la visión de la Merkavá: «como el ojo del jashmal, en medio del fuego» (Yejezkel 1:4)",
      "Jaguigá 13b lo lee jash + mal: las jayot a veces callan (חשות) y a veces hablan (ממללות)",
      "Da nombre a este proyecto: el silencio (jash) y el habla (mal) del estudio",
    ],
    asociacionesFa: [
      "חַשְׁמַל (خشمل) = ۳۷۸ = ח(۸)+ש(۳۰۰)+מ(۴۰)+ל(۳۰)",
      "در رؤیای مرکاوا می‌آید: «چون چشمِ خشمل، در میانِ آتش» (یحزقیل ۱:۴)",
      "حگیگا ۱۳b آن را خَش + مَل می‌خواند: خَیوت گاه خاموش‌اند (חشوت) و گاه گویا (ممللوت)",
      "نامِ همین پروژه است: سکوت (خَش) و سخنِ (مَل) مطالعه",
    ],
    asociacionesEn: [
      "חַשְׁמַל (Chashmal) = 378 = ח(8)+ש(300)+מ(40)+ל(30)",
      "It appears in the vision of the Merkavah: “like the eye of the chashmal, in the midst of the fire” (Ezekiel 1:4)",
      "Chagigah 13b reads it chash + mal: the chayot at times fall silent (חשות) and at times speak (ממללות)",
      "It gives this project its name: the silence (chash) and the speech (mal) of study",
    ],
    color: "#c9a43e",
  },
  {
    num: 913, he: "בְּרֵאשִׁית · בְּרִית אֵשׁ", titulo: "«En el principio» y el pacto de fuego", tituloFa: "«در آغاز» و پیمانِ آتش", tituloEn: "“In the Beginning” and the Covenant of Fire",
    sig: "Bereshit («En el principio») = 913 = Brit Esh («pacto de fuego») = Rosh Bait («cabeza de la casa») — la primera palabra de la Torá esconde, en sus mismas letras, el pacto ardiente de la creación.",
    sigFa: "بِرِشیت («در آغاز») = ۹۱۳ = بِریت اِش («پیمانِ آتش») = رُش بَیت («سرِ خانه») — نخستین واژهٔ تورات، در همان حروفش، پیمانِ آتشینِ آفرینش را پنهان دارد.",
    sigEn: "Bereshit (“In the beginning”) = 913 = Brit Esh (“covenant of fire”) = Rosh Bayit (“head of the house”) — the first word of the Torah hides, in its very letters, the burning covenant of creation.",
    asociaciones: [
      "בְּרֵאשִׁית (Bereshit, «En el principio») = 913",
      "בְּרִית אֵשׁ (Brit Esh, «pacto de fuego») = 612 + 301 = 913 — mismas letras reordenadas",
      "רֹאשׁ בַּיִת (Rosh Bait, «cabeza de la casa») = 501 + 412 = 913 — otro anagrama",
      "La Torá comienza con bet (ב): el mundo nace de la «casa» (bait) y del pacto",
    ],
    asociacionesFa: [
      "בְּרֵאשִׁית (بِرِشیت، «در آغاز») = ۹۱۳",
      "בְּרִית אֵשׁ (بِریت اِش، «پیمانِ آتش») = ۶۱۲ + ۳۰۱ = ۹۱۳ — همان حروفِ بازچیده",
      "רֹאשׁ בַּיִת (رُش بَیت، «سرِ خانه») = ۵۰۱ + ۴۱۲ = ۹۱۳ — واروخوانیِ دیگر",
      "تورات با بِت (ב) آغاز می‌شود: جهان از «خانه» (بَیت) و پیمان زاده می‌شود",
    ],
    asociacionesEn: [
      "בְּרֵאשִׁית (Bereshit, “In the beginning”) = 913",
      "בְּרִית אֵשׁ (Brit Esh, “covenant of fire”) = 612 + 301 = 913 — the same letters rearranged",
      "רֹאשׁ בַּיִת (Rosh Bayit, “head of the house”) = 501 + 412 = 913 — another anagram",
      "The Torah begins with bet (ב): the world is born from the “house” (bayit) and the covenant",
    ],
    color: "#e0a850",
  },
];
